In [1]:
# --- 1. Импорты и общие настройки ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from pmdarima import auto_arima
from statsmodels.tsa.statespace.sarimax import SARIMAX
from prophet import Prophet  # pip install prophet
from sklearn.metrics import mean_squared_error, mean_absolute_error
import warnings
pd.options.display.float_format = '{:.2f}'.format
warnings.filterwarnings("ignore")
# plt.style.use("seaborn-whitegrid")

In [2]:
# --- 2. Загрузка данных ---
# df должен содержать столбцы: "Регион", "Период" (YYYY-MM), и целевой столбец с показателем.
df = pd.read_excel("Датасет по птице.xlsx")
df["Период"] = pd.to_datetime(df["Период"], format="%Y-%m")
df.sample(10)

                              Регион     Период   Птица
987               ЖАМБЫЛСКАЯ ОБЛАСТЬ 2016-01-01   30.43
972                         ГШЫМКЕНТ 2025-05-01    3.60
1288          КАРАГАНДИНСКАЯ ОБЛАСТЬ 2019-12-01  937.63
1733           МАНГИСТАУСКАЯ ОБЛАСТЬ 2025-04-01 1039.88
257              АЛМАТИНСКАЯ ОБЛАСТЬ 2015-04-01 6177.95
566   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 2019-11-01 4845.89
1967            ПАВЛОДАРСКАЯ ОБЛАСТЬ 2024-09-01  128.70
1603          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ 2025-01-01    1.40
281              АЛМАТИНСКАЯ ОБЛАСТЬ 2017-04-01 7649.93
502               АТЫРАУСКАЯ ОБЛАСТЬ 2025-02-01    0.00

In [3]:
regions = df['Регион'].unique()
target   = "Птица"
horizon  = 3
epsilon = 1e-6

In [4]:
first_test = pd.to_datetime("2024-08-01")
last_possible = df["Период"].max() - pd.DateOffset(months=horizon-1)
test_starts = pd.date_range(first_test, last_possible, freq="MS")

## Holw-Winter's (log)

In [5]:
results_hw = []
for region in regions:
    ts = (df[df["Регион"] == region]
          .set_index("Период")[target]
          .dropna()
          .sort_index())
    if len(ts) < 24:
        print(f"{region}: всего {len(ts)} мес. — сезонный Holt-Winter's невозможен.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        # формируем train / test
        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]

        # пропускаем, если недостаточно данных или неполный test
        if len(train) < 24 or len(test) < horizon:
            continue

        # обучаем модель
        train_log = np.log1p(train)

        hw_log = ExponentialSmoothing(
            train_log,
            seasonal="add",
            seasonal_periods=12
        ).fit(optimized=True)

        # прогноз и метрики
        fc_log = hw_log.forecast(horizon)
        fc = np.expm1(fc_log) 
        # fc   = model.forecast(horizon)
        rmse = np.sqrt(mean_squared_error(test, fc))
        mae  = mean_absolute_error(test, fc)
        mape = (np.abs((test - fc) / test).mean()) * 100

        results_hw.append({
            "Регион":      region,
            "Test start":  test_start.strftime("%Y-%m"),
            "Test end":    test_end.strftime("%Y-%m"),
            "Forecast":    [x.round(2) for x in list(fc.values)],
            "Actual":      [y.round(2) for y in list(test.values)],
            "RMSE":        rmse,
            "MAE":         mae,
            "MAPE_%":      mape
        })

# 4) Усреднение по всем скользящим окнам для каждого региона
res_hw = pd.DataFrame(results_hw)
res_hw.to_excel("results/Птица - Результаты прогнозов ХВ.xlsx", index=False)
print("Результаты прогнозов HW на 3 месяца:")

display(res_hw)

final_hw = (
    res_hw
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_hw.to_excel("results/Птица - Результаты прогнозов ХВ средние.xlsx", index=False)
print("Средние метрики Holt–Winter's по регионам (rolling-3):")
display(final_hw)

Результаты прогнозов HW на 3 месяца:

,Регион,Test start,Test end,Forecast,Actual,RMSE,MAE,MAPE_%
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,"[11268.8, 10962.08, 10960.74]","[10080.07, 10273.59, 10251.41]",892.61,862.18,8.47
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,"[10252.48, 10257.31, 10525.67]","[10273.59, 10251.41, 8665.21]",1074.21,629.16,7.24
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,"[10269.94, 10538.61, 11740.42]","[10251.41, 8665.21, 11438.74]",1095.59,731.20,8.15
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,"[10527.16, 11727.89, 9571.69]","[8665.21, 11438.74, 8560.3]",1234.69,1054.16,11.94
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,"[10434.02, 8525.1, 8451.39]","[11438.74, 8560.3, 12551.51]",2437.33,1713.35,13.95
...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,"[354.92, 526.86, 541.42]","[810.6, 641.64, 802.3]",310.31,277.11,35.54
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,"[751.03, 767.97, 1103.05]","[641.64, 802.3, 750.07]",214.27,165.57,22.80
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,"[717.59, 1031.78, 758.58]","[802.3, 750.07, 754.31]",169.86,123.56,16.23
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,"[1081.73, 794.83, 942.02]","[750.07, 754.31, 925.67]",193.14,129.51,17.12
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,"[681.34, 809.57, 441.28]","[754.31, 925.67, 627.6]",133.56,125.13,17.30

Средние метрики Holt–Winter's по регионам (rolling-3):

                            Регион    RMSE     MAE  MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ 1670.51 1445.79   13.02
1              АКТЮБИНСКАЯ ОБЛАСТЬ   34.03   26.98  277.84
2              АЛМАТИНСКАЯ ОБЛАСТЬ 1183.86 1044.20    8.81
3               АТЫРАУСКАЯ ОБЛАСТЬ    0.47    0.39     NaN
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  569.14  522.48    8.55
5                          ГАЛМАТЫ    0.06    0.06   56.93
6                          ГАСТАНА    0.05    0.04     NaN
7                         ГШЫМКЕНТ    8.77    7.97  168.34
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ  584.18  511.77   25.54
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  265.84  214.58   20.69
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ   96.68   80.45    8.14
11            КОСТАНАЙСКАЯ ОБЛАСТЬ  275.32  247.00   18.29
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ    8.09    6.08  207.49
13           МАНГИСТАУСКАЯ ОБЛАСТЬ  356.10  307.53   49.15
14                    ОБЛАСТЬ АБАЙ  163.87  149.35    7.37
15                  ОБЛАСТЬ ЖЕТІСУ   83.77   65.18  121.22
16                  ОБЛАСТЬ ҰЛЫТАУ    2.09    1.75     NaN
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ  177.39  157.48   38.39
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  266.32  256.75   44.78
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ  210.68  172.47   24.55

In [6]:
# res_hw[res_hw['Регион'] == 'АКТЮБИНСКАЯ ОБЛАСТЬ']

## SARIMA

In [7]:
results_sarima = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    ts = ts + epsilon
    ts_log = np.log(ts)

    if len(ts_log) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. для авто-ARIMA, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train_log = ts_log[ts_log.index < test_start]
        test_log  = ts_log[(ts_log.index >= test_start) & (ts_log.index <= test_end)]
        if len(train_log) < 12 + horizon or len(test_log) < horizon:
            continue

        # автоподбор на лог-данных
        use_seasonal = len(train_log) >= 2 * 12

        sarima_log = auto_arima(
            train_log,
            seasonal=use_seasonal,
            m=12 if use_seasonal else 1,
            D=1 if use_seasonal else 0,      # фиксируем порядок сезонной разности
            seasonal_test=None,               # пропустить nsdiffs
            boxcox=True,
            stepwise=True,
            suppress_warnings=True,
            error_action="ignore"
        )
      
        # прогноз в лог-шкале
        fc_log = sarima_log.predict(n_periods=horizon, return_conf_int=False)

        # возвращаем прогноз в исходные единицы
        fc = np.exp(fc_log) - epsilon
        actual = np.exp(test_log.values) - epsilon  # но exp(log(x)) == x

        # метрики на исходном уровне
        rmse = np.sqrt(mean_squared_error(actual, fc))
        mae  = mean_absolute_error(actual, fc)
        mape = (np.abs((actual - fc) / actual).mean()) * 100

        results_sarima.append({
            "Регион":         region,
            "Test start":     test_start.strftime("%Y-%m"),
            "Test end":       test_end.strftime("%Y-%m"),
            "order":          sarima_log.order,
            "seasonal_order": sarima_log.seasonal_order,
            "RMSE":           round(rmse,2),
            "MAE":            round(mae,2),
            "MAPE_%":         round(mape,2),
            "Forecast":       [round(x,2) for x in fc],
            "Actual":         [round(y,2) for y in actual]
        })
# формируем DataFrame с результатами
res_sarima = pd.DataFrame(results_sarima)
res_sarima.to_excel("results/Птица - Результаты прогнозов SARIMA.xlsx", index=False)
print("Результаты прогнозов SARIMA на 3 месяца:")

display(res_sarima)

final_sarima = (
    res_sarima
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_sarima.to_excel("results/Птица - Результаты прогнозов SARIMA средние.xlsx", index=False)
print("Средние метрики SARIMA по регионам (rolling-3):")
display(final_sarima)

KeyboardInterrupt:

## Facebook Prophet

In [8]:
results_prophet = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    if len(ts) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. данных, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]
        if len(train) < 12 + horizon or len(test) < horizon:
            continue

        # Подготовка данных для Prophet
#         df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
# # подготовка для одного региона
        df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
        df_prophet["y"] = np.log(df_prophet["y"] + epsilon)

        m = Prophet()
        m.fit(df_prophet)

        future = m.make_future_dataframe(periods=horizon, freq="MS")
        forecast = m.predict(future)

        # берем только прогнозные точки
        yhat_log = forecast["yhat"].values[-horizon:]
        fc = np.exp(yhat_log) - epsilon

        # m = Prophet()
        # m.fit(df_prophet)

        # # Создаем DataFrame будущих дат и делаем прогноз
        # # future = m.make_future_dataframe(periods=horizon, freq="MS")
        # # forecast = m.predict(future)

        # # Отбираем только наши горизонты
        # fc = forecast.set_index("ds")["yhat"].loc[test.index].values
        actual = test.values

        # Расчет метрик
        rmse  = np.sqrt(mean_squared_error(actual, fc))
        mae   = mean_absolute_error(actual, fc)
        mape  = (np.abs((actual - fc) / actual).mean()) * 100

        results_prophet.append({
            "Регион":     region,
            "Test start": test_start.strftime("%Y-%m"),
            "Test end":   test_end.strftime("%Y-%m"),
            "RMSE":       round(rmse, 2),
            "MAE":        round(mae, 2),
            "MAPE_%":     round(mape, 2),
            "Forecast":   [round(x, 2) for x in fc],
            "Actual":     [round(x, 2) for x in actual]
        })

# Собираем результаты в DataFrame
res_prophet = pd.DataFrame(results_prophet)
res_prophet.to_excel("results/Птица - Результаты прогнозов Prophet.xlsx", index=False)
print("Результаты прогнозов Prophet на 3 месяца:")
display(res_prophet)

final_prophet = (
    res_prophet
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_prophet.to_excel("results/Птица - Результаты прогнозов Prophet средние.xlsx", index=False)
print("Средние метрики Prophet по регионам (rolling-3):")
display(final_prophet)

11:48:46 - cmdstanpy - INFO - Chain [1] start processing
11:48:47 - cmdstanpy - INFO - Chain [1] done processing
11:48:47 - cmdstanpy - INFO - Chain [1] start processing
11:48:47 - cmdstanpy - INFO - Chain [1] done processing
11:48:47 - cmdstanpy - INFO - Chain [1] start processing
11:48:47 - cmdstanpy - INFO - Chain [1] done processing
11:48:47 - cmdstanpy - INFO - Chain [1] start processing
11:48:47 - cmdstanpy - INFO - Chain [1] done processing
11:48:47 - cmdstanpy - INFO - Chain [1] start processing
11:48:48 - cmdstanpy - INFO - Chain [1] done processing
11:48:48 - cmdstanpy - INFO - Chain [1] start processing
11:48:48 - cmdstanpy - INFO - Chain [1] done processing
11:48:48 - cmdstanpy - INFO - Chain [1] start processing
11:48:48 - cmdstanpy - INFO - Chain [1] done processing
11:48:48 - cmdstanpy - INFO - Chain [1] start processing
11:48:48 - cmdstanpy - INFO - Chain [1] done processing
11:48:48 - cmdstanpy - INFO - Chain [1] start processing
11:48:48 - cmdstanpy - INFO - Chain [1] done processing
11:48:49 - cmdstanpy - INFO - Chain [1] start processing
11:48:49 - cmdstanpy - INFO - Chain [1] done processing
11:48:49 - cmdstanpy - INFO - Chain [1] start processing
11:48:49 - cmdstanpy - INFO - Chain [1] done processing
11:48:49 - cmdstanpy - INFO - Chain [1] start processing
11:48:49 - cmdstanpy - INFO - Chain [1] done processing
11:48:49 - cmdstanpy - INFO - Chain [1] start processing
11:48:49 - cmdstanpy - INFO - Chain [1] done processing
11:48:50 - cmdstanpy - INFO - Chain [1] start processing
11:48:50 - cmdstanpy - INFO - Chain [1] done processing
11:48:50 - cmdstanpy - INFO - Chain [1] start processing
11:48:50 - cmdstanpy - INFO - Chain [1] done processing
11:48:50 - cmdstanpy - INFO - Chain [1] start processing
11:48:50 - cmdstanpy - INFO - Chain [1] done processing
11:48:50 - cmdstanpy - INFO - Chain [1] start processing
11:48:50 - cmdstanpy - INFO - Chain [1] done processing
11:48:51 - cmdstanpy - INFO - Chain [1] start processing
11:48:51 - cmdstanpy - INFO - Chain [1] done processing
11:48:51 - cmdstanpy - INFO - Chain [1] start processing
11:48:51 - cmdstanpy - INFO - Chain [1] done processing
11:48:51 - cmdstanpy - INFO - Chain [1] start processing
11:48:51 - cmdstanpy - INFO - Chain [1] done processing
11:48:51 - cmdstanpy - INFO - Chain [1] start processing
11:48:51 - cmdstanpy - INFO - Chain [1] done processing
11:48:52 - cmdstanpy - INFO - Chain [1] start processing
11:48:52 - cmdstanpy - INFO - Chain [1] done processing
11:48:52 - cmdstanpy - INFO - Chain [1] start processing
11:48:52 - cmdstanpy - INFO - Chain [1] done processing
11:48:52 - cmdstanpy - INFO - Chain [1] start processing
11:48:52 - cmdstanpy - INFO - Chain [1] done processing
11:48:52 - cmdstanpy - INFO - Chain [1] start processing
11:48:52 - cmdstanpy - INFO - Chain [1] done processing
11:48:52 - cmdstanpy - INFO - Chain [1] start processing
11:48:53 - cmdstanpy - INFO - Chain [1] done processing
11:48:53 - cmdstanpy - INFO - Chain [1] start processing
11:48:53 - cmdstanpy - INFO - Chain [1] done processing
11:48:53 - cmdstanpy - INFO - Chain [1] start processing
11:48:53 - cmdstanpy - INFO - Chain [1] done processing
11:48:53 - cmdstanpy - INFO - Chain [1] start processing
11:48:53 - cmdstanpy - INFO - Chain [1] done processing
11:48:53 - cmdstanpy - INFO - Chain [1] start processing
11:48:53 - cmdstanpy - INFO - Chain [1] done processing
11:48:54 - cmdstanpy - INFO - Chain [1] start processing
11:48:54 - cmdstanpy - INFO - Chain [1] done processing
11:48:54 - cmdstanpy - INFO - Chain [1] start processing
11:48:54 - cmdstanpy - INFO - Chain [1] done processing
11:48:54 - cmdstanpy - INFO - Chain [1] start processing
11:48:54 - cmdstanpy - INFO - Chain [1] done processing
11:48:54 - cmdstanpy - INFO - Chain [1] start processing
11:48:54 - cmdstanpy - INFO - Chain [1] done processing
11:48:54 - cmdstanpy - INFO - Chain [1] start processing
11:48:55 - cmdstanpy - INFO - Chain [1] done processing
11:48:55 - cmdstanpy - INFO - Chain [1] start processing
11:48:55 - cmdstanpy - INFO - Chain [1] done processing
11:48:55 - cmdstanpy - INFO - Chain [1] start processing
11:48:55 - cmdstanpy - INFO - Chain [1] done processing
11:48:55 - cmdstanpy - INFO - Chain [1] start processing
11:48:55 - cmdstanpy - INFO - Chain [1] done processing
11:48:55 - cmdstanpy - INFO - Chain [1] start processing
11:48:55 - cmdstanpy - INFO - Chain [1] done processing
11:48:56 - cmdstanpy - INFO - Chain [1] start processing
11:48:56 - cmdstanpy - INFO - Chain [1] done processing
11:48:56 - cmdstanpy - INFO - Chain [1] start processing
11:48:56 - cmdstanpy - INFO - Chain [1] done processing
11:48:56 - cmdstanpy - INFO - Chain [1] start processing
11:48:56 - cmdstanpy - INFO - Chain [1] done processing
11:48:56 - cmdstanpy - INFO - Chain [1] start processing
11:48:56 - cmdstanpy - INFO - Chain [1] done processing
11:48:57 - cmdstanpy - INFO - Chain [1] start processing
11:48:57 - cmdstanpy - INFO - Chain [1] done processing
11:48:57 - cmdstanpy - INFO - Chain [1] start processing
11:48:57 - cmdstanpy - INFO - Chain [1] done processing
11:48:57 - cmdstanpy - INFO - Chain [1] start processing
11:48:57 - cmdstanpy - INFO - Chain [1] done processing
11:48:57 - cmdstanpy - INFO - Chain [1] start processing
11:48:57 - cmdstanpy - INFO - Chain [1] done processing
11:48:57 - cmdstanpy - INFO - Chain [1] start processing
11:48:58 - cmdstanpy - INFO - Chain [1] done processing
11:48:58 - cmdstanpy - INFO - Chain [1] start processing
11:48:58 - cmdstanpy - INFO - Chain [1] done processing
11:48:58 - cmdstanpy - INFO - Chain [1] start processing
11:48:58 - cmdstanpy - INFO - Chain [1] done processing
11:48:58 - cmdstanpy - INFO - Chain [1] start processing
11:48:58 - cmdstanpy - INFO - Chain [1] done processing
11:48:58 - cmdstanpy - INFO - Chain [1] start processing
11:48:58 - cmdstanpy - INFO - Chain [1] done processing
11:48:59 - cmdstanpy - INFO - Chain [1] start processing
11:48:59 - cmdstanpy - INFO - Chain [1] done processing
11:48:59 - cmdstanpy - INFO - Chain [1] start processing
11:48:59 - cmdstanpy - INFO - Chain [1] done processing
11:48:59 - cmdstanpy - INFO - Chain [1] start processing
11:48:59 - cmdstanpy - INFO - Chain [1] done processing
11:48:59 - cmdstanpy - INFO - Chain [1] start processing
11:48:59 - cmdstanpy - INFO - Chain [1] done processing
11:48:59 - cmdstanpy - INFO - Chain [1] start processing
11:49:00 - cmdstanpy - INFO - Chain [1] done processing
11:49:00 - cmdstanpy - INFO - Chain [1] start processing
11:49:00 - cmdstanpy - INFO - Chain [1] done processing
11:49:00 - cmdstanpy - INFO - Chain [1] start processing
11:49:00 - cmdstanpy - INFO - Chain [1] done processing
11:49:00 - cmdstanpy - INFO - Chain [1] start processing
11:49:00 - cmdstanpy - INFO - Chain [1] done processing
11:49:00 - cmdstanpy - INFO - Chain [1] start processing
11:49:00 - cmdstanpy - INFO - Chain [1] done processing
11:49:01 - cmdstanpy - INFO - Chain [1] start processing
11:49:01 - cmdstanpy - INFO - Chain [1] done processing
11:49:01 - cmdstanpy - INFO - Chain [1] start processing
11:49:01 - cmdstanpy - INFO - Chain [1] done processing
11:49:01 - cmdstanpy - INFO - Chain [1] start processing
11:49:01 - cmdstanpy - INFO - Chain [1] done processing
11:49:01 - cmdstanpy - INFO - Chain [1] start processing
11:49:01 - cmdstanpy - INFO - Chain [1] done processing
11:49:01 - cmdstanpy - INFO - Chain [1] start processing
11:49:02 - cmdstanpy - INFO - Chain [1] done processing
11:49:02 - cmdstanpy - INFO - Chain [1] start processing
11:49:02 - cmdstanpy - INFO - Chain [1] done processing
11:49:02 - cmdstanpy - INFO - Chain [1] start processing
11:49:02 - cmdstanpy - INFO - Chain [1] done processing
11:49:02 - cmdstanpy - INFO - Chain [1] start processing
11:49:02 - cmdstanpy - INFO - Chain [1] done processing
11:49:02 - cmdstanpy - INFO - Chain [1] start processing
11:49:02 - cmdstanpy - INFO - Chain [1] done processing
11:49:03 - cmdstanpy - INFO - Chain [1] start processing
11:49:03 - cmdstanpy - INFO - Chain [1] done processing
11:49:03 - cmdstanpy - INFO - Chain [1] start processing
11:49:03 - cmdstanpy - INFO - Chain [1] done processing
11:49:04 - cmdstanpy - INFO - Chain [1] start processing
11:49:04 - cmdstanpy - INFO - Chain [1] done processing
11:49:04 - cmdstanpy - INFO - Chain [1] start processing
11:49:04 - cmdstanpy - INFO - Chain [1] done processing
11:49:05 - cmdstanpy - INFO - Chain [1] start processing
11:49:05 - cmdstanpy - INFO - Chain [1] done processing
11:49:05 - cmdstanpy - INFO - Chain [1] start processing
11:49:05 - cmdstanpy - INFO - Chain [1] done processing
11:49:05 - cmdstanpy - INFO - Chain [1] start processing
11:49:06 - cmdstanpy - INFO - Chain [1] done processing
11:49:06 - cmdstanpy - INFO - Chain [1] start processing
11:49:06 - cmdstanpy - INFO - Chain [1] done processing
11:49:06 - cmdstanpy - INFO - Chain [1] start processing
11:49:07 - cmdstanpy - INFO - Chain [1] done processing
11:49:07 - cmdstanpy - INFO - Chain [1] start processing
11:49:07 - cmdstanpy - INFO - Chain [1] done processing
11:49:08 - cmdstanpy - INFO - Chain [1] start processing
11:49:08 - cmdstanpy - INFO - Chain [1] done processing
11:49:08 - cmdstanpy - INFO - Chain [1] start processing
11:49:08 - cmdstanpy - INFO - Chain [1] done processing
11:49:08 - cmdstanpy - INFO - Chain [1] start processing
11:49:08 - cmdstanpy - INFO - Chain [1] done processing
11:49:08 - cmdstanpy - INFO - Chain [1] start processing
11:49:08 - cmdstanpy - INFO - Chain [1] done processing
11:49:09 - cmdstanpy - INFO - Chain [1] start processing
11:49:09 - cmdstanpy - INFO - Chain [1] done processing
11:49:09 - cmdstanpy - INFO - Chain [1] start processing
11:49:09 - cmdstanpy - INFO - Chain [1] done processing
11:49:09 - cmdstanpy - INFO - Chain [1] start processing
11:49:09 - cmdstanpy - INFO - Chain [1] done processing
11:49:09 - cmdstanpy - INFO - Chain [1] start processing
11:49:09 - cmdstanpy - INFO - Chain [1] done processing
11:49:09 - cmdstanpy - INFO - Chain [1] start processing
11:49:10 - cmdstanpy - INFO - Chain [1] done processing
11:49:10 - cmdstanpy - INFO - Chain [1] start processing
11:49:10 - cmdstanpy - INFO - Chain [1] done processing
11:49:10 - cmdstanpy - INFO - Chain [1] start processing
11:49:10 - cmdstanpy - INFO - Chain [1] done processing
11:49:10 - cmdstanpy - INFO - Chain [1] start processing
11:49:10 - cmdstanpy - INFO - Chain [1] done processing
11:49:10 - cmdstanpy - INFO - Chain [1] start processing
11:49:11 - cmdstanpy - INFO - Chain [1] done processing
11:49:11 - cmdstanpy - INFO - Chain [1] start processing
11:49:11 - cmdstanpy - INFO - Chain [1] done processing
11:49:11 - cmdstanpy - INFO - Chain [1] start processing
11:49:11 - cmdstanpy - INFO - Chain [1] done processing
11:49:11 - cmdstanpy - INFO - Chain [1] start processing
11:49:11 - cmdstanpy - INFO - Chain [1] done processing
11:49:11 - cmdstanpy - INFO - Chain [1] start processing
11:49:11 - cmdstanpy - INFO - Chain [1] done processing
11:49:12 - cmdstanpy - INFO - Chain [1] start processing
11:49:12 - cmdstanpy - INFO - Chain [1] done processing
11:49:12 - cmdstanpy - INFO - Chain [1] start processing
11:49:12 - cmdstanpy - INFO - Chain [1] done processing
11:49:12 - cmdstanpy - INFO - Chain [1] start processing
11:49:12 - cmdstanpy - INFO - Chain [1] done processing
11:49:12 - cmdstanpy - INFO - Chain [1] start processing
11:49:12 - cmdstanpy - INFO - Chain [1] done processing
11:49:13 - cmdstanpy - INFO - Chain [1] start processing
11:49:13 - cmdstanpy - INFO - Chain [1] done processing
11:49:13 - cmdstanpy - INFO - Chain [1] start processing
11:49:13 - cmdstanpy - INFO - Chain [1] done processing
11:49:13 - cmdstanpy - INFO - Chain [1] start processing
11:49:13 - cmdstanpy - INFO - Chain [1] done processing
11:49:13 - cmdstanpy - INFO - Chain [1] start processing
11:49:13 - cmdstanpy - INFO - Chain [1] done processing
11:49:13 - cmdstanpy - INFO - Chain [1] start processing
11:49:14 - cmdstanpy - INFO - Chain [1] done processing
11:49:14 - cmdstanpy - INFO - Chain [1] start processing
11:49:14 - cmdstanpy - INFO - Chain [1] done processing
11:49:14 - cmdstanpy - INFO - Chain [1] start processing
11:49:14 - cmdstanpy - INFO - Chain [1] done processing
11:49:14 - cmdstanpy - INFO - Chain [1] start processing
11:49:14 - cmdstanpy - INFO - Chain [1] done processing
11:49:14 - cmdstanpy - INFO - Chain [1] start processing
11:49:14 - cmdstanpy - INFO - Chain [1] done processing
11:49:15 - cmdstanpy - INFO - Chain [1] start processing
11:49:15 - cmdstanpy - INFO - Chain [1] done processing
11:49:15 - cmdstanpy - INFO - Chain [1] start processing
11:49:15 - cmdstanpy - INFO - Chain [1] done processing
11:49:15 - cmdstanpy - INFO - Chain [1] start processing
11:49:15 - cmdstanpy - INFO - Chain [1] done processing
11:49:15 - cmdstanpy - INFO - Chain [1] start processing
11:49:15 - cmdstanpy - INFO - Chain [1] done processing
11:49:16 - cmdstanpy - INFO - Chain [1] start processing
11:49:16 - cmdstanpy - INFO - Chain [1] done processing
11:49:16 - cmdstanpy - INFO - Chain [1] start processing
11:49:16 - cmdstanpy - INFO - Chain [1] done processing
11:49:16 - cmdstanpy - INFO - Chain [1] start processing
11:49:16 - cmdstanpy - INFO - Chain [1] done processing
11:49:16 - cmdstanpy - INFO - Chain [1] start processing
11:49:16 - cmdstanpy - INFO - Chain [1] done processing
11:49:17 - cmdstanpy - INFO - Chain [1] start processing
11:49:17 - cmdstanpy - INFO - Chain [1] done processing
11:49:17 - cmdstanpy - INFO - Chain [1] start processing
11:49:17 - cmdstanpy - INFO - Chain [1] done processing
11:49:17 - cmdstanpy - INFO - Chain [1] start processing
11:49:17 - cmdstanpy - INFO - Chain [1] done processing
11:49:17 - cmdstanpy - INFO - Chain [1] start processing
11:49:17 - cmdstanpy - INFO - Chain [1] done processing
11:49:18 - cmdstanpy - INFO - Chain [1] start processing
11:49:18 - cmdstanpy - INFO - Chain [1] done processing
11:49:18 - cmdstanpy - INFO - Chain [1] start processing
11:49:18 - cmdstanpy - INFO - Chain [1] done processing
11:49:18 - cmdstanpy - INFO - Chain [1] start processing
11:49:18 - cmdstanpy - INFO - Chain [1] done processing
11:49:18 - cmdstanpy - INFO - Chain [1] start processing
11:49:18 - cmdstanpy - INFO - Chain [1] done processing
11:49:18 - cmdstanpy - INFO - Chain [1] start processing
11:49:19 - cmdstanpy - INFO - Chain [1] done processing
11:49:19 - cmdstanpy - INFO - Chain [1] start processing
11:49:19 - cmdstanpy - INFO - Chain [1] done processing
11:49:19 - cmdstanpy - INFO - Chain [1] start processing
11:49:19 - cmdstanpy - INFO - Chain [1] done processing
11:49:19 - cmdstanpy - INFO - Chain [1] start processing
11:49:19 - cmdstanpy - INFO - Chain [1] done processing
11:49:19 - cmdstanpy - INFO - Chain [1] start processing
11:49:19 - cmdstanpy - INFO - Chain [1] done processing
11:49:20 - cmdstanpy - INFO - Chain [1] start processing
11:49:20 - cmdstanpy - INFO - Chain [1] done processing
11:49:20 - cmdstanpy - INFO - Chain [1] start processing
11:49:20 - cmdstanpy - INFO - Chain [1] done processing
11:49:20 - cmdstanpy - INFO - Chain [1] start processing
11:49:20 - cmdstanpy - INFO - Chain [1] done processing
11:49:20 - cmdstanpy - INFO - Chain [1] start processing
11:49:20 - cmdstanpy - INFO - Chain [1] done processing
11:49:21 - cmdstanpy - INFO - Chain [1] start processing
11:49:21 - cmdstanpy - INFO - Chain [1] done processing
11:49:21 - cmdstanpy - INFO - Chain [1] start processing
11:49:21 - cmdstanpy - INFO - Chain [1] done processing
11:49:21 - cmdstanpy - INFO - Chain [1] start processing
11:49:21 - cmdstanpy - INFO - Chain [1] done processing
11:49:21 - cmdstanpy - INFO - Chain [1] start processing
11:49:21 - cmdstanpy - INFO - Chain [1] done processing
11:49:22 - cmdstanpy - INFO - Chain [1] start processing
11:49:22 - cmdstanpy - INFO - Chain [1] done processing
11:49:22 - cmdstanpy - INFO - Chain [1] start processing
11:49:22 - cmdstanpy - INFO - Chain [1] done processing
11:49:22 - cmdstanpy - INFO - Chain [1] start processing
11:49:22 - cmdstanpy - INFO - Chain [1] done processing
11:49:22 - cmdstanpy - INFO - Chain [1] start processing
11:49:22 - cmdstanpy - INFO - Chain [1] done processing
11:49:23 - cmdstanpy - INFO - Chain [1] start processing
11:49:23 - cmdstanpy - INFO - Chain [1] done processing
11:49:23 - cmdstanpy - INFO - Chain [1] start processing
11:49:23 - cmdstanpy - INFO - Chain [1] done processing
11:49:23 - cmdstanpy - INFO - Chain [1] start processing
11:49:23 - cmdstanpy - INFO - Chain [1] done processing
11:49:23 - cmdstanpy - INFO - Chain [1] start processing
11:49:36 - cmdstanpy - INFO - Chain [1] done processing
11:49:36 - cmdstanpy - INFO - Chain [1] start processing
11:49:47 - cmdstanpy - INFO - Chain [1] done processing
11:49:47 - cmdstanpy - INFO - Chain [1] start processing
11:49:59 - cmdstanpy - INFO - Chain [1] done processing
11:49:59 - cmdstanpy - INFO - Chain [1] start processing
11:49:59 - cmdstanpy - INFO - Chain [1] done processing
11:50:00 - cmdstanpy - INFO - Chain [1] start processing
11:50:00 - cmdstanpy - INFO - Chain [1] done processing
11:50:00 - cmdstanpy - INFO - Chain [1] start processing
11:50:00 - cmdstanpy - INFO - Chain [1] done processing
11:50:00 - cmdstanpy - INFO - Chain [1] start processing
11:50:00 - cmdstanpy - INFO - Chain [1] done processing
11:50:00 - cmdstanpy - INFO - Chain [1] start processing
11:50:00 - cmdstanpy - INFO - Chain [1] done processing
11:50:01 - cmdstanpy - INFO - Chain [1] start processing
11:50:01 - cmdstanpy - INFO - Chain [1] done processing
11:50:01 - cmdstanpy - INFO - Chain [1] start processing
11:50:01 - cmdstanpy - INFO - Chain [1] done processing
11:50:01 - cmdstanpy - INFO - Chain [1] start processing
11:50:01 - cmdstanpy - INFO - Chain [1] done processing
11:50:01 - cmdstanpy - INFO - Chain [1] start processing
11:50:01 - cmdstanpy - INFO - Chain [1] done processing
11:50:02 - cmdstanpy - INFO - Chain [1] start processing
11:50:02 - cmdstanpy - INFO - Chain [1] done processing
11:50:02 - cmdstanpy - INFO - Chain [1] start processing
11:50:02 - cmdstanpy - INFO - Chain [1] done processing
11:50:02 - cmdstanpy - INFO - Chain [1] start processing
11:50:02 - cmdstanpy - INFO - Chain [1] done processing
11:50:02 - cmdstanpy - INFO - Chain [1] start processing
11:50:03 - cmdstanpy - INFO - Chain [1] done processing
11:50:03 - cmdstanpy - INFO - Chain [1] start processing
11:50:03 - cmdstanpy - INFO - Chain [1] done processing
11:50:03 - cmdstanpy - INFO - Chain [1] start processing
11:50:03 - cmdstanpy - INFO - Chain [1] done processing
11:50:03 - cmdstanpy - INFO - Chain [1] start processing
11:50:03 - cmdstanpy - INFO - Chain [1] done processing
11:50:03 - cmdstanpy - INFO - Chain [1] start processing
11:50:03 - cmdstanpy - INFO - Chain [1] done processing
11:50:04 - cmdstanpy - INFO - Chain [1] start processing
11:50:04 - cmdstanpy - INFO - Chain [1] done processing
11:50:04 - cmdstanpy - INFO - Chain [1] start processing
11:50:04 - cmdstanpy - INFO - Chain [1] done processing
11:50:04 - cmdstanpy - INFO - Chain [1] start processing
11:50:04 - cmdstanpy - INFO - Chain [1] done processing
11:50:05 - cmdstanpy - INFO - Chain [1] start processing
11:50:05 - cmdstanpy - INFO - Chain [1] done processing
11:50:05 - cmdstanpy - INFO - Chain [1] start processing
11:50:05 - cmdstanpy - INFO - Chain [1] done processing
11:50:05 - cmdstanpy - INFO - Chain [1] start processing
11:50:05 - cmdstanpy - INFO - Chain [1] done processing
11:50:05 - cmdstanpy - INFO - Chain [1] start processing
11:50:05 - cmdstanpy - INFO - Chain [1] done processing
11:50:06 - cmdstanpy - INFO - Chain [1] start processing
11:50:06 - cmdstanpy - INFO - Chain [1] done processing
11:50:06 - cmdstanpy - INFO - Chain [1] start processing
11:50:06 - cmdstanpy - INFO - Chain [1] done processing
11:50:06 - cmdstanpy - INFO - Chain [1] start processing
11:50:06 - cmdstanpy - INFO - Chain [1] done processing
11:50:06 - cmdstanpy - INFO - Chain [1] start processing

Результаты прогнозов Prophet на 3 месяца:

,Регион,Test start,Test end,RMSE,MAE,MAPE_%,Forecast,Actual
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-01,2024-03,1416.91,1133.93,11.74,"[11017.33, 9581.39, 12312.82]","[8963.23, 9586.12, 10969.85]"
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-02,2024-04,1081.75,913.22,8.45,"[9387.06, 11891.14, 9275.67]","[9586.12, 10969.85, 10894.97]"
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-03,2024-05,1087.12,979.64,9.04,"[12026.85, 9380.67, 10606.59]","[10969.85, 10894.97, 10238.97]"
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-04,2024-06,1372.88,1209.78,10.40,"[9324.72, 10537.5, 10931.91]","[10894.97, 10238.97, 12692.46]"
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-05,2024-07,964.16,684.26,5.66,"[10650.87, 11074.23, 10356.51]","[10238.97, 12692.46, 10379.17]"
...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-06,2024-08,368.01,327.71,52.00,"[413.44, 229.12, 338.27]","[305.92, 742.4, 700.6]"
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-07,2024-09,416.74,410.63,56.99,"[231.26, 339.86, 351.11]","[742.4, 700.6, 711.12]"
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-08,2024-10,345.30,343.66,48.98,"[329.85, 347.11, 395.52]","[700.6, 711.12, 691.74]"
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-09,2024-11,312.74,307.24,44.67,"[400.05, 457.87, 290.52]","[711.12, 691.74, 667.3]"
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-10,2024-12,244.03,195.08,28.90,"[475.27, 304.32, 559.56]","[691.74, 667.3, 565.34]"

Средние метрики Prophet по регионам (rolling-3):

                            Регион      RMSE      MAE   MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ   1296.38  1087.96    10.53
1              АКТЮБИНСКАЯ ОБЛАСТЬ     39.21    33.55   208.73
2              АЛМАТИНСКАЯ ОБЛАСТЬ   1693.22  1545.61    13.17
3               АТЫРАУСКАЯ ОБЛАСТЬ      3.44     2.00      NaN
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ    564.69   519.04     8.53
5                          ГАЛМАТЫ      0.10     0.10    99.99
6                          ГАСТАНА      0.02     0.01      NaN
7                         ГШЫМКЕНТ     78.38    62.99  1075.22
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ    451.89   391.54    23.15
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ    335.36   270.03    27.94
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ    155.33   122.69    11.82
11            КОСТАНАЙСКАЯ ОБЛАСТЬ    365.51   306.67    36.41
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ      8.87     7.42   170.89
13           МАНГИСТАУСКАЯ ОБЛАСТЬ 130951.84 81476.91 18483.84
14                    ОБЛАСТЬ АБАЙ    296.85   254.85    13.46
15                  ОБЛАСТЬ ЖЕТІСУ    296.37   206.80   288.27
16                  ОБЛАСТЬ ҰЛЫТАУ   7889.28  4573.55      NaN
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ    206.15   197.52    91.49
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ    153.28   131.16    93.50
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ    332.24   280.98    40.34

In [9]:
# Переименуем колонки с MAPE, чтобы было понятно, к какому методу относятся
hw = final_hw.rename(columns={"MAPE_%": "MAPE_HW"})
sar = final_sarima.rename(columns={"MAPE_%": "MAPE_SARIMA"})
pr  = final_prophet.rename(columns={"MAPE_%": "MAPE_Prophet"})

# Мёрджим по региону
summary = (
    hw[["Регион", "MAPE_HW"]]
    .merge(sar[["Регион", "MAPE_SARIMA"]], on="Регион")
    .merge(pr[["Регион", "MAPE_Prophet"]], on="Регион")
)

# Определяем для каждой строки, какой столбец MAPE минимален
# idxmin вернёт название столбца с минимальным значением
summary["Best_method"] = summary[["MAPE_HW","MAPE_SARIMA","MAPE_Prophet"]] \
                           .idxmin(axis=1) \
                           .str.replace("MAPE_","")  # убираем префикс для красоты

# Если нужно, можно сразу отсортировать
# summary = summary.sort_values("Best_method")

# допустим, у вас уже есть summary
summary = summary.round({
    "MAPE_HW": 2,
    "MAPE_SARIMA": 2,
    "MAPE_Prophet": 2
})

# Готово!
print(summary.to_string(index=False))
summary.to_excel("results/Птица - Лучшие модели.xlsx", index=False)

                        Регион  MAPE_HW                 MAPE_SARIMA  MAPE_Prophet Best_method
           АКМОЛИНСКАЯ ОБЛАСТЬ     9.37                        9.27         10.53      SARIMA
           АКТЮБИНСКАЯ ОБЛАСТЬ   384.26                      356.69        208.73     Prophet
           АЛМАТИНСКАЯ ОБЛАСТЬ     6.56                        9.93         13.17          HW
            АТЫРАУСКАЯ ОБЛАСТЬ      NaN   3505499728190416879616.00           NaN      SARIMA
ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ     8.36                        8.74          8.53          HW
                       ГАЛМАТЫ    54.28                      168.59         99.99          HW
                       ГАСТАНА      NaN     32418544302525849600.00           NaN      SARIMA
                      ГШЫМКЕНТ   423.80                      780.23       1075.22          HW
            ЖАМБЫЛСКАЯ ОБЛАСТЬ    17.50                       19.32         23.15          HW
 ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ    16.21                       13.88         27.94      SARIMA
        КАРАГАНДИНСКАЯ ОБЛАСТЬ    10.48                       14.62         11.82          HW
          КОСТАНАЙСКАЯ ОБЛАСТЬ    27.36                       29.56         36.41          HW
        КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ    98.46                       74.51        170.89      SARIMA
         МАНГИСТАУСКАЯ ОБЛАСТЬ    42.42                      370.55      18483.84          HW
                  ОБЛАСТЬ АБАЙ     5.13                        7.11         13.46          HW
                ОБЛАСТЬ ЖЕТІСУ   181.16                      175.35        288.27      SARIMA
                ОБЛАСТЬ ҰЛЫТАУ      NaN 163874991768398611873792.00           NaN      SARIMA
          ПАВЛОДАРСКАЯ ОБЛАСТЬ    45.92                       52.35         91.49          HW
  СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ    96.07                       89.63         93.50      SARIMA
         ТУРКЕСТАНСКАЯ ОБЛАСТЬ    74.15                       74.95         40.34     Prophet