In [1]:
# --- 1. Импорты и общие настройки ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from pmdarima import auto_arima
from statsmodels.tsa.statespace.sarimax import SARIMAX
from prophet import Prophet  # pip install prophet
from sklearn.metrics import mean_squared_error, mean_absolute_error
import warnings
pd.options.display.float_format = '{:.2f}'.format
warnings.filterwarnings("ignore")
# plt.style.use("seaborn-whitegrid")

In [2]:
# --- 2. Загрузка данных ---
# df должен содержать столбцы: "Регион", "Период" (YYYY-MM), и целевой столбец с показателем.
df = pd.read_excel("Датасет по овцы и козы.xlsx")
df["Период"] = pd.to_datetime(df["Период"], format="%Y-%m")
df.sample(10)

                              Регион     Период  Овцы и козы
637                          ГАЛМАТЫ 2018-02-01         1.52
859                         ГШЫМКЕНТ 2020-01-01        97.93
948               ЖАМБЫЛСКАЯ ОБЛАСТЬ 2017-06-01      4804.07
50               АКМОЛИНСКАЯ ОБЛАСТЬ 2019-03-01       633.22
1676                  ОБЛАСТЬ ЖЕТІСУ 2022-12-01      7374.32
390               АТЫРАУСКАЯ ОБЛАСТЬ 2017-07-01       809.92
300              АЛМАТИНСКАЯ ОБЛАСТЬ 2020-01-01      2029.42
584   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 2023-09-01      1728.84
1429          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ 2017-07-01       696.40
577   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 2023-02-01       703.67

In [3]:
regions = df['Регион'].unique()
target   = "Овцы и козы"
horizon  = 3
epsilon = 1e-6

In [4]:
first_test = pd.to_datetime("2024-01-01")
last_possible = df["Период"].max() - pd.DateOffset(months=horizon-1)
test_starts = pd.date_range(first_test, last_possible, freq="MS")

## Holw-Winter's (log)

In [5]:
results_hw = []
for region in regions:
    ts = (df[df["Регион"] == region]
          .set_index("Период")[target]
          .dropna()
          .sort_index())
    if len(ts) < 24:
        print(f"{region}: всего {len(ts)} мес. — сезонный Holt-Winter's невозможен.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        # формируем train / test
        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]

        # пропускаем, если недостаточно данных или неполный test
        if len(train) < 24 or len(test) < horizon:
            continue

        # обучаем модель
        train_log = np.log1p(train)

        hw_log = ExponentialSmoothing(
            train_log,
            seasonal="add",
            seasonal_periods=12
        ).fit(optimized=True)

        # прогноз и метрики
        fc_log = hw_log.forecast(horizon)
        fc = np.expm1(fc_log) 
        # fc   = model.forecast(horizon)
        rmse = np.sqrt(mean_squared_error(test, fc))
        mae  = mean_absolute_error(test, fc)
        mape = (np.abs((test - fc) / test).mean()) * 100

        results_hw.append({
            "Регион":      region,
            "Test start":  test_start.strftime("%Y-%m"),
            "Test end":    test_end.strftime("%Y-%m"),
            "Forecast":    [x.round(2) for x in list(fc.values)],
            "Actual":      [y.round(2) for y in list(test.values)],
            "RMSE":        rmse,
            "MAE":         mae,
            "MAPE_%":      mape
        })

# 4) Усреднение по всем скользящим окнам для каждого региона
res_hw = pd.DataFrame(results_hw)
res_hw.to_excel("results/Овцы и козы - Результаты прогнозов ХВ.xlsx", index=False)
print("Результаты прогнозов HW на 3 месяца:")

display(res_hw)

final_hw = (
    res_hw
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_hw.to_excel("results/Овцы и козы - Результаты прогнозов ХВ средние.xlsx", index=False)
print("Средние метрики Holt–Winter's по регионам (rolling-3):")
display(final_hw)

Результаты прогнозов HW на 3 месяца:

,Регион,Test start,Test end,Forecast,Actual,RMSE,MAE,MAPE_%
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-01,2024-03,"[539.98, 556.64, 585.43]","[544.33, 634.45, 733.22]",96.46,76.65,11.07
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-02,2024-04,"[557.52, 586.08, 653.24]","[634.45, 733.22, 686.11]",97.72,85.65,12.33
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-03,2024-05,"[596.32, 658.54, 769.98]","[733.22, 686.11, 756.58]",81.00,59.29,8.15
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-04,2024-06,"[666.09, 782.4, 777.1]","[686.11, 756.58, 825.36]",33.64,31.36,4.06
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-05,2024-07,"[784.38, 779.21, 505.68]","[756.58, 825.36, 499.73]",31.30,26.63,3.49
...,...,...,...,...,...,...,...,...
180,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-06,2024-08,"[4123.05, 3623.37, 3899.19]","[4988.31, 2350.88, 3378.76]",937.86,886.06,28.96
181,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-07,2024-09,"[3973.77, 4269.8, 5128.5]","[2350.88, 3378.76, 4625.15]",1107.71,1005.76,35.43
182,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-08,2024-10,"[3811.44, 4730.34, 4991.98]","[3378.76, 4625.15, 4443.92]",407.70,361.98,9.14
183,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-09,2024-11,"[4558.31, 4812.73, 4869.31]","[4625.15, 4443.92, 5402.06]",376.08,322.80,6.54
184,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-10,2024-12,"[4834.6, 4892.55, 6620.68]","[4443.92, 5402.06, 8866.36]",1348.50,1048.63,14.52

Средние метрики Holt–Winter's по регионам (rolling-3):

                            Регион   RMSE    MAE  MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ  57.42  49.23    7.00
1              АКТЮБИНСКАЯ ОБЛАСТЬ 112.58  94.29    5.63
2              АЛМАТИНСКАЯ ОБЛАСТЬ 411.20 338.01   14.43
3               АТЫРАУСКАЯ ОБЛАСТЬ  66.36  55.91    6.38
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 136.14 115.87    9.09
5                          ГАЛМАТЫ   0.41   0.37     NaN
6                          ГАСТАНА   0.20   0.17   16.22
7                         ГШЫМКЕНТ  35.15  25.06   24.58
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ 177.04 166.39    6.20
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  26.80  23.68    2.01
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ  65.55  58.28    7.37
11            КОСТАНАЙСКАЯ ОБЛАСТЬ  51.54  43.29   20.26
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ  92.76  80.69   16.80
13           МАНГИСТАУСКАЯ ОБЛАСТЬ  17.48  16.00    9.15
14                    ОБЛАСТЬ АБАЙ  94.44  70.70    2.70
15                  ОБЛАСТЬ ЖЕТІСУ  75.95  61.31    1.97
16                  ОБЛАСТЬ ҰЛЫТАУ  73.42  62.11   12.20
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ  34.42  28.86    3.48
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  33.23  29.05    8.42
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ 752.37 679.64   17.16

## SARIMA

In [6]:
results_sarima = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    ts = ts + epsilon
    ts_log = np.log(ts)

    if len(ts_log) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. для авто-ARIMA, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train_log = ts_log[ts_log.index < test_start]
        test_log  = ts_log[(ts_log.index >= test_start) & (ts_log.index <= test_end)]
        if len(train_log) < 12 + horizon or len(test_log) < horizon:
            continue

        # автоподбор на лог-данных
        use_seasonal = len(train_log) >= 2 * 12

        sarima_log = auto_arima(
            train_log,
            seasonal=use_seasonal,
            m=12 if use_seasonal else 1,
            D=1 if use_seasonal else 0,      # фиксируем порядок сезонной разности
            seasonal_test=None,               # пропустить nsdiffs
            boxcox=True,
            stepwise=True,
            suppress_warnings=True,
            error_action="ignore"
        )
      
        # прогноз в лог-шкале
        fc_log = sarima_log.predict(n_periods=horizon, return_conf_int=False)

        # возвращаем прогноз в исходные единицы
        fc = np.exp(fc_log) - epsilon
        actual = np.exp(test_log.values) - epsilon  # но exp(log(x)) == x

        # метрики на исходном уровне
        rmse = np.sqrt(mean_squared_error(actual, fc))
        mae  = mean_absolute_error(actual, fc)
        mape = (np.abs((actual - fc) / actual).mean()) * 100

        results_sarima.append({
            "Регион":         region,
            "Test start":     test_start.strftime("%Y-%m"),
            "Test end":       test_end.strftime("%Y-%m"),
            "order":          sarima_log.order,
            "seasonal_order": sarima_log.seasonal_order,
            "RMSE":           round(rmse,2),
            "MAE":            round(mae,2),
            "MAPE_%":         round(mape,2),
            "Forecast":       [round(x,2) for x in fc],
            "Actual":         [round(y,2) for y in actual]
        })
# формируем DataFrame с результатами
res_sarima = pd.DataFrame(results_sarima)
res_sarima.to_excel("results/Овцы и козы - Результаты прогнозов SARIMA.xlsx", index=False)
print("Результаты прогнозов SARIMA на 3 месяца:")

display(res_sarima)

final_sarima = (
    res_sarima
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_sarima.to_excel("results/Овцы и козы - Результаты прогнозов SARIMA средние.xlsx", index=False)
print("Средние метрики SARIMA по регионам (rolling-3):")
display(final_sarima)

KeyboardInterrupt:

## Facebook Prophet

In [ ]:
results_prophet = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    if len(ts) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. данных, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]
        if len(train) < 12 + horizon or len(test) < horizon:
            continue

        # Подготовка данных для Prophet
#         df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
# # подготовка для одного региона
        df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
        df_prophet["y"] = np.log(df_prophet["y"] + epsilon)

        m = Prophet()
        m.fit(df_prophet)

        future = m.make_future_dataframe(periods=horizon, freq="MS")
        forecast = m.predict(future)

        # берем только прогнозные точки
        yhat_log = forecast["yhat"].values[-horizon:]
        fc = np.exp(yhat_log) - epsilon

        # m = Prophet()
        # m.fit(df_prophet)

        # # Создаем DataFrame будущих дат и делаем прогноз
        # # future = m.make_future_dataframe(periods=horizon, freq="MS")
        # # forecast = m.predict(future)

        # # Отбираем только наши горизонты
        # fc = forecast.set_index("ds")["yhat"].loc[test.index].values
        actual = test.values

        # Расчет метрик
        rmse  = np.sqrt(mean_squared_error(actual, fc))
        mae   = mean_absolute_error(actual, fc)
        mape  = (np.abs((actual - fc) / actual).mean()) * 100

        results_prophet.append({
            "Регион":     region,
            "Test start": test_start.strftime("%Y-%m"),
            "Test end":   test_end.strftime("%Y-%m"),
            "RMSE":       round(rmse, 2),
            "MAE":        round(mae, 2),
            "MAPE_%":     round(mape, 2),
            "Forecast":   [round(x, 2) for x in fc],
            "Actual":     [round(x, 2) for x in actual]
        })

# Собираем результаты в DataFrame
res_prophet = pd.DataFrame(results_prophet)
res_prophet.to_excel("results/Овцы и козы - Результаты прогнозов Prophet.xlsx", index=False)
print("Результаты прогнозов Prophet на 3 месяца:")
display(res_prophet)

final_prophet = (
    res_prophet
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_prophet.to_excel("results/Овцы и козы - Результаты прогнозов Prophet средние.xlsx", index=False)
print("Средние метрики Prophet по регионам (rolling-3):")
display(final_prophet)

In [ ]:
# Переименуем колонки с MAPE, чтобы было понятно, к какому методу относятся
hw = final_hw.rename(columns={"MAPE_%": "MAPE_HW"})
sar = final_sarima.rename(columns={"MAPE_%": "MAPE_SARIMA"})
pr  = final_prophet.rename(columns={"MAPE_%": "MAPE_Prophet"})

# Мёрджим по региону
summary = (
    hw[["Регион", "MAPE_HW"]]
    .merge(sar[["Регион", "MAPE_SARIMA"]], on="Регион")
    .merge(pr[["Регион", "MAPE_Prophet"]], on="Регион")
)

# Определяем для каждой строки, какой столбец MAPE минимален
# idxmin вернёт название столбца с минимальным значением
summary["Best_method"] = summary[["MAPE_HW","MAPE_SARIMA","MAPE_Prophet"]] \
                           .idxmin(axis=1) \
                           .str.replace("MAPE_","")  # убираем префикс для красоты

# Если нужно, можно сразу отсортировать
# summary = summary.sort_values("Best_method")

# допустим, у вас уже есть summary
summary = summary.round({
    "MAPE_HW": 2,
    "MAPE_SARIMA": 2,
    "MAPE_Prophet": 2
})

# Готово!
print(summary.to_string(index=False))
summary.to_excel("results/Овцы и козы - Лучшие модели.xlsx", index=False)