In [1]:
# --- 1. Импорты и общие настройки ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from pmdarima import auto_arima
from statsmodels.tsa.statespace.sarimax import SARIMAX
from prophet import Prophet  # pip install prophet
from sklearn.metrics import mean_squared_error, mean_absolute_error
import warnings
pd.options.display.float_format = '{:.2f}'.format
warnings.filterwarnings("ignore")
# plt.style.use("seaborn-whitegrid")

In [2]:
# --- 2. Загрузка данных ---
# df должен содержать столбцы: "Регион", "Период" (YYYY-MM), и целевой столбец с показателем.
df = pd.read_excel("Датасет по молоку.xlsx")
df["Период"] = pd.to_datetime(df["Период"], format="%Y-%m")
df.sample(10)

,Регион,Период,Молоко,Осадки,Поголовье: КРС,Температура,Цена: Молоко
579,ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,2020-12-01,61724.80,32.50,1111042.00,-13.70,135.79
1651,МАНГИСТАУСКАЯ ОБЛАСТЬ,2018-06-01,1117.70,0.00,23410.00,23.95,137.58
2118,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2019-07-01,72544.00,1.80,1070131.00,32.09,112.46
940,ГШЫМКЕНТ,2022-09-01,3693.80,0.00,77711.00,23.29,NaN
846,ГАСТАНА,2022-01-01,12.60,25.00,258.00,-11.26,NaN
389,АТЫРАУСКАЯ ОБЛАСТЬ,2015-09-01,5783.30,12.30,162784.00,21.01,102.30
566,ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,2019-11-01,62361.50,65.70,1057840.00,-6.25,127.25
1351,КАРАГАНДИНСКАЯ ОБЛАСТЬ,2025-03-01,16438.50,NaN,NaN,NaN,NaN
1108,ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,2015-07-01,27562.60,23.70,525595.00,22.69,100.00
1918,ПАВЛОДАРСКАЯ ОБЛАСТЬ,2020-08-01,46247.40,11.80,503971.00,20.36,140.64

In [3]:
regions = df['Регион'].unique()
target   = "Молоко"
horizon  = 3
epsilon = 1e-6

In [4]:
first_test = pd.to_datetime("2024-08-01")
last_possible = df["Период"].max() - pd.DateOffset(months=horizon-1)
test_starts = pd.date_range(first_test, last_possible, freq="MS")

## Holw-Winter's (log)

In [5]:
results_hw = []
for region in regions:
    ts = (df[df["Регион"] == region]
          .set_index("Период")[target]
          .dropna()
          .sort_index())
    if len(ts) < 24:
        print(f"{region}: всего {len(ts)} мес. — сезонный Holt-Winter's невозможен.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        # формируем train / test
        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]

        # пропускаем, если недостаточно данных или неполный test
        if len(train) < 24 or len(test) < horizon:
            continue

        # обучаем модель
        train_log = np.log1p(train)

        hw_log = ExponentialSmoothing(
            train_log,
            seasonal="add",
            seasonal_periods=12
        ).fit(optimized=True)

        # прогноз и метрики
        fc_log = hw_log.forecast(horizon)
        fc = np.expm1(fc_log) 
        # fc   = model.forecast(horizon)
        rmse = np.sqrt(mean_squared_error(test, fc))
        mae  = mean_absolute_error(test, fc)
        mape = (np.abs((test - fc) / test).mean()) * 100

        results_hw.append({
            "Регион":      region,
            "Test start":  test_start.strftime("%Y-%m"),
            "Test end":    test_end.strftime("%Y-%m"),
            "Forecast":    [x.round(2) for x in list(fc.values)],
            "Actual":      [y.round(2) for y in list(test.values)],
            "RMSE":        rmse,
            "MAE":         mae,
            "MAPE_%":      mape
        })

# 4) Усреднение по всем скользящим окнам для каждого региона
res_hw = pd.DataFrame(results_hw)
res_hw.to_excel("results/Молоко - Результаты прогнозов ХВ.xlsx", index=False)
print("Результаты прогнозов HW на 3 месяца:")

display(res_hw)

final_hw = (
    res_hw
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_hw.to_excel("results/Молоко - Результаты прогнозов ХВ средние.xlsx", index=False)
print("Средние метрики Holt–Winter's по регионам (rolling-3):")
display(final_hw)

Результаты прогнозов HW на 3 месяца:

,Регион,Test start,Test end,Forecast,Actual,RMSE,MAE,MAPE_%
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,"[22664.47, 22108.67, 16700.88]","[22673.0, 22635.3, 18373.4]",1012.38,735.90,3.82
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,"[22116.73, 16706.45, 14464.08]","[22635.3, 18373.4, 15949.9]",1323.54,1223.78,6.89
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,"[17017.48, 14729.22, 15792.52]","[18373.4, 15949.9, 16241.4]",1084.75,1008.49,5.93
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,"[15660.77, 16781.84, 9323.12]","[15949.9, 16241.4, 11378.1]",1238.09,961.52,7.73
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,"[17030.25, 9459.76, 10945.48]","[16241.4, 11378.1, 12075.2]",1363.64,1278.97,10.36
...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,"[23750.42, 26365.58, 34344.46]","[33158.0, 35623.7, 44086.4]",9471.37,9469.21,25.49
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,"[36652.5, 47538.7, 56311.11]","[35623.7, 44086.4, 49990.5]",4200.28,3600.57,7.79
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,"[46231.24, 54782.31, 66156.84]","[44086.4, 49990.5, 59303.1]",4984.50,4596.80,8.67
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,"[52285.58, 63179.24, 66262.24]","[49990.5, 59303.1, 61702.9]",3700.43,3576.86,6.17
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,"[60449.86, 63440.39, 50013.08]","[59303.1, 61702.9, 43495.5]",3950.22,3133.94,6.58

Средние метрики Holt–Winter's по регионам (rolling-3):

                            Регион    RMSE     MAE  MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ 1926.95 1744.53    9.43
1              АКТЮБИНСКАЯ ОБЛАСТЬ 1429.97 1284.40    9.94
2              АЛМАТИНСКАЯ ОБЛАСТЬ 2670.18 2350.59   10.77
3               АТЫРАУСКАЯ ОБЛАСТЬ  228.41  192.97    7.50
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 3728.95 3197.45   15.77
5                          ГАЛМАТЫ   20.96   17.59   63.09
6                          ГАСТАНА    3.32    2.98   33.75
7                         ГШЫМКЕНТ  655.34  611.91   10.45
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ  620.64  562.66    3.46
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 1384.59 1246.99    8.46
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ 1055.71  826.93    4.43
11            КОСТАНАЙСКАЯ ОБЛАСТЬ 2039.76 1882.96   10.53
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ  589.84  483.86   11.89
13           МАНГИСТАУСКАЯ ОБЛАСТЬ    0.83    0.67     NaN
14                    ОБЛАСТЬ АБАЙ 1572.07 1453.77    8.68
15                  ОБЛАСТЬ ЖЕТІСУ  929.43  822.33    5.64
16                  ОБЛАСТЬ ҰЛЫТАУ  656.76  558.32   12.33
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ 3707.84 3370.60   16.86
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 6224.14 5500.60   18.55
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ 4236.19 3796.46    9.55

In [6]:
# res_hw[res_hw['Регион'] == 'МАНГИСТАУСКАЯ ОБЛАСТЬ']

## SARIMA

In [6]:
results_sarima = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    ts = ts + epsilon
    ts_log = np.log(ts)

    if len(ts_log) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. для авто-ARIMA, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train_log = ts_log[ts_log.index < test_start]
        test_log  = ts_log[(ts_log.index >= test_start) & (ts_log.index <= test_end)]
        if len(train_log) < 12 + horizon or len(test_log) < horizon:
            continue

        # автоподбор на лог-данных
        use_seasonal = len(train_log) >= 2 * 12

        sarima_log = auto_arima(
            train_log,
            seasonal=use_seasonal,
            m=12 if use_seasonal else 1,
            D=1 if use_seasonal else 0,      # фиксируем порядок сезонной разности
            seasonal_test=None,               # пропустить nsdiffs
            boxcox=True,
            stepwise=True,
            suppress_warnings=True,
            error_action="ignore"
        )
      
        # прогноз в лог-шкале
        fc_log = sarima_log.predict(n_periods=horizon, return_conf_int=False)

        # возвращаем прогноз в исходные единицы
        fc = np.exp(fc_log) - epsilon
        actual = np.exp(test_log.values) - epsilon  # но exp(log(x)) == x

        # метрики на исходном уровне
        rmse = np.sqrt(mean_squared_error(actual, fc))
        mae  = mean_absolute_error(actual, fc)
        mape = (np.abs((actual - fc) / actual).mean()) * 100

        results_sarima.append({
            "Регион":         region,
            "Test start":     test_start.strftime("%Y-%m"),
            "Test end":       test_end.strftime("%Y-%m"),
            "order":          sarima_log.order,
            "seasonal_order": sarima_log.seasonal_order,
            "RMSE":           round(rmse,2),
            "MAE":            round(mae,2),
            "MAPE_%":         round(mape,2),
            "Forecast":       [round(x,2) for x in fc],
            "Actual":         [round(y,2) for y in actual]
        })
# формируем DataFrame с результатами
res_sarima = pd.DataFrame(results_sarima)
res_sarima.to_excel("results/Молоко - Результаты прогнозов SARIMA.xlsx", index=False)
print("Результаты прогнозов SARIMA на 3 месяца:")

display(res_sarima)

final_sarima = (
    res_sarima
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_sarima.to_excel("results/Молоко - Результаты прогнозов SARIMA средние.xlsx", index=False)
print("Средние метрики SARIMA по регионам (rolling-3):")
display(final_sarima)

Результаты прогнозов SARIMA на 3 месяца:

,Регион,Test start,Test end,order,seasonal_order,RMSE,MAE,MAPE_%,Forecast,Actual
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,"(1, 1, 0)","(1, 1, 1, 12)",1406.68,1233.06,6.16,"[22236.04, 21464.76, 16281.72]","[22673.0, 22635.3, 18373.4]"
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,"(1, 1, 0)","(1, 1, 1, 12)",1543.37,1477.56,8.24,"[21786.65, 16542.25, 14197.01]","[22635.3, 18373.4, 15949.9]"
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,"(1, 1, 0)","(1, 1, 1, 12)",1130.81,1075.50,6.35,"[17031.0, 14647.81, 15659.38]","[18373.4, 15949.9, 16241.4]"
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,"(1, 1, 0)","(1, 1, 1, 12)",1882.56,1350.21,11.14,"[15530.89, 16667.58, 8172.65]","[15949.9, 16241.4, 11378.1]"
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,"(1, 1, 0)","(1, 1, 1, 12)",2333.48,2121.25,17.53,"[17011.32, 8360.78, 9498.68]","[16241.4, 11378.1, 12075.2]"
...,...,...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,"(1, 0, 0)","(0, 1, 2, 12)",11854.45,11845.54,31.81,"[21594.85, 24143.74, 31592.88]","[33158.0, 35623.7, 44086.4]"
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,"(1, 0, 0)","(2, 1, 1, 12)",5101.49,4394.30,9.52,"[36950.4, 48277.99, 57655.1]","[35623.7, 44086.4, 49990.5]"
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,"(1, 0, 0)","(2, 1, 1, 12)",6101.62,5590.00,10.52,"[46608.03, 55732.2, 67809.79]","[44086.4, 49990.5, 59303.1]"
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,"(1, 0, 0)","(2, 1, 1, 12)",3169.95,3101.22,5.38,"[52171.23, 62759.61, 65369.33]","[49990.5, 59303.1, 61702.9]"
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,"(1, 0, 0)","(2, 1, 1, 12)",6177.49,4916.65,10.30,"[60979.23, 64619.55, 53652.66]","[59303.1, 61702.9, 43495.5]"

Средние метрики SARIMA по регионам (rolling-3):

                            Регион    RMSE     MAE  MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ 1812.26 1639.63    9.96
1              АКТЮБИНСКАЯ ОБЛАСТЬ 1316.29 1202.32   11.12
2              АЛМАТИНСКАЯ ОБЛАСТЬ 2293.38 2066.48    9.92
3               АТЫРАУСКАЯ ОБЛАСТЬ  215.62  194.89   10.91
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 2998.89 2561.98   13.20
5                          ГАЛМАТЫ   27.56   22.93   81.36
6                          ГАСТАНА    2.72    2.49   29.05
7                         ГШЫМКЕНТ  590.55  544.94    9.66
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ  802.53  714.89    5.17
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 1978.45 1811.75   10.33
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ  929.32  754.61    4.64
11            КОСТАНАЙСКАЯ ОБЛАСТЬ 1479.49 1344.30    8.39
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ 2168.01 1376.51   27.65
13           МАНГИСТАУСКАЯ ОБЛАСТЬ    0.00    0.00  206.67
14                    ОБЛАСТЬ АБАЙ  584.39  441.84    1.53
15                  ОБЛАСТЬ ЖЕТІСУ  374.43  326.52    1.67
16                  ОБЛАСТЬ ҰЛЫТАУ 1038.68  867.17   15.61
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ 3383.01 3076.00   16.39
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 3935.92 3545.51   13.54
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ 5139.17 4539.20   11.39

## Facebook Prophet

In [7]:
results_prophet = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    if len(ts) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. данных, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]
        if len(train) < 12 + horizon or len(test) < horizon:
            continue

        # Подготовка данных для Prophet
#         df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
# # подготовка для одного региона
        df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
        df_prophet["y"] = np.log(df_prophet["y"] + epsilon)

        m = Prophet()
        m.fit(df_prophet)

        future = m.make_future_dataframe(periods=horizon, freq="MS")
        forecast = m.predict(future)

        # берем только прогнозные точки
        yhat_log = forecast["yhat"].values[-horizon:]
        fc = np.exp(yhat_log) - epsilon

        # m = Prophet()
        # m.fit(df_prophet)

        # # Создаем DataFrame будущих дат и делаем прогноз
        # # future = m.make_future_dataframe(periods=horizon, freq="MS")
        # # forecast = m.predict(future)

        # # Отбираем только наши горизонты
        # fc = forecast.set_index("ds")["yhat"].loc[test.index].values
        actual = test.values

        # Расчет метрик
        rmse  = np.sqrt(mean_squared_error(actual, fc))
        mae   = mean_absolute_error(actual, fc)
        mape  = (np.abs((actual - fc) / actual).mean()) * 100

        results_prophet.append({
            "Регион":     region,
            "Test start": test_start.strftime("%Y-%m"),
            "Test end":   test_end.strftime("%Y-%m"),
            "RMSE":       round(rmse, 2),
            "MAE":        round(mae, 2),
            "MAPE_%":     round(mape, 2),
            "Forecast":   [round(x, 2) for x in fc],
            "Actual":     [round(x, 2) for x in actual]
        })

# Собираем результаты в DataFrame
res_prophet = pd.DataFrame(results_prophet)
res_prophet.to_excel("results/Молоко - Результаты прогнозов Prophet.xlsx", index=False)
print("Результаты прогнозов Prophet на 3 месяца:")
display(res_prophet)

final_prophet = (
    res_prophet
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_prophet.to_excel("results/Молоко - Результаты прогнозов Prophet средние.xlsx", index=False)
print("Средние метрики Prophet по регионам (rolling-3):")
display(final_prophet)

16:39:16 - cmdstanpy - INFO - Chain [1] start processing
16:39:16 - cmdstanpy - INFO - Chain [1] done processing
16:39:17 - cmdstanpy - INFO - Chain [1] start processing
16:39:17 - cmdstanpy - INFO - Chain [1] done processing
16:39:17 - cmdstanpy - INFO - Chain [1] start processing
16:39:17 - cmdstanpy - INFO - Chain [1] done processing
16:39:18 - cmdstanpy - INFO - Chain [1] start processing
16:39:18 - cmdstanpy - INFO - Chain [1] done processing
16:39:18 - cmdstanpy - INFO - Chain [1] start processing
16:39:18 - cmdstanpy - INFO - Chain [1] done processing
16:39:18 - cmdstanpy - INFO - Chain [1] start processing
16:39:19 - cmdstanpy - INFO - Chain [1] done processing
16:39:19 - cmdstanpy - INFO - Chain [1] start processing
16:39:19 - cmdstanpy - INFO - Chain [1] done processing
16:39:19 - cmdstanpy - INFO - Chain [1] start processing
16:39:19 - cmdstanpy - INFO - Chain [1] done processing
16:39:19 - cmdstanpy - INFO - Chain [1] start processing
16:39:19 - cmdstanpy - INFO - Chain [1] done processing
16:39:20 - cmdstanpy - INFO - Chain [1] start processing
16:39:20 - cmdstanpy - INFO - Chain [1] done processing
16:39:20 - cmdstanpy - INFO - Chain [1] start processing
16:39:20 - cmdstanpy - INFO - Chain [1] done processing
16:39:20 - cmdstanpy - INFO - Chain [1] start processing
16:39:20 - cmdstanpy - INFO - Chain [1] done processing
16:39:21 - cmdstanpy - INFO - Chain [1] start processing
16:39:21 - cmdstanpy - INFO - Chain [1] done processing
16:39:21 - cmdstanpy - INFO - Chain [1] start processing
16:39:21 - cmdstanpy - INFO - Chain [1] done processing
16:39:21 - cmdstanpy - INFO - Chain [1] start processing
16:39:21 - cmdstanpy - INFO - Chain [1] done processing
16:39:21 - cmdstanpy - INFO - Chain [1] start processing
16:39:22 - cmdstanpy - INFO - Chain [1] done processing
16:39:22 - cmdstanpy - INFO - Chain [1] start processing
16:39:22 - cmdstanpy - INFO - Chain [1] done processing
16:39:22 - cmdstanpy - INFO - Chain [1] start processing
16:39:22 - cmdstanpy - INFO - Chain [1] done processing
16:39:22 - cmdstanpy - INFO - Chain [1] start processing
16:39:23 - cmdstanpy - INFO - Chain [1] done processing
16:39:23 - cmdstanpy - INFO - Chain [1] start processing
16:39:23 - cmdstanpy - INFO - Chain [1] done processing
16:39:23 - cmdstanpy - INFO - Chain [1] start processing
16:39:24 - cmdstanpy - INFO - Chain [1] done processing
16:39:24 - cmdstanpy - INFO - Chain [1] start processing
16:39:24 - cmdstanpy - INFO - Chain [1] done processing
16:39:24 - cmdstanpy - INFO - Chain [1] start processing
16:39:24 - cmdstanpy - INFO - Chain [1] done processing
16:39:25 - cmdstanpy - INFO - Chain [1] start processing
16:39:25 - cmdstanpy - INFO - Chain [1] done processing
16:39:25 - cmdstanpy - INFO - Chain [1] start processing
16:39:25 - cmdstanpy - INFO - Chain [1] done processing
16:39:26 - cmdstanpy - INFO - Chain [1] start processing
16:39:26 - cmdstanpy - INFO - Chain [1] done processing
16:39:27 - cmdstanpy - INFO - Chain [1] start processing
16:39:27 - cmdstanpy - INFO - Chain [1] done processing
16:39:27 - cmdstanpy - INFO - Chain [1] start processing
16:39:27 - cmdstanpy - INFO - Chain [1] done processing
16:39:28 - cmdstanpy - INFO - Chain [1] start processing
16:39:28 - cmdstanpy - INFO - Chain [1] done processing
16:39:29 - cmdstanpy - INFO - Chain [1] start processing
16:39:29 - cmdstanpy - INFO - Chain [1] done processing
16:39:29 - cmdstanpy - INFO - Chain [1] start processing
16:39:30 - cmdstanpy - INFO - Chain [1] done processing
16:39:30 - cmdstanpy - INFO - Chain [1] start processing
16:39:30 - cmdstanpy - INFO - Chain [1] done processing
16:39:31 - cmdstanpy - INFO - Chain [1] start processing
16:39:31 - cmdstanpy - INFO - Chain [1] done processing
16:39:31 - cmdstanpy - INFO - Chain [1] start processing
16:39:31 - cmdstanpy - INFO - Chain [1] done processing
16:39:32 - cmdstanpy - INFO - Chain [1] start processing
16:39:32 - cmdstanpy - INFO - Chain [1] done processing
16:39:33 - cmdstanpy - INFO - Chain [1] start processing
16:39:33 - cmdstanpy - INFO - Chain [1] done processing
16:39:33 - cmdstanpy - INFO - Chain [1] start processing
16:39:34 - cmdstanpy - INFO - Chain [1] done processing
16:39:34 - cmdstanpy - INFO - Chain [1] start processing
16:39:34 - cmdstanpy - INFO - Chain [1] done processing
16:39:35 - cmdstanpy - INFO - Chain [1] start processing
16:39:35 - cmdstanpy - INFO - Chain [1] done processing
16:39:35 - cmdstanpy - INFO - Chain [1] start processing
16:39:35 - cmdstanpy - INFO - Chain [1] done processing
16:39:36 - cmdstanpy - INFO - Chain [1] start processing
16:39:36 - cmdstanpy - INFO - Chain [1] done processing
16:39:37 - cmdstanpy - INFO - Chain [1] start processing
16:39:37 - cmdstanpy - INFO - Chain [1] done processing
16:39:37 - cmdstanpy - INFO - Chain [1] start processing
16:39:37 - cmdstanpy - INFO - Chain [1] done processing
16:39:38 - cmdstanpy - INFO - Chain [1] start processing
16:39:38 - cmdstanpy - INFO - Chain [1] done processing
16:39:38 - cmdstanpy - INFO - Chain [1] start processing
16:39:39 - cmdstanpy - INFO - Chain [1] done processing
16:39:39 - cmdstanpy - INFO - Chain [1] start processing
16:39:39 - cmdstanpy - INFO - Chain [1] done processing
16:39:40 - cmdstanpy - INFO - Chain [1] start processing
16:39:40 - cmdstanpy - INFO - Chain [1] done processing
16:39:41 - cmdstanpy - INFO - Chain [1] start processing
16:39:41 - cmdstanpy - INFO - Chain [1] done processing
16:39:41 - cmdstanpy - INFO - Chain [1] start processing
16:39:42 - cmdstanpy - INFO - Chain [1] done processing
16:39:42 - cmdstanpy - INFO - Chain [1] start processing
16:39:42 - cmdstanpy - INFO - Chain [1] done processing
16:39:43 - cmdstanpy - INFO - Chain [1] start processing
16:39:43 - cmdstanpy - INFO - Chain [1] done processing
16:39:44 - cmdstanpy - INFO - Chain [1] start processing
16:39:44 - cmdstanpy - INFO - Chain [1] done processing
16:39:44 - cmdstanpy - INFO - Chain [1] start processing
16:39:45 - cmdstanpy - INFO - Chain [1] done processing
16:39:45 - cmdstanpy - INFO - Chain [1] start processing
16:39:45 - cmdstanpy - INFO - Chain [1] done processing
16:39:46 - cmdstanpy - INFO - Chain [1] start processing
16:39:46 - cmdstanpy - INFO - Chain [1] done processing
16:39:46 - cmdstanpy - INFO - Chain [1] start processing
16:39:46 - cmdstanpy - INFO - Chain [1] done processing
16:39:47 - cmdstanpy - INFO - Chain [1] start processing
16:39:47 - cmdstanpy - INFO - Chain [1] done processing
16:39:47 - cmdstanpy - INFO - Chain [1] start processing
16:39:47 - cmdstanpy - INFO - Chain [1] done processing
16:39:48 - cmdstanpy - INFO - Chain [1] start processing
16:39:48 - cmdstanpy - INFO - Chain [1] done processing
16:39:48 - cmdstanpy - INFO - Chain [1] start processing
16:39:48 - cmdstanpy - INFO - Chain [1] done processing
16:39:48 - cmdstanpy - INFO - Chain [1] start processing
16:39:49 - cmdstanpy - INFO - Chain [1] done processing
16:39:49 - cmdstanpy - INFO - Chain [1] start processing
16:39:49 - cmdstanpy - INFO - Chain [1] done processing
16:39:49 - cmdstanpy - INFO - Chain [1] start processing
16:39:49 - cmdstanpy - INFO - Chain [1] done processing
16:39:50 - cmdstanpy - INFO - Chain [1] start processing
16:39:50 - cmdstanpy - INFO - Chain [1] done processing
16:39:50 - cmdstanpy - INFO - Chain [1] start processing
16:39:50 - cmdstanpy - INFO - Chain [1] done processing
16:39:51 - cmdstanpy - INFO - Chain [1] start processing
16:39:51 - cmdstanpy - INFO - Chain [1] done processing
16:39:51 - cmdstanpy - INFO - Chain [1] start processing
16:39:51 - cmdstanpy - INFO - Chain [1] done processing
16:39:52 - cmdstanpy - INFO - Chain [1] start processing
16:39:52 - cmdstanpy - INFO - Chain [1] done processing
16:39:52 - cmdstanpy - INFO - Chain [1] start processing
16:39:52 - cmdstanpy - INFO - Chain [1] done processing
16:39:52 - cmdstanpy - INFO - Chain [1] start processing
16:39:52 - cmdstanpy - INFO - Chain [1] done processing
16:39:53 - cmdstanpy - INFO - Chain [1] start processing
16:39:53 - cmdstanpy - INFO - Chain [1] done processing
16:39:54 - cmdstanpy - INFO - Chain [1] start processing
16:39:54 - cmdstanpy - INFO - Chain [1] done processing
16:39:54 - cmdstanpy - INFO - Chain [1] start processing
16:39:55 - cmdstanpy - INFO - Chain [1] done processing
16:39:55 - cmdstanpy - INFO - Chain [1] start processing
16:39:56 - cmdstanpy - INFO - Chain [1] done processing
16:39:56 - cmdstanpy - INFO - Chain [1] start processing
16:39:56 - cmdstanpy - INFO - Chain [1] done processing
16:39:57 - cmdstanpy - INFO - Chain [1] start processing
16:39:57 - cmdstanpy - INFO - Chain [1] done processing
16:39:58 - cmdstanpy - INFO - Chain [1] start processing
16:39:58 - cmdstanpy - INFO - Chain [1] done processing
16:39:58 - cmdstanpy - INFO - Chain [1] start processing
16:39:59 - cmdstanpy - INFO - Chain [1] done processing
16:39:59 - cmdstanpy - INFO - Chain [1] start processing
16:39:59 - cmdstanpy - INFO - Chain [1] done processing
16:40:00 - cmdstanpy - INFO - Chain [1] start processing
16:40:00 - cmdstanpy - INFO - Chain [1] done processing
16:40:01 - cmdstanpy - INFO - Chain [1] start processing
16:40:01 - cmdstanpy - INFO - Chain [1] done processing
16:40:01 - cmdstanpy - INFO - Chain [1] start processing
16:40:01 - cmdstanpy - INFO - Chain [1] done processing
16:40:01 - cmdstanpy - INFO - Chain [1] start processing
16:40:02 - cmdstanpy - INFO - Chain [1] done processing
16:40:02 - cmdstanpy - INFO - Chain [1] start processing
16:40:02 - cmdstanpy - INFO - Chain [1] done processing
16:40:02 - cmdstanpy - INFO - Chain [1] start processing
16:40:03 - cmdstanpy - INFO - Chain [1] done processing
16:40:03 - cmdstanpy - INFO - Chain [1] start processing
16:40:03 - cmdstanpy - INFO - Chain [1] done processing
16:40:03 - cmdstanpy - INFO - Chain [1] start processing
16:40:03 - cmdstanpy - INFO - Chain [1] done processing
16:40:04 - cmdstanpy - INFO - Chain [1] start processing
16:40:04 - cmdstanpy - INFO - Chain [1] done processing
16:40:04 - cmdstanpy - INFO - Chain [1] start processing
16:40:04 - cmdstanpy - INFO - Chain [1] done processing
16:40:05 - cmdstanpy - INFO - Chain [1] start processing
16:40:05 - cmdstanpy - INFO - Chain [1] done processing
16:40:05 - cmdstanpy - INFO - Chain [1] start processing
16:40:05 - cmdstanpy - INFO - Chain [1] done processing
16:40:06 - cmdstanpy - INFO - Chain [1] start processing
16:40:06 - cmdstanpy - INFO - Chain [1] done processing
16:40:06 - cmdstanpy - INFO - Chain [1] start processing
16:40:06 - cmdstanpy - INFO - Chain [1] done processing
16:40:07 - cmdstanpy - INFO - Chain [1] start processing
16:40:07 - cmdstanpy - INFO - Chain [1] done processing
16:40:07 - cmdstanpy - INFO - Chain [1] start processing
16:40:07 - cmdstanpy - INFO - Chain [1] done processing
16:40:07 - cmdstanpy - INFO - Chain [1] start processing
16:40:08 - cmdstanpy - INFO - Chain [1] done processing
16:40:08 - cmdstanpy - INFO - Chain [1] start processing
16:40:08 - cmdstanpy - INFO - Chain [1] done processing
16:40:08 - cmdstanpy - INFO - Chain [1] start processing
16:40:08 - cmdstanpy - INFO - Chain [1] done processing
16:40:09 - cmdstanpy - INFO - Chain [1] start processing
16:40:09 - cmdstanpy - INFO - Chain [1] done processing
16:40:09 - cmdstanpy - INFO - Chain [1] start processing
16:40:09 - cmdstanpy - INFO - Chain [1] done processing
16:40:10 - cmdstanpy - INFO - Chain [1] start processing
16:40:10 - cmdstanpy - INFO - Chain [1] done processing
16:40:10 - cmdstanpy - INFO - Chain [1] start processing
16:40:10 - cmdstanpy - INFO - Chain [1] done processing
16:40:11 - cmdstanpy - INFO - Chain [1] start processing
16:40:11 - cmdstanpy - INFO - Chain [1] done processing
16:40:11 - cmdstanpy - INFO - Chain [1] start processing
16:40:11 - cmdstanpy - INFO - Chain [1] done processing
16:40:12 - cmdstanpy - INFO - Chain [1] start processing
16:40:12 - cmdstanpy - INFO - Chain [1] done processing
16:40:12 - cmdstanpy - INFO - Chain [1] start processing
16:40:12 - cmdstanpy - INFO - Chain [1] done processing
16:40:13 - cmdstanpy - INFO - Chain [1] start processing
16:40:13 - cmdstanpy - INFO - Chain [1] done processing
16:40:13 - cmdstanpy - INFO - Chain [1] start processing
16:40:13 - cmdstanpy - INFO - Chain [1] done processing
16:40:14 - cmdstanpy - INFO - Chain [1] start processing
16:40:14 - cmdstanpy - INFO - Chain [1] done processing
16:40:14 - cmdstanpy - INFO - Chain [1] start processing
16:40:14 - cmdstanpy - INFO - Chain [1] done processing
16:40:15 - cmdstanpy - INFO - Chain [1] start processing
16:40:15 - cmdstanpy - INFO - Chain [1] done processing
16:40:15 - cmdstanpy - INFO - Chain [1] start processing
16:40:15 - cmdstanpy - INFO - Chain [1] done processing
16:40:16 - cmdstanpy - INFO - Chain [1] start processing
16:40:16 - cmdstanpy - INFO - Chain [1] done processing
16:40:16 - cmdstanpy - INFO - Chain [1] start processing
16:40:16 - cmdstanpy - INFO - Chain [1] done processing
16:40:16 - cmdstanpy - INFO - Chain [1] start processing
16:40:17 - cmdstanpy - INFO - Chain [1] done processing
16:40:17 - cmdstanpy - INFO - Chain [1] start processing
16:40:17 - cmdstanpy - INFO - Chain [1] done processing
16:40:17 - cmdstanpy - INFO - Chain [1] start processing
16:40:17 - cmdstanpy - INFO - Chain [1] done processing
16:40:18 - cmdstanpy - INFO - Chain [1] start processing
16:40:18 - cmdstanpy - INFO - Chain [1] done processing
16:40:18 - cmdstanpy - INFO - Chain [1] start processing
16:40:18 - cmdstanpy - INFO - Chain [1] done processing
16:40:19 - cmdstanpy - INFO - Chain [1] start processing
16:40:19 - cmdstanpy - INFO - Chain [1] done processing
16:40:19 - cmdstanpy - INFO - Chain [1] start processing
16:40:19 - cmdstanpy - INFO - Chain [1] done processing
16:40:20 - cmdstanpy - INFO - Chain [1] start processing
16:40:20 - cmdstanpy - INFO - Chain [1] done processing
16:40:20 - cmdstanpy - INFO - Chain [1] start processing
16:40:20 - cmdstanpy - INFO - Chain [1] done processing
16:40:21 - cmdstanpy - INFO - Chain [1] start processing
16:40:21 - cmdstanpy - INFO - Chain [1] done processing
16:40:21 - cmdstanpy - INFO - Chain [1] start processing
16:40:21 - cmdstanpy - INFO - Chain [1] done processing
16:40:22 - cmdstanpy - INFO - Chain [1] start processing
16:40:22 - cmdstanpy - INFO - Chain [1] done processing
16:40:22 - cmdstanpy - INFO - Chain [1] start processing
16:40:22 - cmdstanpy - INFO - Chain [1] done processing
16:40:22 - cmdstanpy - INFO - Chain [1] start processing
16:40:23 - cmdstanpy - INFO - Chain [1] done processing
16:40:23 - cmdstanpy - INFO - Chain [1] start processing
16:40:23 - cmdstanpy - INFO - Chain [1] done processing
16:40:23 - cmdstanpy - INFO - Chain [1] start processing
16:40:24 - cmdstanpy - INFO - Chain [1] done processing
16:40:24 - cmdstanpy - INFO - Chain [1] start processing
16:40:24 - cmdstanpy - INFO - Chain [1] done processing
16:40:24 - cmdstanpy - INFO - Chain [1] start processing
16:40:24 - cmdstanpy - INFO - Chain [1] done processing
16:40:25 - cmdstanpy - INFO - Chain [1] start processing
16:40:25 - cmdstanpy - INFO - Chain [1] done processing
16:40:25 - cmdstanpy - INFO - Chain [1] start processing
16:40:25 - cmdstanpy - INFO - Chain [1] done processing
16:40:26 - cmdstanpy - INFO - Chain [1] start processing
16:40:26 - cmdstanpy - INFO - Chain [1] done processing
16:40:26 - cmdstanpy - INFO - Chain [1] start processing
16:40:26 - cmdstanpy - INFO - Chain [1] done processing
16:40:26 - cmdstanpy - INFO - Chain [1] start processing
16:40:27 - cmdstanpy - INFO - Chain [1] done processing
16:40:27 - cmdstanpy - INFO - Chain [1] start processing
16:40:27 - cmdstanpy - INFO - Chain [1] done processing
16:40:27 - cmdstanpy - INFO - Chain [1] start processing
16:40:27 - cmdstanpy - INFO - Chain [1] done processing
16:40:28 - cmdstanpy - INFO - Chain [1] start processing
16:40:28 - cmdstanpy - INFO - Chain [1] done processing
16:40:28 - cmdstanpy - INFO - Chain [1] start processing
16:40:50 - cmdstanpy - INFO - Chain [1] done processing
16:40:51 - cmdstanpy - INFO - Chain [1] start processing
16:41:09 - cmdstanpy - INFO - Chain [1] done processing
16:41:10 - cmdstanpy - INFO - Chain [1] start processing
16:41:32 - cmdstanpy - INFO - Chain [1] done processing
16:41:33 - cmdstanpy - INFO - Chain [1] start processing
16:41:48 - cmdstanpy - INFO - Chain [1] done processing
16:41:48 - cmdstanpy - INFO - Chain [1] start processing
16:42:02 - cmdstanpy - INFO - Chain [1] done processing
16:42:02 - cmdstanpy - INFO - Chain [1] start processing
16:42:03 - cmdstanpy - INFO - Chain [1] done processing
16:42:03 - cmdstanpy - INFO - Chain [1] start processing
16:42:03 - cmdstanpy - INFO - Chain [1] done processing
16:42:03 - cmdstanpy - INFO - Chain [1] start processing
16:42:04 - cmdstanpy - INFO - Chain [1] done processing
16:42:04 - cmdstanpy - INFO - Chain [1] start processing
16:42:04 - cmdstanpy - INFO - Chain [1] done processing
16:42:04 - cmdstanpy - INFO - Chain [1] start processing
16:42:04 - cmdstanpy - INFO - Chain [1] done processing
16:42:05 - cmdstanpy - INFO - Chain [1] start processing
16:42:17 - cmdstanpy - INFO - Chain [1] done processing
16:42:17 - cmdstanpy - INFO - Chain [1] start processing
16:42:31 - cmdstanpy - INFO - Chain [1] done processing
16:42:31 - cmdstanpy - INFO - Chain [1] start processing
16:42:45 - cmdstanpy - INFO - Chain [1] done processing
16:42:46 - cmdstanpy - INFO - Chain [1] start processing
16:43:01 - cmdstanpy - INFO - Chain [1] done processing
16:43:02 - cmdstanpy - INFO - Chain [1] start processing
16:43:17 - cmdstanpy - INFO - Chain [1] done processing
16:43:17 - cmdstanpy - INFO - Chain [1] start processing
16:43:35 - cmdstanpy - INFO - Chain [1] done processing
16:43:35 - cmdstanpy - INFO - Chain [1] start processing
16:43:36 - cmdstanpy - INFO - Chain [1] done processing
16:43:36 - cmdstanpy - INFO - Chain [1] start processing
16:43:36 - cmdstanpy - INFO - Chain [1] done processing
16:43:36 - cmdstanpy - INFO - Chain [1] start processing
16:43:53 - cmdstanpy - INFO - Chain [1] done processing
16:43:54 - cmdstanpy - INFO - Chain [1] start processing
16:43:54 - cmdstanpy - INFO - Chain [1] done processing
16:43:54 - cmdstanpy - INFO - Chain [1] start processing
16:43:54 - cmdstanpy - INFO - Chain [1] done processing
16:43:54 - cmdstanpy - INFO - Chain [1] start processing
16:43:55 - cmdstanpy - INFO - Chain [1] done processing
16:43:55 - cmdstanpy - INFO - Chain [1] start processing
16:43:55 - cmdstanpy - INFO - Chain [1] done processing
16:43:55 - cmdstanpy - INFO - Chain [1] start processing
16:43:56 - cmdstanpy - INFO - Chain [1] done processing
16:43:56 - cmdstanpy - INFO - Chain [1] start processing
16:43:56 - cmdstanpy - INFO - Chain [1] done processing
16:43:56 - cmdstanpy - INFO - Chain [1] start processing
16:43:56 - cmdstanpy - INFO - Chain [1] done processing
16:43:57 - cmdstanpy - INFO - Chain [1] start processing
16:43:57 - cmdstanpy - INFO - Chain [1] done processing
16:43:57 - cmdstanpy - INFO - Chain [1] start processing
16:43:57 - cmdstanpy - INFO - Chain [1] done processing
16:43:57 - cmdstanpy - INFO - Chain [1] start processing
16:43:58 - cmdstanpy - INFO - Chain [1] done processing
16:43:58 - cmdstanpy - INFO - Chain [1] start processing
16:43:58 - cmdstanpy - INFO - Chain [1] done processing
16:43:58 - cmdstanpy - INFO - Chain [1] start processing
16:43:58 - cmdstanpy - INFO - Chain [1] done processing
16:43:59 - cmdstanpy - INFO - Chain [1] start processing
16:43:59 - cmdstanpy - INFO - Chain [1] done processing
16:43:59 - cmdstanpy - INFO - Chain [1] start processing
16:43:59 - cmdstanpy - INFO - Chain [1] done processing
16:43:59 - cmdstanpy - INFO - Chain [1] start processing
16:43:59 - cmdstanpy - INFO - Chain [1] done processing
16:43:59 - cmdstanpy - INFO - Chain [1] start processing
16:44:00 - cmdstanpy - INFO - Chain [1] done processing
16:44:00 - cmdstanpy - INFO - Chain [1] start processing
16:44:00 - cmdstanpy - INFO - Chain [1] done processing
16:44:00 - cmdstanpy - INFO - Chain [1] start processing

Результаты прогнозов Prophet на 3 месяца:

,Регион,Test start,Test end,RMSE,MAE,MAPE_%,Forecast,Actual
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,4493.28,4465.77,21.45,"[18828.81, 18141.55, 13314.04]","[22673.0, 22635.3, 18373.4]"
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,4383.14,4374.80,23.60,"[18553.01, 13639.26, 11641.92]","[22635.3, 18373.4, 15949.9]"
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,4203.73,4185.63,24.82,"[13723.87, 11738.69, 12545.24]","[18373.4, 15949.9, 16241.4]"
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,4022.31,3984.93,28.79,"[12010.84, 12902.47, 6701.32]","[15949.9, 16241.4, 11378.1]"
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,3775.38,3727.69,29.50,"[13239.95, 6911.61, 8360.05]","[16241.4, 11378.1, 12075.2]"
...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,6292.05,6221.38,17.06,"[26366.21, 28647.13, 39190.62]","[33158.0, 35623.7, 44086.4]"
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,4157.39,3819.27,9.55,"[29776.84, 40299.97, 48165.98]","[35623.7, 44086.4, 49990.5]"
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,1841.52,1404.17,3.05,"[41023.63, 49158.7, 59621.03]","[44086.4, 49990.5, 59303.1]"
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,2608.11,2173.70,3.62,"[50315.24, 61658.36, 65543.98]","[49990.5, 59303.1, 61702.9]"
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,5428.98,4570.09,9.39,"[61037.05, 65073.93, 52100.79]","[59303.1, 61702.9, 43495.5]"

Средние метрики Prophet по регионам (rolling-3):

                            Регион     RMSE     MAE  MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ  3276.09 3229.36   19.57
1              АКТЮБИНСКАЯ ОБЛАСТЬ  2832.43 2706.96   22.16
2              АЛМАТИНСКАЯ ОБЛАСТЬ  6359.82 6164.30   25.56
3               АТЫРАУСКАЯ ОБЛАСТЬ   748.69  689.50   27.40
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  6824.78 6533.59   33.76
5                          ГАЛМАТЫ    17.83   14.98   54.61
6                          ГАСТАНА     3.04    2.78  121.66
7                         ГШЫМКЕНТ  1220.41 1157.05   18.57
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ  2338.18 2193.30   12.86
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  1781.31 1612.72    9.28
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ  3966.48 3528.97   22.41
11            КОСТАНАЙСКАЯ ОБЛАСТЬ  3502.68 3445.87   24.89
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ   806.69  739.61   17.88
13           МАНГИСТАУСКАЯ ОБЛАСТЬ     0.00    0.00     NaN
14                    ОБЛАСТЬ АБАЙ 10258.70 8843.11   48.84
15                  ОБЛАСТЬ ЖЕТІСУ  3145.18 2665.94   17.73
16                  ОБЛАСТЬ ҰЛЫТАУ  3056.43 2366.68   46.63
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ  4618.77 4529.75   25.29
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  5908.14 5666.45   23.96
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ  3535.36 3119.19    8.23

In [8]:
# Переименуем колонки с MAPE, чтобы было понятно, к какому методу относятся
hw = final_hw.rename(columns={"MAPE_%": "MAPE_HW"})
sar = final_sarima.rename(columns={"MAPE_%": "MAPE_SARIMA"})
pr  = final_prophet.rename(columns={"MAPE_%": "MAPE_Prophet"})

# Мёрджим по региону
summary = (
    hw[["Регион", "MAPE_HW"]]
    .merge(sar[["Регион", "MAPE_SARIMA"]], on="Регион")
    .merge(pr[["Регион", "MAPE_Prophet"]], on="Регион")
)

# Определяем для каждой строки, какой столбец MAPE минимален
# idxmin вернёт название столбца с минимальным значением
summary["Best_method"] = summary[["MAPE_HW","MAPE_SARIMA","MAPE_Prophet"]] \
                           .idxmin(axis=1) \
                           .str.replace("MAPE_","")  # убираем префикс для красоты

# Если нужно, можно сразу отсортировать
# summary = summary.sort_values("Best_method")

# допустим, у вас уже есть summary
summary = summary.round({
    "MAPE_HW": 2,
    "MAPE_SARIMA": 2,
    "MAPE_Prophet": 2
})

# Готово!
print(summary.to_string(index=False))
summary.to_excel("results/Молоко - Лучшие модели.xlsx", index=False)

                        Регион  MAPE_HW  MAPE_SARIMA  MAPE_Prophet Best_method
           АКМОЛИНСКАЯ ОБЛАСТЬ     9.43         9.96         19.57          HW
           АКТЮБИНСКАЯ ОБЛАСТЬ     9.94        11.12         22.16          HW
           АЛМАТИНСКАЯ ОБЛАСТЬ    10.77         9.92         25.56      SARIMA
            АТЫРАУСКАЯ ОБЛАСТЬ     7.50        10.91         27.40          HW
ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ    15.77        13.20         33.76      SARIMA
                       ГАЛМАТЫ    63.09        81.36         54.61     Prophet
                       ГАСТАНА    33.75        29.05        121.66      SARIMA
                      ГШЫМКЕНТ    10.45         9.66         18.57      SARIMA
            ЖАМБЫЛСКАЯ ОБЛАСТЬ     3.46         5.17         12.86          HW
 ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ     8.46        10.33          9.28          HW
        КАРАГАНДИНСКАЯ ОБЛАСТЬ     4.43         4.64         22.41          HW
          КОСТАНАЙСКАЯ ОБЛАСТЬ    10.53         8.39         24.89      SARIMA
        КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ    11.89        27.65         17.88          HW
         МАНГИСТАУСКАЯ ОБЛАСТЬ      NaN       206.67           NaN      SARIMA
                  ОБЛАСТЬ АБАЙ     8.68         1.53         48.84      SARIMA
                ОБЛАСТЬ ЖЕТІСУ     5.64         1.67         17.73      SARIMA
                ОБЛАСТЬ ҰЛЫТАУ    12.33        15.61         46.63          HW
          ПАВЛОДАРСКАЯ ОБЛАСТЬ    16.86        16.39         25.29      SARIMA
  СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ    18.55        13.54         23.96      SARIMA
         ТУРКЕСТАНСКАЯ ОБЛАСТЬ     9.55        11.39          8.23     Prophet