### Подготовка датасета по показателю количество полученных яиц

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import kpss
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.arima.model import ARIMA
from pmdarima import auto_arima
from statsmodels.graphics.tsaplots import plot_acf
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

from pylab import rcParams
from IPython.display import display
import math
from prophet import Prophet
pd.set_option('display.max_columns', 130)


import warnings
from statsmodels.tools.sm_exceptions import InterpolationWarning
warnings.simplefilter("ignore", category=InterpolationWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

In [2]:
df = pd.read_excel("../../Data cleansing/output data/Просуммированные по категориям с доп регрессорами.xlsx")
df.head(5)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,Верблюды,АКМОЛИНСКАЯ ОБЛАСТЬ,0.00,0.00,0.40,0.00,0.00,0.00,0.09,1.00,0.00,0.00,0.20,0.00,0.00,0.18,0.28,0.00,0.00,0.40,0.00,0.00,0.65,0.00,0.31,1.00,0.00,0.00,0.00,0.00,0.00,2.01,0.00,1.20,0.00,0.00,2.18,0.39,0.00,0.00,1.04,0.00,0.14,2.08,0.00,0.00,0.00,0.00,0.00,0.30,0.00,0.00,0.00,0.66,0.00,0.33,0.00,0.9,0.00,0.00,0.00,10.08,0.00,0.0,0.00,0.0,0.00,0.54,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.36,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.40,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00
1,Верблюды,АКТЮБИНСКАЯ ОБЛАСТЬ,101.98,67.47,374.84,115.59,218.72,14.15,19.77,3.00,39.16,46.16,238.56,463.35,109.04,72.94,384.96,114.35,221.89,10.93,18.79,3.50,38.53,46.64,216.08,472.07,110.32,68.17,380.15,127.12,217.61,14.98,21.26,7.14,44.63,51.78,239.43,513.33,115.70,69.40,371.53,130.17,218.41,14.59,21.76,7.19,45.97,55.48,252.68,527.66,117.94,70.37,385.75,117.80,218.45,15.54,21.78,7.2,47.06,58.02,257.54,543.35,119.80,71.3,396.90,121.8,228.10,15.90,21.9,7.2,63.00,59.90,260.20,552.10,121.60,71.8,398.40,128.50,228.80,13.10,22.50,7.20,63.90,61.90,150.70,554.90,121.30,73.3,404.20,128.70,234.90,13.60,23.60,6.3,49.80,62.4,153.70,552.8,118.07,69.17,384.21,121.01,223.46,11.76,21.39,5.52,48.18,61.39,150.87,531.79,119.50,72.60,391.0,126.1,229.10,12.2,24.10,5.7,49.87,63.00,154.3,538.40
2,Верблюды,АЛМАТИНСКАЯ ОБЛАСТЬ,1.00,0.20,51.60,25.40,0.00,61.90,76.87,95.57,16.09,0.10,10.80,46.78,15.06,13.70,131.80,9.20,17.89,130.12,2.00,0.00,4.99,2.06,4.90,44.48,15.06,23.94,41.60,19.54,3.00,15.14,18.50,14.82,14.52,12.60,9.92,43.11,20.72,2.96,15.24,0.00,1.00,20.03,3.44,7.77,117.25,1.00,0.00,20.34,21.95,3.04,17.91,26.81,9.16,18.80,13.37,0.0,17.29,15.90,4.69,23.10,10.85,9.7,42.75,0.0,6.21,21.10,4.0,2.6,28.10,4.53,79.50,93.18,23.70,11.2,16.00,2.00,3.10,19.62,2.30,4.85,11.18,2.80,9.65,36.44,10.60,11.5,26.10,7.20,12.75,11.20,11.20,27.0,25.26,17.9,21.90,12.5,16.55,16.81,22.78,12.10,12.44,6.85,39.65,17.22,8.85,27.48,0.48,29.72,18.90,17.40,12.5,16.4,11.60,16.7,15.70,24.0,7.70,6.90,5.4,12.60
3,Верблюды,АТЫРАУСКАЯ ОБЛАСТЬ,213.89,167.70,306.60,164.97,342.57,192.00,43.60,113.03,262.37,193.97,308.17,1087.33,325.10,190.60,301.10,154.84,328.50,220.30,66.10,118.20,234.90,196.51,270.92,974.18,303.30,167.41,323.54,182.34,349.10,249.40,57.57,88.40,221.21,199.63,278.80,964.02,305.22,159.62,326.87,159.50,367.20,257.50,60.01,78.10,253.27,332.00,355.05,989.86,280.08,165.05,334.51,134.85,367.97,321.22,126.22,93.7,263.10,366.66,348.54,1041.38,293.40,154.8,339.44,143.6,405.80,308.35,88.5,130.5,575.30,458.70,357.62,998.10,292.76,188.3,487.02,129.28,421.44,351.20,95.77,97.54,624.80,631.65,499.30,1179.66,286.67,189.8,513.16,171.46,402.10,432.22,121.53,126.2,637.50,651.7,482.94,1412.2,307.85,200.59,466.60,182.63,414.56,405.19,184.80,154.96,717.92,719.01,522.83,1164.77,323.81,423.76,441.9,219.1,487.69,446.9,191.43,133.5,730.34,709.68,537.6,930.28
4,Верблюды,ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,0.30,0.00,0.00,1.14,6.12,4.70,4.20,1.80,1.80,0.00,6.82,18.78,0.74,0.00,1.80,2.38,1.22,2.40,3.20,2.45,0.90,2.20,0.74,12.46,0.74,2.70,1.80,0.00,0.00,3.00,0.00,0.00,0.90,7.58,1.85,13.27,0.50,0.60,1.27,0.00,0.50,1.70,0.00,0.00,3.54,3.01,11.51,21.95,0.90,0.00,0.75,4.56,4.50,3.20,0.40,8.4,5.40,0.50,2.30,17.77,0.00,0.6,0.60,2.7,0.00,3.10,0.0,0.6,5.85,3.15,3.50,2.80,0.00,0.0,0.90,1.35,0.00,3.30,0.50,0.00,7.60,0.00,2.20,5.50,0.00,0.2,0.00,1.00,0.00,0.00,0.00,0.0,0.00,0.0,0.30,1.7,0.00,0.00,0.00,0.40,0.00,0.00,0.00,0.30,0.00,0.00,0.70,0.50,0.00,0.00,0.0,0.8,0.00,0.0,0.50,0.0,0.00,0.40,0.0,0.00

In [3]:
df['Показатель'].unique()

array(['Верблюды', 'КРС', 'Лошади', 'Молоко', 'Овцы и козы', 'Птица',
       'Свиньи', 'Яйца', 'Температура', 'Поголовье: КРС',
       'Поголовье: лошади', 'Поголовье: овцы и козы', 'Поголовье: свиньи',
       'Поголовье: птица домашняя', 'Поголовье: верблюды', 'Осадки',
       'Цена: Говядина', 'Цена: Баранина', 'Цена: Молоко', 'Цена: Яйца'],
      dtype=object)

In [4]:
df_eggs = df[df['Показатель'].isin(['Яйца', 'Температура', 'Осадки', 'Поголовье: птица домашняя', 'Цена: Яйца'])]
df_eggs.sample(10)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
406,Цена: Яйца,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+02,1.000000e+02,1.584000e+02,1.584000e+02,1.710720e+02,2.088789e+02,2.088789e+02,2.088789e+02,2.306023e+02,2.306023e+02,2.306023e+02,2.306023e+02,2.306023e+02,2.306023e+02,2.306023e+02,2.306023e+02,2.638091e+02,2.532567e+02,2.565490e+02,2.688634e+02,2.780047e+02,2.746687e+02,2.840074e+02,2.746352e+02,2.784801e+02,2.648345e+02,2.621862e+02,2.682165e+02,2.521235e+02,2.740582e+02,2.948867e+02,3.223111e+02,3.509968e+02,3.731096e+02,3.820642e+02,3.820642e+02,3.763333e+02,3.721936e+02,3.662385e+02,3.629424e+02,4.072213e+02,4.927378e+02,4.991434e+02,4.991434e+02,4.971468e+02,5.026154e+02,4.810030e+02,4.588768e+02,3.973873e+02,3.973873e+02,4.053351e+02,4.628927e+02,4.971467e+02,5.284670e+02,5.427356e+02,5.579322e+02,5.478894e+02,5.407668e+02,5.396853e+02,5.391456e+02,4.286208e+02,4.341928e+02,4.337586e+02,4.337586e+02,4.701944e+02,4.894723e+02,6.162457e+02,6.710915e+02,6.898821e+02,6.381409e+02,5.979381e+02,4.089896e+02,4.830168e+02,4.830168e+02,4.830168e+02,4.892960e+02,5.303968e+02,5.468391e+02,5.993357e+02
290,Поголовье: птица домашняя,ОБЛАСТЬ ҰЛЫТАУ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.362350e+05,1.299790e+05,1.140620e+05,1.129190e+05,1.093180e+05,1.071700e+05,1.053600e+05,5.415900e+04,5.342600e+04,4.620400e+04,3.965600e+04,3.869600e+04,8.448400e+04,6.410600e+04,5.997800e+04,5.916700e+04,5.750000e+04,5.635300e+04,5.484000e+04,9.596400e+04,9.455600e+04,9.300600e+04,9.226600e+04,9.124800e+04,9.086100e+04,9.042100e+04,1.003800e+05,1.313000e+05,1.421480e+05,1.381310e+05,1.474600e+05
279,Поголовье: птица домашняя,КОСТАНАЙСКАЯ ОБЛАСТЬ,4.339047e+06,4.252332e+06,4.355080e+06,4.403034e+06,4.258368e+06,4.218033e+06,4.711784e+06,4.864764e+06,4.845163e+06,4.782079e+06,4.798043e+06,4.685533e+06,4.495239e+06,4.334432e+06,4.511248e+06,4.470723e+06,4.321941e+06,4.369219e+06,4.337111e+06,4.435447e+06,4.395796e+06,4.551720e+06,4.775232e+06,4.532263e+06,4.284287e+06,4.433611e+06,4.528159e+06,4.363778e+06,4.296913e+06,4.283906e+06,4.452240e+06,4.673813e+06,4.600709e+06,4.486298e+06,4.433128e+06,4.245038e+06,4.117564e+06,4.149294e+06,4.157810e+06,4.344277e+06,4.244812e+06,4.257266e+06,4.869345e+06,5.012916e+06,4.987508e+06,4.769061e+06,4.773035e+06,4.422940e+06,4.303083e+06,4.369091e+06,4.389773e+06,4.297663e+06,4.286190e+06,4.251613e+06,4.858978e+06,4.931750e+06,4.908137e+06,4.868989e+06,4.714512e+06,4.266751e+06,4.266751e+06,4.563915e+06,4.687077e+06,4.582234e+06,4.427115e+06,4.469884e+06,4.491843e+06,5.019799e+06,5.052201e+06,4.883871e+06,4.674603e+06,4.518040e+06,4.024863e+06,4.271223e+06,4.346823e+06,4.151946e+06,4.075840e+06,4.625737e+06,4.491876e+06,5.308901e+06,5.495002e+06,5.499719e+06,5.446472e+06,5.611087e+06,4.821638e+06,4.632143e+06,4.243633e+06,4.112320e+06,4.031824e+06,4.028955e+06,4.095478e+06,4.728193e+06,4.798931e+06,4.840453e+06,4.848771e+06,4.996426e+06,2.209989e+06,2.359025e+06,2.282587e+06,2.224496e+06,2.147514e+06,2.161570e+06,1.943523e+06,2.231707e+06,2.041445e+06,2.151569e+06,2.252787e+06,2.119063e+06,2.925292e+06,3.045795e+06,3.013031e+06,2.978347e+06,2.929987e+06,2.629666e+06,2.589533e+06,2.880509e+06,2.831284e+06,2.877183e+06,3.053867e+06,2.951288e+06
321,Осадки,КОСТАНАЙСКАЯ ОБЛАСТЬ,2.280000e+01,3.400000e+00,1.490000e+01,2.010000e+01,8.230000e+01,3.760000e+01,4.790000e+01,2.300000e+01,3.790000e+01,3.200000e+01,3.180000e+01,5.870000e+01,2.820000e+01,2.670000e+01,3.810000e+01,3.660000e+01,2.500000e+00,5.140000e+01,7.110000e+01,1.080000e+01,7.420000e+01,2.400000e+01,3.630000e+01,3.340000e+01,2.050000e+01,2.850000e+01,1.240000e+01,1.790000e+01,5.210000e+01,7.730000e+01,6.770000e+01,3.680000e+01,7.300000e+00,2.650000e+01,6.100000e+00,1.780000e+01,2.100000e+00,6.500000e+00,3.830000e+01,3.310000e+01,4.470000e+01,7.640000e+01,3.570000e+01,8.240000e+01,1.170000e+01,3.960000e+01,2.020000e+01,1.020000e+01,8.700000e+00,1.220000e+01,2.420000e+01,1.250000e+01,1.600000e+01,1.280000e+01,2.300000e+01,4.710000e+01,5.170000e+01,4.360000e+01,1.940000e+01,2.660000e+01,2.790000e+01,3.800000e+01,2.240000e+01,3.600000e+01,8.060000e+01,2.310000e+01,1.740000e+01,6.950000e+01,4.200000e+01,3.880000e+01,1.430000e+01,1.210000e+01,2.640000e+01,4.550000e+01,2.640000e+01,1.410000e+01,5.500000e+00,1.370000e+01,1.035000e+02,5.400000e+00,1.660000e+01,1.160000e+01,1.330000e+01,3.020000e+01,2.280000e+01,1.560000e+01,1.360000e+01,5.800000e+00,5.340000e+01,2.110000e+01,8.120000e+01,1.500000e+01,8.300000e+00,2.910000e+01,5.380000e+01,8.700000e+00,1.500000e+01,1.820000e+01,1.960000e+01,5.000000e-01,1.940000e+01,4.730000e+01,4.300000e+01,1.024000e+02,2.720000e+01,6.360000e+01,5.520000e+01,3.580000e+01,4.500000e+01,1.330000e+01,1.410000e+01,3.140000e+01,3.020000e+01,5.180000e+01,5.600000e+01,7.130000e+01,1.050000e+01,8.900000e+00,3.700000e+01,6.500000e+00
316,Осадки,АЛМАТИНСКАЯ ОБЛАСТЬ,8.900000e+00,2.130000e+01,4.860000e+01,6.150000e+01,3.600000e+01,6.320000e+01,4.400000e+00,2.160000e+01,1.080000e+01,4.550000e+01,5.990000e+01,2.750000e+01,4.100000e+01,6.200000e+00,4.290000e+01,8.830000e+01,1.675000e+02,6.490000e+01,7.880000e+01,3.000000e-01,1.890000e+01,6.000000e+01,5.860000e+01,6.070000e+01,1.590000e+01,3.110000e+01,4.170000e+01,9.950000e+01,4.570000e+01,6.220000e+01,8.900000e+00,1.330000e+01,1.630000e+01,2.210000e+01,4.030000e+01,1.570000e+01,2.670000e+01,2.560000e+01,7.730000e+01,5.960000e+01,7.570000e+01,2.200000e+01,6.960000e+01,2.190000e+01,1.320000e+01,2.730000e+01,2.910000e+01,1.410000e+01,1.830000e+01,3.230000e+01,1.760000e+01,9.090000e+01,4.750000e+01,4.470000e+01,6.900000e+00,2.830000e+01,4.420000e+01,3.490000e+01,2.530000e+01,3.420000e+01,1.160000e+01,4.900000e+01,2.340000e+01,9.970000e+01,8.280000e+01,2.700000e+01,2.570000e+01,4.760000e+01,4.800000e+00,4.000000e+00,9.100000e+00,1.030000e+01,6.900000e+00,3.380000e+01,6.620000e+01,4.290000e+01,4.890000e+01,1.180000e+01,1.580000e+01,1.580000e+01,1.600000e+00,4.070000e+01,3.770000e+01,7.300000e+00,1.570000e+01,2.300000e+01,9.480000e+01,3.190000e+01,8.710000e+01,2.900000e+01,1.220000e+01,1.110000e+01,1.500000e+00,3.000000e+01,6.670000e+01,7.400000e+00,2.080000e+01,2.000000e+01,3.430000e+01,3.710000e+01,2.650000e+01,9.400000e+00,4.280000e+01,4.080000e+01,3.720000e+01,5.130000e+01,3.970000e+01,4.800000e+01,3.560000e+01,3.730000e+01,7.570000e+01,7.340000e+01,9.070000e+01,1.420000e+01,6.970000e+01,6.800000e+00,3.270000e+01,6.040000e+01,3.620000e+01,3.030000e+01
314,Осадки,АКМОЛИНСКАЯ ОБЛАСТЬ,9.800000e+00,9.800000e+00,8.300000e+00,8.800000e+00,4.280000e+01,1.670000e+01,3.960000e+01,2.350000e+01,1.450000e+01,4.310000e+01,2.810000e+01,1.590000e+01,1.970000e+01,1.270000e+01,1.900000e+01,2.000000e+01,4.900000e+00,8.880000e+01,1.030000e+02,2.790000e+01,4.680000e+01,2.830000e+01,1.970000e+01,4.010000e+01,1.250000e+01,1.340000e+01,1.850000e+01,1.680000e+01,3.370000e+01,5.050000e+01,4.940000e+01,8.700000e+00,8.900000e+00,3.470000e+01,1.770000e+01,8.000000e+00,1.330000e+01,6.000000e+00,1.770000e+01,1.690000e+01,3.660000e+01,5.610000e+01,7.120000e+01,1.278000e+02,2.020000e+01,3.530000e+01,1.560000e+01,8.800000e+00,5.700000e+00,1.830000e+01,1.430000e+01,2.210000e+01,2.490000e+01,3.720000e+01,1.440000e+01,3.500000e+01,7.410000e+01,2.780000e+01,1.770000e+01,1.840000e+01,1.230000e+01,1.420000e+01,3.500000e+00,2.690000e+01,2.400000e+01,9.100000e+00,4.690000e+01,3.220000e+01,1.610000e+01,8.500000e+00,8.300000e+00,9.600000e+00,2.840000e+01,2.470000e+01,2.190000e+01,7.500000e+00,1.880000e+01,1.370000e+01,4.350000e+01,3.820000e+01,1.750000e+01,1.250000e+01,1.730000e+01,4.500000e+00,8.100000e+00,1.300000e+01,9.800000e+00,9.600000e+00,1.680000e+01,6.870000e+01,1.201000e+02,2.150000e+01,3.500000e+00,3.880000e+01,3.210000e+01,1.100000e+01,1.320000e+01,1.140000e+01,2.290000e+01,2.600000e+00,1.180000e+01,1.890000e+01,4.110000e+01,6.240000e+01,7.130000e+01,3.500000e+01,3.570000e+01,3.220000e+01,3.140000e+01,9.900000e+00,1.140000e+01,2.180000e+01,5.190000e+01,6.190000e+01,5.180000e+01,4.900000e+01,1.500000e+01,1.560000e+01,2.370000e+01,1.640000e+01
161,Яйца,ОБЛАСТЬ АБАЙ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.827700e+03,7.202400e+03,6.153800e+03,5.538600e+03,4.821800e+03,3.898900e+03,3.526400e+03,2.364500e+03,3.184600e+03,4.336300e+03,4.836000e+03,6.870600e+03,7.328700e+03,6.869300e+03,5.644800e+03,5.197600e+03,3.834500e+03,2.931200e+03,3.315200e+03,2.308200e+03,2.958400e+03,4.585100e+03,4.970800e+03,6.800600e+03,6.902500e+03,7.055300e+03,6.256200e+03,5.516800e+03,4.175400e+03,3.304700e+03,3.916900e+03
150,Яйца,АТЫРАУСКАЯ ОБЛАСТЬ,2.611100e+03,2.646800e+03,2.663600e+03,2.912500e+03,4.336200e+03,5.047900e+03,5.047900e+03,5.694400e+03,6.106100e+03,6.182700e+03,6.195000e+03,6.540200e+03,7.640000e+03,7.640000e+03,7.698600e+03,7.547500e+03,7.890600e+03,8.035200e+03,8.169400e+03,9.078700e+03,9.446800e+03,8.818800e+03,8.782300e+03,7.697300e+03,8.937900e+03,8.234700e+03,7.749900e+03,7.454800e+03,7.610500e+03,6.702400e+03,7.405800e+03,8.829500e+03,8.440000e+03,8.607000e+03,8.034000e+03,1.083110e+04,9.358400e+03,9.022100e+03,9.354700e+03,9.875500e+03,1.105910e+04,1.065500e+04,1.045800e+04,1.061230e+04,1.106980e+04,1.090580e+04,1.150480e+04,1.160230e+04,1.082710e+04,1.018720e+04,1.046450e+04,9.533700e+03,9.873200e+03,9.885000e+03,9.850100e+03,1.048010e+04,9.631100e+03,9.643400e+03,1.027060e+04,9.378700e+03,1.023470e+04,9.197200e+03,6.401300e+03,7.490800e+03,4.880900e+03,3.173900e+03,2.593600e+03,2.249700e+03,1.976900e+03,2.234100e+03,2.280800e+03,2.297600e+03,2.233800e+03,3.669000e+03,5.326000e+03,5.284500e+03,4.883100e+03,3.982600e+03,3.008100e+03,2.674100e+03,2.350100e+03,2.196000e+03,1.710000e+03,1.599900e+03,1.506200e+03,1.677500e+03,3.059500e+03,2.747000e+03,2.613800e+03,2.387000e+03,1.959600e+03,1.674400e+03,1.459600e+03,1.186300e+03,9.661000e+02,9.660000e+02,9.057000e+02,7.980000e+02,8.809000e+02,8.036000e+02,5.467000e+02,1.702000e+02,2.140000e+02,1.352000e+02,1.284000e+02,9.310000e+01,4.532000e+02,1.674500e+03,1.750400e+03,1.637700e+03,1.784400e+03,1.712400e+03,1.822600e+03,1.773700e+03,2.353900e+03,3.327400e+03,3.278000e+03,3.283500e+03,3.123700e+03,3.581100e+03
404,Цена: Яйца,СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,1.025000e+02,9.942500e+01,9.793362e+01,9.509355e+01,8.729588e+01,7.036048e+01,6.445020e+01,6.625480e+01,6.970005e+01,9.256167e+01,1.121847e+02,1.232910e+02,1.255103e+02,1.258868e+02,1.195925e+02,1.191141e+02,1.035101e+02,8.932926e+01,9.022255e+01,9.987636e+01,1.038714e+02,1.185173e+02,1.284727e+02,1.481291e+02,1.476847e+02,1.414819e+02,1.389353e+02,1.385184e+02,9.820958e+01,9.506687e+01,9.677807e+01,8.487437e+01,9.302231e+01,1.020455e+02,1.164339e+02,1.142216e+02,1.098812e+02,1.026291e+02,1.079658e+02,1.085056e+02,9.656998e+01,8.923067e+01,9.262143e+01,8.789774e+01,9.238052e+01,1.143671e+02,1.177981e+02,1.294601e+02,1.345091e+02,1.357196e+02,1.330052e+02,1.316752e+02,1.236430e+02,1.095477e+02,9.914067e+01,1.185722e+02,1.319709e+02,1.364579e+02,1.556985e+02,1.675316e+02,1.661913e+02,1.281335e+02,1.458159e+02,1.541274e+02,1.471917e+02,1.179006e+02,1.191975e+02,1.145488e+02,1.400931e+02,1.727348e+02,1.727348e+02,1.908720e+02,1.986977e+02,1.927368e+02,2.106613e+02,2.026562e+02,1.584771e+02,1.079229e+02,1.526030e+02,1.526030e+02,1.414630e+02,2.185604e+02,2.109107e+02,2.113326e+02,1.940033e+02,1.676188e+02,1.873979e+02,1.918954e+02,1.585056e+02,1.646873e+02,1.931782e+02,1.833262e+02,2.339242e+02,2.622290e+02,2.834695e+02,2.755324e+02,2.777367e+02,2.619057e+02,2.721200e+02,2.634121e+02,2.273247e+02,1.982271e+02,2.057598e+02,2.002042e+02,2.208253e+02,2.660945e+02,2.751417e+02,3.032061e+02,3.174568e+02,3.219012e+02,3.144975e+02,2.748708e+02,2.163233e+02,2.243273e+02,2.218597e+02,2.185318e+02,2.572119e+02,2.628706e+02,2.670765e+02,2.865731e+02
173,Температура,ЖАМБЫЛСКАЯ ОБЛАСТЬ,-2.306452e+00,1.871429e+00,3.958065e+00,1.416667e+01,2.010645e+01,2.502667e+01,2.750000e+01,2.356452e+01,1.606000e+01,1.118387e+01,4.213333e+00,1.609677e+00,1.487097e+00,1.458621e+00,9.851613e+00,1.311667e+01,1.785484e+01,2.392333e+01,2.498387e+01,2.352581e+01,2.017667e+01,7.132258e+00,6.866667e-01,1.548387e+00,-5.451613e-01,-2.192857e+00,2.222581e+00,1.112333e+01,1.971935e+01,2.360000e+01,2.640968e+01,2.336129e+01,1.803000e+01,1.105806e+01,5.483333e+00,-2.193548e+00,-9.332258e+00,-3.092857e+00,9.490323e+00,1.228667e+01,1.720323e+01,2.327667e+01,2.644194e+01,2.410645e+01,1.678333e+01,1.084839e+01,-3.333333e-03,-1.641935e+00,5.709677e-01,5.928571e-01,8.725806e+00,1.272333e+01,1.781290e+01,2.308000e+01,2.827742e+01,2.470645e+01,1.784000e+01,1.181935e+01,4.466667e-01,1.361290e+00,-1.964516e+00,3.465517e+00,6.729032e+00,1.367667e+01,1.939032e+01,2.355333e+01,2.610645e+01,2.429032e+01,1.640333e+01,8.903226e+00,-1.023333e+00,-5.861290e+00,-5.119355e+00,2.778571e+00,4.696774e+00,1.241667e+01,2.066774e+01,2.487667e+01,2.801613e+01,2.523226e+01,1.969000e+01,7.790323e+00,2.106667e+00,2.500000e+00,1.525806e+00,1.542857e+00,5.712903e+00,1.713667e+01,1.906129e+01,2.523000e+01,2.674839e+01,2.290323e+01,1.990667e+01,1.090000e+01,5.010000e+00,-5.174194e+00,-8.522581e+00,8.928571e-01,8.916129e+00,1.277333e+01,1.823226e+01,2.523000e+01,2.779355e+01,2.396452e+01,1.748000e+01,1.329355e+01,8.036667e+00,-1.093548e+00,6.451613e-03,-2.175862e+00,5.535484e+00,1.278667e+01,1.744194e+01,2.528667e+01,2.575806e+01,2.534516e+01,1.621333e+01,1.138710e+01,5.546667e+00,-2.419355e+00

In [5]:
# Step 1: Pivot to wide format (each indicator becomes columns of periods)
df_wide = df_eggs.pivot(index="Регион", columns="Показатель")

# Step 2: Flatten multi-level columns: ('2015-01', 'КРС') → 'КРС_2015-01'
df_wide.columns = [f"{col[1]}_{col[0]}" for col in df_wide.columns]
df_wide = df_wide.reset_index()

# Step 3: Melt: one row per region-period-indicator
df_melted = df_wide.melt(id_vars="Регион", var_name="indicator_period", value_name="value")

# Step 4: Extract 'Период' and 'Показатель' from the combined column
df_melted["Период"] = df_melted["indicator_period"].str.extract(r"_(\d{4}-\d{2})$")
df_melted["Показатель"] = df_melted["indicator_period"].str.extract(r"^(.+)_\d{4}-\d{2}")

# Step 5: Pivot again to get final modeling format: one row per region+period, one column per indicator
df_eggs = df_melted.pivot_table(index=["Регион", "Период"], columns="Показатель", values="value").reset_index()
print(df_eggs.groupby("Регион").size().reset_index(name="Количество строк"))
df_eggs

                            Регион  Количество строк
0              АКМОЛИНСКАЯ ОБЛАСТЬ               120
1              АКТЮБИНСКАЯ ОБЛАСТЬ               120
2              АЛМАТИНСКАЯ ОБЛАСТЬ               120
3               АТЫРАУСКАЯ ОБЛАСТЬ               120
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ               120
5                          ГАЛМАТЫ               120
6                          ГАСТАНА               120
7                         ГШЫМКЕНТ                79
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ               120
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ               120
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ               120
11            КОСТАНАЙСКАЯ ОБЛАСТЬ               120
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ               120
13           МАНГИСТАУСКАЯ ОБЛАСТЬ               120
14                    ОБЛАСТЬ АБАЙ                31
15                  ОБЛАСТЬ ЖЕТІСУ                31
16                  ОБЛАСТЬ ҰЛЫТАУ                31
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ               120
18            РЕСПУБЛИКА КАЗАХСТАН               120
19    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ               120
20           ТУРКЕСТАНСКАЯ ОБЛАСТЬ                79

Показатель,Регион,Период,Осадки,Поголовье: птица домашняя,Температура,Цена: Яйца,Яйца
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-01,9.8,4436655.0,-12.490323,100.600000,51667.7
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-02,9.8,4446764.0,-10.192857,88.829800,49357.2
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-03,8.3,4461524.0,-5.870968,87.053204,59105.8
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-04,8.8,4575245.0,4.490000,87.227310,61953.7
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-05,42.8,4778690.0,14.574194,69.607394,72700.2
...,...,...,...,...,...,...,...
2166,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-08,0.0,2167498.0,27.874194,483.016761,23808.0
2167,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-09,0.5,2092996.0,20.766667,489.295979,22847.1
2168,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-10,13.6,2088086.0,13.200000,530.396841,21639.9
2169,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-11,12.1,2030035.0,6.500000,546.839143,19659.4
2170,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-12,17.3,2151943.0,-1.854839,599.335701,19576.8

In [6]:
df_eggs = df_eggs[df_eggs["Регион"] != 'РЕСПУБЛИКА КАЗАХСТАН']

In [7]:
df_eggs

Показатель,Регион,Период,Осадки,Поголовье: птица домашняя,Температура,Цена: Яйца,Яйца
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-01,9.8,4436655.0,-12.490323,100.600000,51667.7
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-02,9.8,4446764.0,-10.192857,88.829800,49357.2
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-03,8.3,4461524.0,-5.870968,87.053204,59105.8
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-04,8.8,4575245.0,4.490000,87.227310,61953.7
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-05,42.8,4778690.0,14.574194,69.607394,72700.2
...,...,...,...,...,...,...,...
2166,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-08,0.0,2167498.0,27.874194,483.016761,23808.0
2167,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-09,0.5,2092996.0,20.766667,489.295979,22847.1
2168,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-10,13.6,2088086.0,13.200000,530.396841,21639.9
2169,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-11,12.1,2030035.0,6.500000,546.839143,19659.4
2170,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-12,17.3,2151943.0,-1.854839,599.335701,19576.8

In [8]:
df_eggs.to_excel("Датасет по яйцам с регрессорами.xlsx", index=False)

In [9]:
df_eggs = df_eggs.drop(columns=['Осадки', 'Поголовье: птица домашняя', 'Температура', 'Цена: Яйца'])
df_eggs.sample(10)

Показатель                          Регион   Период     Яйца
1806                  ПАВЛОДАРСКАЯ ОБЛАСТЬ  2021-03  19001.2
1131         ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  2022-09  16372.4
813                                ГАСТАНА  2022-10      0.2
1340                  КОСТАНАЙСКАЯ ОБЛАСТЬ  2020-02  39719.7
1152         ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  2024-06  13068.2
1197                КАРАГАНДИНСКАЯ ОБЛАСТЬ  2018-03  59881.4
507         ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  2017-04  12125.0
268                    АЛМАТИНСКАЯ ОБЛАСТЬ  2017-05  82996.4
184                    АКТЮБИНСКАЯ ОБЛАСТЬ  2020-05  27678.0
882                               ГШЫМКЕНТ  2021-12  13252.2

In [10]:
df_eggs.to_excel("Датасет по яйцам.xlsx", index=False)

In [11]:
# 1) приведение типов
df = df_eggs.copy()
df["Период"] = pd.to_datetime(df["Период"], format="%Y-%m", errors="coerce")
df["Яйца"] = pd.to_numeric(df["Яйца"], errors="coerce")

# 2) wide-таблица: строки — месяцы, столбцы — регионы, значения — КРС
df_eggs_wide = (df
        .pivot_table(index="Период", columns="Регион", values="Яйца", aggfunc="sum")  # если дублей нет — можно aggfunc="first"
        .sort_index())
# 3) Убираем лишний уровень индекса у колонок
df_eggs_wide.columns.name = None

# 4) Возвращаем "Период" в строковый формат YYYY-MM
df_eggs_wide = df_eggs_wide.reset_index()
df_eggs_wide["Период"] = df_eggs_wide["Период"].dt.strftime("%Y-%m")

df_eggs_wide.to_excel("Датасет по яйцам wide.xlsx", index=False)
df_eggs_wide

,Период,АКМОЛИНСКАЯ ОБЛАСТЬ,АКТЮБИНСКАЯ ОБЛАСТЬ,АЛМАТИНСКАЯ ОБЛАСТЬ,АТЫРАУСКАЯ ОБЛАСТЬ,ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,ГАЛМАТЫ,ГАСТАНА,ГШЫМКЕНТ,ЖАМБЫЛСКАЯ ОБЛАСТЬ,ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,КАРАГАНДИНСКАЯ ОБЛАСТЬ,КОСТАНАЙСКАЯ ОБЛАСТЬ,КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ,МАНГИСТАУСКАЯ ОБЛАСТЬ,ОБЛАСТЬ АБАЙ,ОБЛАСТЬ ЖЕТІСУ,ОБЛАСТЬ ҰЛЫТАУ,ПАВЛОДАРСКАЯ ОБЛАСТЬ,СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,ТУРКЕСТАНСКАЯ ОБЛАСТЬ
0,2015-01,51667.7,12433.9,77166.7,2611.1,6106.2,154.1,8.5,NaN,6679.3,10279.2,53238.8,37858.0,197.0,28.7,NaN,NaN,NaN,9637.3,37704.5,NaN
1,2015-02,49357.2,11404.2,68749.0,2646.8,7131.1,35.5,9.1,NaN,5882.9,10693.9,48610.4,33173.6,229.1,29.5,NaN,NaN,NaN,8361.4,37570.6,NaN
2,2015-03,59105.8,13962.1,80477.6,2663.6,10886.9,27.6,11.3,NaN,8486.3,11749.1,53478.1,59139.1,232.1,260.6,NaN,NaN,NaN,9164.5,41732.4,NaN
3,2015-04,61953.7,14037.1,85247.6,2912.5,11777.5,27.6,31.3,NaN,9293.0,13940.3,52742.3,59058.3,427.3,150.6,NaN,NaN,NaN,10447.6,52925.7,NaN
4,2015-05,72700.2,16327.4,100331.2,4336.2,18897.3,29.4,18.6,NaN,12289.6,16197.7,55539.3,55511.7,517.8,186.7,NaN,NaN,NaN,14083.6,68018.4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2024-08,62899.9,17751.9,43050.1,3327.4,5916.0,15.7,0.1,14567.7,14534.9,12949.8,54175.0,34474.8,784.7,64.1,6256.2,27169.4,973.5,18689.8,53762.5,23808.0
116,2024-09,58300.1,19636.9,46554.1,3278.0,5600.6,15.5,0.1,14597.2,11659.5,13164.9,48842.0,33915.9,863.1,62.7,5516.8,29416.8,1757.9,18071.9,51783.9,22847.1
117,2024-10,56071.5,18993.4,49803.9,3283.5,4681.3,15.1,0.1,15961.0,8246.6,10955.9,48503.5,33318.5,747.7,69.0,4175.4,29285.2,961.6,16535.5,47959.4,21639.9
118,2024-11,52213.7,19062.1,51729.5,3123.7,4394.2,15.0,0.1,17495.6,7127.0,11636.6,46995.1,33853.9,671.1,48.5,3304.7,27011.6,806.3,15899.2,47352.0,19659.4
119,2024-12,55640.3,18775.5,47398.6,3581.1,4553.1,15.1,0.1,17266.1,7000.5,10530.0,51088.6,31412.9,695.8,41.1,3916.9,27657.0,1780.6,14834.9,48441.5,19576.8