### Подготовка датасета по показателю количество полученных яиц

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import kpss
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.arima.model import ARIMA
from pmdarima import auto_arima
from statsmodels.graphics.tsaplots import plot_acf
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

from pylab import rcParams
from IPython.display import display
import math
from prophet import Prophet
pd.set_option('display.max_columns', 130)


import warnings
from statsmodels.tools.sm_exceptions import InterpolationWarning
warnings.simplefilter("ignore", category=InterpolationWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

In [2]:
df = pd.read_excel("../../Data cleansing/output data/Просуммированные по категориям с доп регрессорами.xlsx")
df.head(5)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,Верблюды,АКМОЛИНСКАЯ ОБЛАСТЬ,0.00,0.00,0.40,0.00,0.00,0.00,0.09,1.00,0.00,0.00,0.20,0.00,0.00,0.18,0.28,0.00,0.00,0.40,0.00,0.00,0.65,0.00,0.31,1.00,0.00,0.00,0.00,0.00,0.00,2.01,0.00,1.20,0.00,0.00,2.18,0.39,0.00,0.00,1.04,0.00,0.14,2.08,0.00,0.00,0.00,0.00,0.00,0.30,0.00,0.00,0.00,0.66,0.00,0.33,0.00,0.9,0.00,0.00,0.00,10.08,0.00,0.0,0.00,0.0,0.00,0.54,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.36,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.40,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00
1,Верблюды,АКТЮБИНСКАЯ ОБЛАСТЬ,101.98,67.47,374.84,115.59,218.72,14.15,19.77,3.00,39.16,46.16,238.56,463.35,109.04,72.94,384.96,114.35,221.89,10.93,18.79,3.50,38.53,46.64,216.08,472.07,110.32,68.17,380.15,127.12,217.61,14.98,21.26,7.14,44.63,51.78,239.43,513.33,115.70,69.40,371.53,130.17,218.41,14.59,21.76,7.19,45.97,55.48,252.68,527.66,117.94,70.37,385.75,117.80,218.45,15.54,21.78,7.2,47.06,58.02,257.54,543.35,119.80,71.3,396.90,121.8,228.10,15.90,21.9,7.2,63.00,59.90,260.20,552.10,121.60,71.8,398.40,128.50,228.80,13.10,22.50,7.20,63.90,61.90,150.70,554.90,121.30,73.3,404.20,128.70,234.90,13.60,23.60,6.3,49.80,62.4,153.70,552.8,118.07,69.17,384.21,121.01,223.46,11.76,21.39,5.52,48.18,61.39,150.87,531.79,119.50,72.60,391.0,126.1,229.10,12.2,24.10,5.7,49.87,63.00,154.3,538.40
2,Верблюды,АЛМАТИНСКАЯ ОБЛАСТЬ,1.00,0.20,51.60,25.40,0.00,61.90,76.87,95.57,16.09,0.10,10.80,46.78,15.06,13.70,131.80,9.20,17.89,130.12,2.00,0.00,4.99,2.06,4.90,44.48,15.06,23.94,41.60,19.54,3.00,15.14,18.50,14.82,14.52,12.60,9.92,43.11,20.72,2.96,15.24,0.00,1.00,20.03,3.44,7.77,117.25,1.00,0.00,20.34,21.95,3.04,17.91,26.81,9.16,18.80,13.37,0.0,17.29,15.90,4.69,23.10,10.85,9.7,42.75,0.0,6.21,21.10,4.0,2.6,28.10,4.53,79.50,93.18,23.70,11.2,16.00,2.00,3.10,19.62,2.30,4.85,11.18,2.80,9.65,36.44,10.60,11.5,26.10,7.20,12.75,11.20,11.20,27.0,25.26,17.9,21.90,12.5,16.55,16.81,22.78,12.10,12.44,6.85,39.65,17.22,8.85,27.48,0.48,29.72,18.90,17.40,12.5,16.4,11.60,16.7,15.70,24.0,7.70,6.90,5.4,12.60
3,Верблюды,АТЫРАУСКАЯ ОБЛАСТЬ,213.89,167.70,306.60,164.97,342.57,192.00,43.60,113.03,262.37,193.97,308.17,1087.33,325.10,190.60,301.10,154.84,328.50,220.30,66.10,118.20,234.90,196.51,270.92,974.18,303.30,167.41,323.54,182.34,349.10,249.40,57.57,88.40,221.21,199.63,278.80,964.02,305.22,159.62,326.87,159.50,367.20,257.50,60.01,78.10,253.27,332.00,355.05,989.86,280.08,165.05,334.51,134.85,367.97,321.22,126.22,93.7,263.10,366.66,348.54,1041.38,293.40,154.8,339.44,143.6,405.80,308.35,88.5,130.5,575.30,458.70,357.62,998.10,292.76,188.3,487.02,129.28,421.44,351.20,95.77,97.54,624.80,631.65,499.30,1179.66,286.67,189.8,513.16,171.46,402.10,432.22,121.53,126.2,637.50,651.7,482.94,1412.2,307.85,200.59,466.60,182.63,414.56,405.19,184.80,154.96,717.92,719.01,522.83,1164.77,323.81,423.76,441.9,219.1,487.69,446.9,191.43,133.5,730.34,709.68,537.6,930.28
4,Верблюды,ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,0.30,0.00,0.00,1.14,6.12,4.70,4.20,1.80,1.80,0.00,6.82,18.78,0.74,0.00,1.80,2.38,1.22,2.40,3.20,2.45,0.90,2.20,0.74,12.46,0.74,2.70,1.80,0.00,0.00,3.00,0.00,0.00,0.90,7.58,1.85,13.27,0.50,0.60,1.27,0.00,0.50,1.70,0.00,0.00,3.54,3.01,11.51,21.95,0.90,0.00,0.75,4.56,4.50,3.20,0.40,8.4,5.40,0.50,2.30,17.77,0.00,0.6,0.60,2.7,0.00,3.10,0.0,0.6,5.85,3.15,3.50,2.80,0.00,0.0,0.90,1.35,0.00,3.30,0.50,0.00,7.60,0.00,2.20,5.50,0.00,0.2,0.00,1.00,0.00,0.00,0.00,0.0,0.00,0.0,0.30,1.7,0.00,0.00,0.00,0.40,0.00,0.00,0.00,0.30,0.00,0.00,0.70,0.50,0.00,0.00,0.0,0.8,0.00,0.0,0.50,0.0,0.00,0.40,0.0,0.00

In [3]:
df['Показатель'].unique()

array(['Верблюды', 'КРС', 'Лошади', 'Молоко', 'Овцы и козы', 'Птица',
       'Свиньи', 'Яйца', 'Температура', 'Поголовье: КРС',
       'Поголовье: лошади', 'Поголовье: овцы и козы', 'Поголовье: свиньи',
       'Поголовье: птица домашняя', 'Поголовье: верблюды', 'Осадки',
       'Цена: Говядина', 'Цена: Баранина', 'Цена: Молоко', 'Цена: Яйца'],
      dtype=object)

In [4]:
df_eggs = df[df['Показатель'].isin(['Яйца', 'Температура', 'Осадки', 'Поголовье: птица домашняя', 'Цена: Яйца'])]
df_eggs.sample(10)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
275,Поголовье: птица домашняя,АТЫРАУСКАЯ ОБЛАСТЬ,155010.0,142106.0000,133214.000000,122909.00000,230545.000000,259351.000000,246516.000000,299607.000000,345085.000000,336199.000000,308551.00000,296281.000000,323092.000000,313361.000000,307937.000000,415715.000000,410956.000000,405186.000000,451300.000000,445878.000000,442270.000000,500004.000000,494753.000000,469111.000000,322610.000000,499954.000000,410406.000000,408369.000000,406234.000000,343282.000000,393173.000000,386767.000000,381446.000000,379579.000000,372753.000000,431403.000000,429160.000000,426849.000000,425874.000000,484312.000000,532971.000000,5.272150e+05,5.233590e+05,5.191050e+05,5.754800e+05,5.644780e+05,5.076460e+05,4.439750e+05,4.397040e+05,4.834750e+05,4.793180e+05,4.705980e+05,4.594220e+05,4.483120e+05,4.043540e+05,4.010250e+05,4.019510e+05,3.972270e+05,4.636720e+05,4.554700e+05,4.554700e+05,4.527520e+05,4.008330e+05,3.395580e+05,3.288670e+05,2.847380e+05,2.306230e+05,2.260460e+05,1.821760e+05,2.355440e+05,2.644630e+05,2.650470e+05,2.636450e+05,2.631010e+05,3.214510e+05,3.087620e+05,3.208070e+05,2.646870e+05,2.692800e+05,2.685720e+05,2.991540e+05,2.508980e+05,2.437630e+05,2.321740e+05,2.135830e+05,2.109910e+05,1.646580e+05,1.631450e+05,1.533900e+05,1.475870e+05,1.270270e+05,1.258550e+05,1.218750e+05,1.192510e+05,1.167520e+05,7.990100e+04,40510.000000,40245.000000,39937.000000,39568.000000,39198.000000,NaN,NaN,NaN,NaN,56000.000000,55259.000000,55256.000000,7.913000e+04,7.903100e+04,7.892400e+04,7.935500e+04,2.378300e+04,1.365890e+05,1.395320e+05,1.393280e+05,1.971070e+05,1.962200e+05,1.959710e+05,1.945400e+05
160,Яйца,МАНГИСТАУСКАЯ ОБЛАСТЬ,28.7,29.5000,260.600000,150.60000,186.700000,155.600000,155.600000,38.900000,38.900000,38.900000,38.70000,139.900000,126.100000,126.100000,235.400000,247.900000,145.900000,150.300000,139.800000,119.800000,123.500000,110.100000,110.100000,105.900000,193.500000,139.500000,146.000000,164.800000,164.800000,202.600000,834.000000,800.300000,817.000000,517.000000,500.300000,491.900000,482.900000,482.300000,496.700000,508.400000,508.200000,5.487000e+02,8.490000e+02,8.087000e+02,8.248000e+02,8.280000e+02,8.032000e+02,7.924000e+02,7.829000e+02,6.573000e+02,7.914000e+02,8.084000e+02,7.832000e+02,7.987000e+02,8.289000e+02,7.883000e+02,7.739000e+02,7.767000e+02,7.782000e+02,7.674000e+02,7.579000e+02,3.190000e+01,4.040000e+01,5.800000e+01,5.810000e+01,9.870000e+01,9.970000e+01,6.310000e+01,7.370000e+01,7.410000e+01,5.320000e+01,4.240000e+01,3.290000e+01,3.190000e+01,4.040000e+01,5.800000e+01,5.810000e+01,9.870000e+01,9.970000e+01,6.770000e+01,6.910000e+01,7.410000e+01,5.320000e+01,4.240000e+01,3.290000e+01,3.490000e+01,4.340000e+01,6.080000e+01,6.090000e+01,1.015000e+02,1.025000e+02,7.050000e+01,7.190000e+01,7.560000e+01,5.470000e+01,4.400000e+01,29.900000,31.900000,41.700000,57.700000,57.500000,97.400000,93.300000,61.60000,62.700000,68.800000,48.300000,41.100000,3.370000e+01,2.810000e+01,4.160000e+01,5.780000e+01,5.760000e+01,9.730000e+01,9.340000e+01,6.410000e+01,6.270000e+01,6.900000e+01,4.850000e+01,4.110000e+01
288,Поголовье: птица домашняя,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.904739e+06,1.869861e+06,1.979777e+06,1.934265e+06,1.810651e+06,1.632272e+06,2.047650e+06,1.938305e+06,1.865176e+06,1.832725e+06,1.896287e+06,1.818943e+06,1.788240e+06,2.057267e+06,2.127630e+06,2.106614e+06,1.955097e+06,1.907825e+06,2.178513e+06,2.175396e+06,2.127857e+06,2.110616e+06,1.945291e+06,2.065624e+06,1.875024e+06,2.011112e+06,2.024585e+06,2.020382e+06,1.965324e+06,2.080548e+06,1.916242e+06,2.218531e+06,2.058633e+06,2.260159e+06,2.190072e+06,2.351305e+06,2.255366e+06,2.133746e+06,2.270030e+06,2.271633e+06,2.242683e+06,2.148529e+06,2.186669e+06,2.297132e+06,2.173214e+06,2.094731e+06,2.158781e+06,1.903899e+06,1.887691e+06,1.797383e+06,2.092070e+06,2.046538e+06,2.014184e+06,1.989089e+06,1.989250e+06,506873.000000,623044.000000,776363.000000,773508.000000,844057.000000,753500.000000,658005.000000,680404.00000,783016.000000,720357.000000,757284.000000,778323.000000,1.984554e+06,1.996919e+06,1.997072e+06,2.105724e+06,1.967508e+06,1.953752e+06,2.137815e+06,2.167498e+06,2.092996e+06,2.088086e+06,2.030035e+06,2.151943e+06
395,Цена: Яйца,АКМОЛИНСКАЯ ОБЛАСТЬ,100.6,88.8298,87.053204,87.22731,69.607394,64.038802,48.925645,51.469778,72.623857,89.690464,112.11308,121.082126,124.835672,125.709522,124.326717,112.142699,101.713428,95.915762,125.265986,121.633272,128.809635,136.667023,135.983688,144.822628,142.939933,133.934718,133.131109,132.731716,109.901861,112.979113,114.221883,106.683239,114.044382,126.931398,130.358545,131.010338,128.259121,119.922278,126.518003,121.330765,107.620389,9.169257e+01,9.352642e+01,9.109474e+01,1.022994e+02,1.198949e+02,1.432744e+02,1.492919e+02,1.518299e+02,1.381652e+02,1.337439e+02,1.287954e+02,1.210677e+02,1.004862e+02,9.435649e+01,1.098310e+02,1.230107e+02,1.345737e+02,1.426481e+02,1.584820e+02,1.584820e+02,1.470713e+02,1.425121e+02,1.600411e+02,1.489983e+02,1.194966e+02,1.169872e+02,1.194439e+02,1.327022e+02,1.814039e+02,1.928323e+02,2.069091e+02,2.435320e+02,2.576569e+02,2.476083e+02,2.307709e+02,1.989245e+02,1.360644e+02,1.672231e+02,1.784271e+02,1.575511e+02,2.139544e+02,2.026148e+02,1.886344e+02,1.599619e+02,1.495644e+02,1.702043e+02,1.683321e+02,1.376956e+02,1.572484e+02,1.762755e+02,1.709872e+02,2.029618e+02,2.354357e+02,2.505036e+02,2.349724e+02,242.491477,244.673900,261.067052,252.451839,229.983625,191.576360,203.262518,203.46578,218.929180,238.413877,253.195537,270.412833,2.812293e+02,2.905099e+02,2.756939e+02,2.541898e+02,2.099608e+02,2.194090e+02,2.176537e+02,2.019827e+02,2.433891e+02,2.801409e+02,2.728572e+02,2.813158e+02
285,Поголовье: птица домашняя,ГАСТАНА,3858.0,3353.0000,3329.000000,3229.00000,3078.000000,2897.000000,2716.000000,2161.000000,2177.000000,2253.000000,1513.00000,1537.000000,1527.000000,1432.000000,1358.000000,1258.000000,1229.000000,1077.000000,1016.000000,991.000000,969.000000,932.000000,867.000000,830.000000,885.000000,885.000000,840.000000,800.000000,771.000000,726.000000,665.000000,608.000000,588.000000,578.000000,571.000000,1397.000000,1382.000000,1351.000000,1324.000000,1288.000000,1252.000000,1.560000e+03,1.484000e+03,1.415000e+03,1.384000e+03,1.365000e+03,1.349000e+03,9.700000e+01,8.200000e+01,7.700000e+01,7.700000e+01,7.700000e+01,7.700000e+01,7.700000e+01,7.700000e+01,7.700000e+01,7.700000e+01,7.700000e+01,7.700000e+01,7.200000e+01,7.200000e+01,7.200000e+01,7.200000e+01,7.200000e+01,6.000000e+01,6.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,3.795000e+03,3.795000e+03,3.795000e+03,3.775000e+03,3.755000e+03,3.720000e+03,4.283000e+03,4.243000e+03,4.382000e+03,4.332000e+03,4.292000e+03,4.266000e+03,3.122000e+03,3.122000e+03,3.086000e+03,3.068000e+03,3.040000e+03,3.010000e+03,1.734000e+03,1.716000e+03,1.668000e+03,1.636000e+03,1.608000e+03,1.588000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.670000e+02,7.670000e+02,7.550000e+02,7.420000e+02,7.320000e+02,6.990000e+02,3.000000e+02,2.900000e+02,2.750000e+02,2.730000e+02,2.630000e+02,2.530000e+02
159,Яйца,КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ,197.0,229.1000,232.100000,427.30000,517.800000,599.500000,599.500000,606.600000,680.200000,584.900000,540.80000,524.000000,200.300000,200.300000,234.500000,426.500000,492.100000,545.100000,604.300000,619.500000,689.800000,573.900000,544.100000,523.600000,201.000000,239.500000,242.000000,428.800000,494.100000,697.800000,749.000000,772.100000,849.700000,729.700000,660.400000,639.200000,351.800000,380.900000,393.800000,685.100000,749.800000,8.025000e+02,8.664000e+02,8.065000e+02,8.905000e+02,8.817000e+02,7.422000e+02,7.507000e+02,5.813000e+02,5.936000e+02,4.982000e+02,6.978000e+02,7.540000e+02,7.584000e+02,8.057000e+02,8.089000e+02,8.858000e+02,7.686000e+02,6.879000e+02,6.893000e+02,2.887000e+02,3.143000e+02,3.224000e+02,5.318000e+02,5.864000e+02,6.516000e+02,9.177000e+02,9.457000e+02,1.016100e+03,6.972000e+02,6.137000e+02,6.806000e+02,3.746000e+02,3.997000e+02,4.133000e+02,6.241000e+02,6.792000e+02,7.486000e+02,8.033000e+02,8.310000e+02,8.752000e+02,7.811000e+02,6.931000e+02,6.986000e+02,3.579000e+02,3.930000e+02,4.225000e+02,6.607000e+02,7.173000e+02,7.872000e+02,8.285000e+02,8.381000e+02,8.818000e+02,7.913000e+02,7.015000e+02,7.149000e+02,287.600000,337.700000,342.200000,584.100000,637.400000,752.400000,790.200000,774.60000,850.700000,757.500000,665.300000,732.100000,3.076000e+02,3.087000e+02,3.286000e+02,5.884000e+02,6.205000e+02,8.615000e+02,7.973000e+02,7.847000e+02,8.631000e+02,7.477000e+02,6.711000e+02,6.958000e+02
183,Температура,ГШЫМКЕНТ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.414333e+01,2.907419e+01,2.568387e+01,2.001333e+01,1.227097e+01,3.753333e+00,1.993548e+00,2.974194e+00,3.014286e+00,1.084839e+01,1.373000e+01,1.989677e+01,2.385667e+01,2.973871e+01,2.678065e+01,1.966667e+01,1.407742e+01,3.173333e+00,3.067742e+00,-1.006452e+00,4.727586e+00,1.014839e+01,1.474333e+01,2.059355e+01,2.452333e+01,2.781935e+01,2.542258e+01,1.896667e+01,1.143871e+01,2.146667e+00,-2.748387e+00,-1.548387e-01,5.196429e+00,7.132258e+00,1.443333e+01,2.233871e+01,2.690333e+01,2.926452e+01,2.778065e+01,2.190000e+01,1.050323e+01,4.300000e+00,5.248387e+00,2.851613e+00,3.875000e+00,6.661290e+00,1.832000e+01,2.020000e+01,2.604000e+01,2.865484e+01,2.539677e+01,2.328667e+01,1.340645e+01,6.720000e+00,-1.938710e+00,-5.032258,3.796429,13.312903,15.433333,20.448387,27.523333,29.961290,25.86129,19.526667,15.087097,10.796667,2.519355,3.425806e+00,2.065517e+00,7.506452e+00,1.511000e+01,1.898065e+01,2.664667e+01,2.702903e+01,2.665806e+01,1.983333e+01,1.312258e+01,7.926667e+00,-1.200000e+00
152,Яйца,ГАЛМАТЫ,154.1,35.5000,27.600000,27.60000,29.400000,24.500000,24.500000,25.300000,24.000000,22.100000,23.50000,21.900000,89.600000,89.600000,27.400000,27.600000,31.200000,31.600000,20.000000,19.200000,19.600000,20.100000,23.400000,21.600000,89.600000,34.700000,27.400000,27.600000,31.200000,31.600000,17.800000,16.900000,17.900000,19.100000,21.900000,19.900000,89.000000,32.100000,26.900000,27.400000,22.400000,3.300000e+01,1.810000e+01,1.770000e+01,1.890000e+01,1.950000e+01,2.280000e+01,2.080000e+01,9.080000e+01,3.290000e+01,2.780000e+01,2.800000e+01,2.300000e+01,3.470000e+01,1.870000e+01,1.800000e+01,1.940000e+01,2.030000e+01,2.380000e+01,2.270000e+01,1.830000e+02,2.310000e+01,2.070000e+01,2.200000e+01,1.620000e+01,5.440000e+01,1.400000e+01,1.400000e+01,1.380000e+01,2.640000e+01,2.350000e+01,2.340000e+01,5.220000e+01,2.320000e+01,2.300000e+01,2.310000e+01,1.720000e+01,1.260000e+02,1.710000e+01,1.710000e+01,1.710000e+01,3.250000e+01,3.230000e+01,1.900000e+01,4.270000e+01,1.900000e+01,1.900000e+01,1.900000e+01,1.440000e+01,1.032000e+02,1.420000e+01,1.400000e+01,1.400000e+01,3.260000e+01,3.580000e+01,1.910000e+01,25.100000,19.100000,14.800000,18.900000,18.500000,18.400000,18.000000,17.90000,17.800000,17.600000,17.500000,17.200000,1.720000e+01,1.690000e+01,1.660000e+01,1.620000e+01,1.610000e+01,1.580000e+01,1.580000e+01,1.570000e+01,1.550000e+01,1.510000e+01,1.500000e+01,1.510000e+01
323,Осадки,МАНГИСТАУСКАЯ ОБЛАСТЬ,13.2,0.9000,2.200000,31.70000,13.700000,0.300000,3.400000,0.000000,0.000000,7.600000,31.30000,56.200000,30.600000,23.500000,57.300000,67.900000,13.500000,3.700000,8.700000,0.000000,30.900000,3.900000,21.300000,40.900000,5.400000,5.100000,44.300000,9.200000,40.400000,18.700000,12.600000,0.000000,0.300000,38.500000,12.200000,29.300000,27.000000,8.400000,13.100000,15.700000,0.000000,0.000000e+00,1.840000e+01,1.540000e+01,0.000000e+00,9.300000e+00,1.030000e+01,1.530000e+01,1.230000e+01,1.770000e+01,8.800000e+00,3.660000e+01,3.000000e+00,2.200000e+00,1.270000e+01,2.500000e+00,4.900000e+00,6.100000e+00,2.120000e+01,1.030000e+01,1.030000e+01,5.600000e+00,2.100000e+00,9.000000e+00,2.200000e+01,7.000000e-01,3.300000e+00,7.560000e+01,6.000000e-01,0.000000e+00,2.230000e+01,3.700000e+00,3.900000e+00,1.470000e+01,1.200000e+00,0.000000e+00,8.400000e+00,1.700000e+01,5.220000e+01,0.000000e+00,5.200000e+00,7.900000e+00,6.200000e+00,2.300000e+00,6.400000e+00,6.300000e+00,2.760000e+01,0.000000e+00,5.280000e+01,0.000000e+00,6.150000e+01,9.000000e-01,1.390000e+01,3.210000e+01,2.130000e+01,9.200000e+00,0.800000,18.800000,4.000000,15.000000,24.500000,2.400000,4.000000,2.50000,11.700000,13.200000,12.800000,21.700000,1.460000e+01,1.100000e+01,3.480000e+01,1.000000e+00,5.140000e+01,1.600000e+00,6.400000e+00,7.000000e-01,1.400000e+00,2.620000e+01,2.670000e+01,2.720000e+01
329,Осадки,ГШЫМКЕНТ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.420000e+01,0.000000e+00,2.200000e+00,8.000000e-01,4.360000e+01,8.530000e+01,6.720000e+01,8.050000e+01,7.430000e+01,3.010000e+01,1.384000e+02,2.380000e+01,1.400000e+01,7.000000e-01,0.000000e+00,8.500000e+00,1.000000e+01,2.430000e+01,8.810000e+01,8.170000e+01,1.035000e+02,2.860000e+01,1.025000e+02,9.830000e+01,1.900000e+00,8.000000e-01,1.170000e+01,2.900000e+00,6.282222e+01,6.780000e+01,3.010000e+01,2.270000e+01,9.130000e+01,1.620000e+02,3.670000e+01,3.360000e+01,2.100000e+00,1.200000e+00,4.000000e-01,0.000000e+00,4.580000e+01,4.300000e+01,3.810000e+01,1.079000e+02,6.540000e+01,2.312000e+02,1.290000e+01,6.740000e+01,1.090000e+01,6.000000e-01,4.500000e+00,0.000000e+00,6.470000e+01,1.269000e+02,4.450000e+01,76.000000,96.000000,55.900000,36.100000,10.300000,2.100000,7.000000,81.30000,5.700000,59.300000,66.200000,112.100000,9.380000e+01,1.040000e+02,1.278000e+02,6.780000e+01,7.720000e+01,8.500000e+00,3.520000e+01,4.000000e-01,2.900000e+00,8.430000e+01,7.200000e+01,7.980000e+01

In [5]:
# Step 1: Pivot to wide format (each indicator becomes columns of periods)
df_wide = df_eggs.pivot(index="Регион", columns="Показатель")

# Step 2: Flatten multi-level columns: ('2015-01', 'КРС') → 'КРС_2015-01'
df_wide.columns = [f"{col[1]}_{col[0]}" for col in df_wide.columns]
df_wide = df_wide.reset_index()

# Step 3: Melt: one row per region-period-indicator
df_melted = df_wide.melt(id_vars="Регион", var_name="indicator_period", value_name="value")

# Step 4: Extract 'Период' and 'Показатель' from the combined column
df_melted["Период"] = df_melted["indicator_period"].str.extract(r"_(\d{4}-\d{2})$")
df_melted["Показатель"] = df_melted["indicator_period"].str.extract(r"^(.+)_\d{4}-\d{2}")

# Step 5: Pivot again to get final modeling format: one row per region+period, one column per indicator
df_eggs = df_melted.pivot_table(index=["Регион", "Период"], columns="Показатель", values="value").reset_index()
print(df_eggs.groupby("Регион").size().reset_index(name="Количество строк"))
df_eggs

                            Регион  Количество строк
0              АКМОЛИНСКАЯ ОБЛАСТЬ               120
1              АКТЮБИНСКАЯ ОБЛАСТЬ               120
2              АЛМАТИНСКАЯ ОБЛАСТЬ               120
3               АТЫРАУСКАЯ ОБЛАСТЬ               120
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ               120
5                          ГАЛМАТЫ               120
6                          ГАСТАНА               120
7                         ГШЫМКЕНТ                79
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ               120
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ               120
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ               120
11            КОСТАНАЙСКАЯ ОБЛАСТЬ               120
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ               120
13           МАНГИСТАУСКАЯ ОБЛАСТЬ               120
14                    ОБЛАСТЬ АБАЙ                31
15                  ОБЛАСТЬ ЖЕТІСУ                31
16                  ОБЛАСТЬ ҰЛЫТАУ                31
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ               120
18            РЕСПУБЛИКА КАЗАХСТАН               120
19    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ               120
20           ТУРКЕСТАНСКАЯ ОБЛАСТЬ                79

Показатель,Регион,Период,Осадки,Поголовье: птица домашняя,Температура,Цена: Яйца,Яйца
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-01,9.8,4436655.0,-12.490323,100.600000,51667.7
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-02,9.8,4446764.0,-10.192857,88.829800,49357.2
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-03,8.3,4461524.0,-5.870968,87.053204,59105.8
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-04,8.8,4575245.0,4.490000,87.227310,61953.7
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-05,42.8,4778690.0,14.574194,69.607394,72700.2
...,...,...,...,...,...,...,...
2166,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-08,0.0,2167498.0,27.874194,483.016761,23808.0
2167,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-09,0.5,2092996.0,20.766667,489.295979,22847.1
2168,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-10,13.6,2088086.0,13.200000,530.396841,21639.9
2169,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-11,12.1,2030035.0,6.500000,546.839143,19659.4
2170,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-12,17.3,2151943.0,-1.854839,599.335701,19576.8

In [6]:
df_eggs = df_eggs[df_eggs["Регион"] != 'РЕСПУБЛИКА КАЗАХСТАН']

In [7]:
df_eggs

Показатель,Регион,Период,Осадки,Поголовье: птица домашняя,Температура,Цена: Яйца,Яйца
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-01,9.8,4436655.0,-12.490323,100.600000,51667.7
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-02,9.8,4446764.0,-10.192857,88.829800,49357.2
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-03,8.3,4461524.0,-5.870968,87.053204,59105.8
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-04,8.8,4575245.0,4.490000,87.227310,61953.7
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-05,42.8,4778690.0,14.574194,69.607394,72700.2
...,...,...,...,...,...,...,...
2166,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-08,0.0,2167498.0,27.874194,483.016761,23808.0
2167,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-09,0.5,2092996.0,20.766667,489.295979,22847.1
2168,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-10,13.6,2088086.0,13.200000,530.396841,21639.9
2169,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-11,12.1,2030035.0,6.500000,546.839143,19659.4
2170,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-12,17.3,2151943.0,-1.854839,599.335701,19576.8

In [8]:
df_eggs.to_excel("Датасет по яйцам с регрессорами.xlsx", index=False)

In [9]:
df_eggs = df_eggs.drop(columns=['Осадки', 'Поголовье: птица домашняя', 'Температура', 'Цена: Яйца'])
df_eggs.sample(10)

Показатель                          Регион   Период     Яйца
1570                 МАНГИСТАУСКАЯ ОБЛАСТЬ  2019-04    808.4
1769                  ПАВЛОДАРСКАЯ ОБЛАСТЬ  2018-02  13348.2
1632                 МАНГИСТАУСКАЯ ОБЛАСТЬ  2024-06     97.3
412                     АТЫРАУСКАЯ ОБЛАСТЬ  2019-05   9873.2
1240                КАРАГАНДИНСКАЯ ОБЛАСТЬ  2021-10  53569.9
367                     АТЫРАУСКАЯ ОБЛАСТЬ  2015-08   5694.4
1376                  КОСТАНАЙСКАЯ ОБЛАСТЬ  2023-02  32633.3
1593                 МАНГИСТАУСКАЯ ОБЛАСТЬ  2021-03     40.4
816                                ГАСТАНА  2023-01      0.2
490         ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  2015-11   9918.3

In [10]:
df_eggs.to_excel("Датасет по яйцам.xlsx", index=False)