In [1]:
# --- 1. Импорты и общие настройки ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from pmdarima import auto_arima
from statsmodels.tsa.statespace.sarimax import SARIMAX
from prophet import Prophet  # pip install prophet
from sklearn.metrics import mean_squared_error, mean_absolute_error
import warnings

warnings.filterwarnings("ignore")
# plt.style.use("seaborn-whitegrid")

In [2]:
# --- 2. Загрузка данных ---
# df должен содержать столбцы: "Регион", "Период" (YYYY-MM), и целевой столбец с показателем.
df = pd.read_excel("Датасет по КРС.xlsx")
df["Период"] = pd.to_datetime(df["Период"], format="%Y-%m")
df.sample(10)

                              Регион     Период       КРС
953                         ГШЫМКЕНТ 2023-10-01   1576.80
151              АКТЮБИНСКАЯ ОБЛАСТЬ 2017-01-01   5371.21
546   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 2018-03-01   8019.26
1417            КОСТАНАЙСКАЯ ОБЛАСТЬ 2020-02-01   6370.84
835                          ГАСТАНА 2021-02-01      5.80
521   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 2016-02-01   6672.12
1880            ПАВЛОДАРСКАЯ ОБЛАСТЬ 2017-06-01   3668.95
1022              ЖАМБЫЛСКАЯ ОБЛАСТЬ 2018-12-01  14040.98
524   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 2016-05-01   6507.33
1037              ЖАМБЫЛСКАЯ ОБЛАСТЬ 2020-03-01   3201.18

In [3]:
regions = df['Регион'].unique()
target   = "КРС"
horizon  = 3
epsilon = 1e-6

In [4]:
first_test = pd.to_datetime("2024-08-01")
last_possible = df["Период"].max() - pd.DateOffset(months=horizon-1)
test_starts = pd.date_range(first_test, last_possible, freq="MS")

## Holw-Winter's (log)

In [6]:
results_hw = []
for region in regions:
    ts = (df[df["Регион"] == region]
          .set_index("Период")[target]
          .dropna()
          .sort_index())
    if len(ts) < 24:
        print(f"{region}: всего {len(ts)} мес. — сезонный Holt-Winter's невозможен.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        # формируем train / test
        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]

        # пропускаем, если недостаточно данных или неполный test
        if len(train) < 24 or len(test) < horizon:
            continue

        # обучаем модель
        train_log = np.log1p(train)

        hw_log = ExponentialSmoothing(
            train_log,
            seasonal="add",
            seasonal_periods=12
        ).fit(optimized=True)

        # прогноз и метрики
        fc_log = hw_log.forecast(horizon)
        fc = np.expm1(fc_log) 
        # fc   = model.forecast(horizon)
        rmse = np.sqrt(mean_squared_error(test, fc))
        mae  = mean_absolute_error(test, fc)
        mape = (np.abs((test - fc) / test).mean()) * 100

        results_hw.append({
            "Регион":      region,
            "Test start":  test_start.strftime("%Y-%m"),
            "Test end":    test_end.strftime("%Y-%m"),
            "Forecast":    [x.round(2) for x in list(fc.values)],
            "Actual":      [y.round(2) for y in list(test.values)],
            "RMSE":        rmse,
            "MAE":         mae,
            "MAPE_%":      mape
        })

res_hw = pd.DataFrame(results_hw)
res_hw.to_excel("results/КРС - Результаты прогнозов ХВ.xlsx", index=False)
print("Результаты прогнозов HW на 3 месяца:")
display(res_hw)

# 4) Усреднение по всем скользящим окнам для каждого региона

final_hw = (
    res_hw
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)

final_hw.to_excel("results/КРС - Результаты прогнозов ХВ средние.xlsx", index=False)
print("Средние метрики Holt–Winter's по регионам (rolling-3):")
display(final_hw)

Результаты прогнозов HW на 3 месяца:

,Регион,Test start,Test end,Forecast,Actual,RMSE,MAE,MAPE_%
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,"[1980.04, 2804.29, 2321.35]","[2412.7, 2909.66, 2608.27]",305.843683,274.984935,10.851515
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,"[3076.09, 2544.25, 3674.98]","[2909.66, 2608.27, 3649.19]",104.023139,85.412867,2.960360
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,"[2473.4, 3573.49, 4340.85]","[2608.27, 3649.19, 4253.58]",102.529691,99.280401,3.099016
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,"[3658.88, 4443.53, 4531.06]","[3649.19, 4253.58, 3947.99]",354.091345,260.903078,6.499982
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,"[4438.89, 4526.11, 3844.21]","[4253.58, 3947.99, 3588.93]",380.234370,339.570710,8.704339
...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,"[8502.0, 9247.63, 9596.6]","[8467.16, 8032.34, 8225.02]",1058.203455,873.904563,10.739061
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,"[9238.26, 9587.77, 9462.39]","[8032.34, 8225.02, 6628.3]",1944.511972,1800.918886,24.779676
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,"[9325.64, 9208.63, 8660.17]","[8225.02, 6628.3, 7697.58]",1712.312864,1547.847665,21.605160
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,"[8541.04, 8046.88, 9217.04]","[6628.3, 7697.58, 9167.36]",1122.950713,770.574648,11.312311
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,"[8184.3, 9441.33, 7882.08]","[7697.58, 9167.36, 8580.29]",516.221008,486.300889,5.816322

Средние метрики Holt–Winter's по регионам (rolling-3):

                            Регион     RMSE      MAE  MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ   229.47   193.56    5.59
1              АКТЮБИНСКАЯ ОБЛАСТЬ   319.78   243.58    4.65
2              АЛМАТИНСКАЯ ОБЛАСТЬ   903.49   750.00   10.36
3               АТЫРАУСКАЯ ОБЛАСТЬ   142.42   126.22    6.33
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   388.38   318.35    7.59
5                          ГАЛМАТЫ    11.11     8.56     NaN
6                          ГАСТАНА     0.32     0.29   13.02
7                         ГШЫМКЕНТ   183.50   164.10   35.63
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ   746.60   597.03   13.97
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   233.15   188.09    4.54
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ   121.84   102.56    3.69
11            КОСТАНАЙСКАЯ ОБЛАСТЬ   451.46   394.44   12.74
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ   172.81   135.73    8.25
13           МАНГИСТАУСКАЯ ОБЛАСТЬ    63.19    48.95   26.67
14                    ОБЛАСТЬ АБАЙ   725.63   581.70   13.01
15                  ОБЛАСТЬ ЖЕТІСУ   925.92   820.56   14.94
16                  ОБЛАСТЬ ҰЛЫТАУ   160.16   136.55   23.12
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ   674.73   601.50   14.97
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   228.81   170.82    6.26
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ  3546.60  2420.04   16.20

## SARIMA

In [7]:
results_sarima = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    ts = ts + epsilon
    ts_log = np.log(ts)

    if len(ts_log) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. для авто-ARIMA, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train_log = ts_log[ts_log.index < test_start]
        test_log  = ts_log[(ts_log.index >= test_start) & (ts_log.index <= test_end)]
        if len(train_log) < 12 + horizon or len(test_log) < horizon:
            continue

        # автоподбор на лог-данных
        use_seasonal = len(train_log) >= 2 * 12

        sarima_log = auto_arima(
            train_log,
            seasonal=use_seasonal,
            m=12 if use_seasonal else 1,
            D=1 if use_seasonal else 0,      # фиксируем порядок сезонной разности
            seasonal_test=None,               # пропустить nsdiffs
            boxcox=True,
            stepwise=True,
            suppress_warnings=True,
            error_action="ignore"
        )
      
        # прогноз в лог-шкале
        fc_log = sarima_log.predict(n_periods=horizon, return_conf_int=False)

        # возвращаем прогноз в исходные единицы
        fc = np.exp(fc_log) - epsilon
        actual = np.exp(test_log.values) - epsilon  # но exp(log(x)) == x

        # метрики на исходном уровне
        rmse = np.sqrt(mean_squared_error(actual, fc))
        mae  = mean_absolute_error(actual, fc)
        mape = (np.abs((actual - fc) / actual).mean()) * 100

        results_sarima.append({
            "Регион":         region,
            "Test start":     test_start.strftime("%Y-%m"),
            "Test end":       test_end.strftime("%Y-%m"),
            "order":          sarima_log.order,
            "seasonal_order": sarima_log.seasonal_order,
            "RMSE":           round(rmse,2),
            "MAE":            round(mae,2),
            "MAPE_%":         round(mape,2),
            "Forecast":       [round(x,2) for x in fc],
            "Actual":         [round(y,2) for y in actual]
        })
# формируем DataFrame с результатами
res_sarima = pd.DataFrame(results_sarima)
res_sarima.to_excel("results/КРС - Результаты прогнозов SARIMA.xlsx", index=False)
print("Результаты прогнозов SARIMA на 3 месяца:")

display(res_sarima)

final_sarima = (
    res_sarima
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_sarima.to_excel("results/КРС - Результаты прогнозов SARIMA средние.xlsx", index=False)
print("Средние метрики SARIMA по регионам (rolling-3):")
display(final_sarima)

Результаты прогнозов SARIMA на 3 месяца:

,Регион,Test start,Test end,order,seasonal_order,RMSE,MAE,MAPE_%,Forecast,Actual
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,"(3, 0, 3)","(0, 1, 1, 12)",289.77,274.47,10.70,"[2014.14, 2734.59, 2358.48]","[2412.7, 2909.66, 2608.27]"
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,"(1, 0, 2)","(0, 1, 1, 12)",153.47,111.22,3.88,"[3167.53, 2545.04, 3636.62]","[2909.66, 2608.27, 3649.19]"
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,"(1, 0, 2)","(0, 1, 1, 12)",109.09,86.37,2.97,"[2443.09, 3557.47, 4255.77]","[2608.27, 3649.19, 4253.58]"
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,"(1, 0, 2)","(0, 1, 1, 12)",243.82,146.11,3.70,"[3653.92, 4265.06, 4370.11]","[3649.19, 4253.58, 3947.99]"
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,"(1, 0, 2)","(0, 1, 1, 12)",254.87,186.87,4.83,"[4264.81, 4370.73, 3715.55]","[4253.58, 3947.99, 3588.93]"
...,...,...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,"(1, 0, 1)","(0, 1, 1, 12)",1447.32,1071.21,13.17,"[7692.32, 10415.78, 8280.36]","[8467.16, 8032.34, 8225.02]"
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,"(2, 0, 2)","(0, 1, 1, 12)",2135.61,1795.83,25.00,"[10129.44, 7971.11, 9664.77]","[8032.34, 8225.02, 6628.3]"
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,"(0, 0, 0)","(0, 1, 1, 12)",1322.41,920.53,13.43,"[7861.03, 8885.31, 7557.0]","[8225.02, 6628.3, 7697.58]"
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,"(0, 0, 0)","(0, 1, 1, 12)",1383.32,1064.74,14.82,"[8870.85, 7581.47, 10002.93]","[6628.3, 7697.58, 9167.36]"
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,"(0, 0, 0)","(0, 1, 1, 12)",856.71,701.82,8.03,"[7618.92, 9914.57, 7300.7]","[7697.58, 9167.36, 8580.29]"

Средние метрики SARIMA по регионам (rolling-3):

                            Регион     RMSE      MAE        MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ   195.14   156.50  4.670000e+00
1              АКТЮБИНСКАЯ ОБЛАСТЬ   440.52   362.00  6.460000e+00
2              АЛМАТИНСКАЯ ОБЛАСТЬ   645.16   469.63  5.710000e+00
3               АТЫРАУСКАЯ ОБЛАСТЬ   143.89   132.20  6.660000e+00
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   319.08   260.70  6.530000e+00
5                          ГАЛМАТЫ    10.45     7.86  2.286067e+22
6                          ГАСТАНА     0.29     0.26  1.114000e+01
7                         ГШЫМКЕНТ   252.34   178.60  3.761000e+01
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ   712.59   521.48  1.155000e+01
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   243.21   194.85  4.250000e+00
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ   169.02   150.64  5.620000e+00
11            КОСТАНАЙСКАЯ ОБЛАСТЬ   434.12   350.90  1.168000e+01
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ   295.10   220.04  1.239000e+01
13           МАНГИСТАУСКАЯ ОБЛАСТЬ    32.32    20.85  4.321000e+01
14                    ОБЛАСТЬ АБАЙ   659.85   548.97  1.321000e+01
15                  ОБЛАСТЬ ЖЕТІСУ  1973.46  1753.38  3.085000e+01
16                  ОБЛАСТЬ ҰЛЫТАУ    95.17    85.27  1.724000e+01
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ   494.40   430.62  1.115000e+01
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   196.45   150.04  5.990000e+00
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ  3630.81  2473.98  1.674000e+01

## Facebook Prophet

In [8]:
results_prophet = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    if len(ts) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. данных, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]
        if len(train) < 12 + horizon or len(test) < horizon:
            continue

        # Подготовка данных для Prophet
#         df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
# # подготовка для одного региона
        df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
        df_prophet["y"] = np.log(df_prophet["y"] + epsilon)

        m = Prophet()
        m.fit(df_prophet)

        future = m.make_future_dataframe(periods=horizon, freq="MS")
        forecast = m.predict(future)

        # берем только прогнозные точки
        yhat_log = forecast["yhat"].values[-horizon:]
        fc = np.exp(yhat_log) - epsilon

        # m = Prophet()
        # m.fit(df_prophet)

        # # Создаем DataFrame будущих дат и делаем прогноз
        # # future = m.make_future_dataframe(periods=horizon, freq="MS")
        # # forecast = m.predict(future)

        # # Отбираем только наши горизонты
        # fc = forecast.set_index("ds")["yhat"].loc[test.index].values
        actual = test.values

        # Расчет метрик
        rmse  = np.sqrt(mean_squared_error(actual, fc))
        mae   = mean_absolute_error(actual, fc)
        mape  = (np.abs((actual - fc) / actual).mean()) * 100

        results_prophet.append({
            "Регион":     region,
            "Test start": test_start.strftime("%Y-%m"),
            "Test end":   test_end.strftime("%Y-%m"),
            "RMSE":       round(rmse, 2),
            "MAE":        round(mae, 2),
            "MAPE_%":     round(mape, 2),
            "Forecast":   [round(x, 2) for x in fc],
            "Actual":     [round(x, 2) for x in actual]
        })

# Собираем результаты в DataFrame
res_prophet = pd.DataFrame(results_prophet)
res_prophet.to_excel("results/КРС - Результаты прогнозов Prophet.xlsx", index=False)
print("Результаты прогнозов Prophet на 3 месяца:")
display(res_prophet)

final_prophet = (
    res_prophet
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_prophet.to_excel("results/КРС - Результаты прогнозов Prophet средние.xlsx", index=False)
print("Средние метрики Prophet по регионам (rolling-3):")
display(final_prophet)

14:30:54 - cmdstanpy - INFO - Chain [1] start processing
14:30:55 - cmdstanpy - INFO - Chain [1] done processing
14:30:56 - cmdstanpy - INFO - Chain [1] start processing
14:30:56 - cmdstanpy - INFO - Chain [1] done processing
14:30:56 - cmdstanpy - INFO - Chain [1] start processing
14:30:56 - cmdstanpy - INFO - Chain [1] done processing
14:30:57 - cmdstanpy - INFO - Chain [1] start processing
14:30:57 - cmdstanpy - INFO - Chain [1] done processing
14:30:57 - cmdstanpy - INFO - Chain [1] start processing
14:30:57 - cmdstanpy - INFO - Chain [1] done processing
14:30:58 - cmdstanpy - INFO - Chain [1] start processing
14:30:58 - cmdstanpy - INFO - Chain [1] done processing
14:30:58 - cmdstanpy - INFO - Chain [1] start processing
14:30:58 - cmdstanpy - INFO - Chain [1] done processing
14:30:58 - cmdstanpy - INFO - Chain [1] start processing
14:30:59 - cmdstanpy - INFO - Chain [1] done processing
14:30:59 - cmdstanpy - INFO - Chain [1] start processing
14:30:59 - cmdstanpy - INFO - Chain [1] done processing
14:30:59 - cmdstanpy - INFO - Chain [1] start processing
14:30:59 - cmdstanpy - INFO - Chain [1] done processing
14:31:00 - cmdstanpy - INFO - Chain [1] start processing
14:31:00 - cmdstanpy - INFO - Chain [1] done processing
14:31:00 - cmdstanpy - INFO - Chain [1] start processing
14:31:00 - cmdstanpy - INFO - Chain [1] done processing
14:31:01 - cmdstanpy - INFO - Chain [1] start processing
14:31:01 - cmdstanpy - INFO - Chain [1] done processing
14:31:01 - cmdstanpy - INFO - Chain [1] start processing
14:31:01 - cmdstanpy - INFO - Chain [1] done processing
14:31:02 - cmdstanpy - INFO - Chain [1] start processing
14:31:02 - cmdstanpy - INFO - Chain [1] done processing
14:31:02 - cmdstanpy - INFO - Chain [1] start processing
14:31:02 - cmdstanpy - INFO - Chain [1] done processing
14:31:03 - cmdstanpy - INFO - Chain [1] start processing
14:31:03 - cmdstanpy - INFO - Chain [1] done processing
14:31:03 - cmdstanpy - INFO - Chain [1] start processing
14:31:03 - cmdstanpy - INFO - Chain [1] done processing
14:31:03 - cmdstanpy - INFO - Chain [1] start processing
14:31:03 - cmdstanpy - INFO - Chain [1] done processing
14:31:04 - cmdstanpy - INFO - Chain [1] start processing
14:31:04 - cmdstanpy - INFO - Chain [1] done processing
14:31:04 - cmdstanpy - INFO - Chain [1] start processing
14:31:04 - cmdstanpy - INFO - Chain [1] done processing
14:31:04 - cmdstanpy - INFO - Chain [1] start processing
14:31:04 - cmdstanpy - INFO - Chain [1] done processing
14:31:05 - cmdstanpy - INFO - Chain [1] start processing
14:31:05 - cmdstanpy - INFO - Chain [1] done processing
14:31:05 - cmdstanpy - INFO - Chain [1] start processing
14:31:05 - cmdstanpy - INFO - Chain [1] done processing
14:31:05 - cmdstanpy - INFO - Chain [1] start processing
14:31:05 - cmdstanpy - INFO - Chain [1] done processing
14:31:06 - cmdstanpy - INFO - Chain [1] start processing
14:31:06 - cmdstanpy - INFO - Chain [1] done processing
14:31:06 - cmdstanpy - INFO - Chain [1] start processing
14:31:06 - cmdstanpy - INFO - Chain [1] done processing
14:31:07 - cmdstanpy - INFO - Chain [1] start processing
14:31:07 - cmdstanpy - INFO - Chain [1] done processing
14:31:07 - cmdstanpy - INFO - Chain [1] start processing
14:31:07 - cmdstanpy - INFO - Chain [1] done processing
14:31:07 - cmdstanpy - INFO - Chain [1] start processing
14:31:07 - cmdstanpy - INFO - Chain [1] done processing
14:31:08 - cmdstanpy - INFO - Chain [1] start processing
14:31:08 - cmdstanpy - INFO - Chain [1] done processing
14:31:09 - cmdstanpy - INFO - Chain [1] start processing
14:31:09 - cmdstanpy - INFO - Chain [1] done processing
14:31:09 - cmdstanpy - INFO - Chain [1] start processing
14:31:09 - cmdstanpy - INFO - Chain [1] done processing
14:31:10 - cmdstanpy - INFO - Chain [1] start processing
14:31:10 - cmdstanpy - INFO - Chain [1] done processing
14:31:10 - cmdstanpy - INFO - Chain [1] start processing
14:31:10 - cmdstanpy - INFO - Chain [1] done processing
14:31:11 - cmdstanpy - INFO - Chain [1] start processing
14:31:11 - cmdstanpy - INFO - Chain [1] done processing
14:31:11 - cmdstanpy - INFO - Chain [1] start processing
14:31:11 - cmdstanpy - INFO - Chain [1] done processing
14:31:12 - cmdstanpy - INFO - Chain [1] start processing
14:31:12 - cmdstanpy - INFO - Chain [1] done processing
14:31:12 - cmdstanpy - INFO - Chain [1] start processing
14:31:12 - cmdstanpy - INFO - Chain [1] done processing
14:31:13 - cmdstanpy - INFO - Chain [1] start processing
14:31:13 - cmdstanpy - INFO - Chain [1] done processing
14:31:13 - cmdstanpy - INFO - Chain [1] start processing
14:31:13 - cmdstanpy - INFO - Chain [1] done processing
14:31:14 - cmdstanpy - INFO - Chain [1] start processing
14:31:14 - cmdstanpy - INFO - Chain [1] done processing
14:31:14 - cmdstanpy - INFO - Chain [1] start processing
14:31:14 - cmdstanpy - INFO - Chain [1] done processing
14:31:15 - cmdstanpy - INFO - Chain [1] start processing
14:31:15 - cmdstanpy - INFO - Chain [1] done processing
14:31:15 - cmdstanpy - INFO - Chain [1] start processing
14:31:15 - cmdstanpy - INFO - Chain [1] done processing
14:31:16 - cmdstanpy - INFO - Chain [1] start processing
14:31:16 - cmdstanpy - INFO - Chain [1] done processing
14:31:16 - cmdstanpy - INFO - Chain [1] start processing
14:31:17 - cmdstanpy - INFO - Chain [1] done processing
14:31:17 - cmdstanpy - INFO - Chain [1] start processing
14:31:17 - cmdstanpy - INFO - Chain [1] done processing
14:31:18 - cmdstanpy - INFO - Chain [1] start processing
14:31:18 - cmdstanpy - INFO - Chain [1] done processing
14:31:18 - cmdstanpy - INFO - Chain [1] start processing
14:31:19 - cmdstanpy - INFO - Chain [1] done processing
14:31:19 - cmdstanpy - INFO - Chain [1] start processing
14:31:19 - cmdstanpy - INFO - Chain [1] done processing
14:31:20 - cmdstanpy - INFO - Chain [1] start processing
14:31:20 - cmdstanpy - INFO - Chain [1] done processing
14:31:20 - cmdstanpy - INFO - Chain [1] start processing
14:31:20 - cmdstanpy - INFO - Chain [1] done processing
14:31:21 - cmdstanpy - INFO - Chain [1] start processing
14:31:21 - cmdstanpy - INFO - Chain [1] done processing
14:31:22 - cmdstanpy - INFO - Chain [1] start processing
14:31:22 - cmdstanpy - INFO - Chain [1] done processing
14:31:22 - cmdstanpy - INFO - Chain [1] start processing
14:31:22 - cmdstanpy - INFO - Chain [1] done processing
14:31:23 - cmdstanpy - INFO - Chain [1] start processing
14:31:23 - cmdstanpy - INFO - Chain [1] done processing
14:31:24 - cmdstanpy - INFO - Chain [1] start processing
14:31:24 - cmdstanpy - INFO - Chain [1] done processing
14:31:24 - cmdstanpy - INFO - Chain [1] start processing
14:31:24 - cmdstanpy - INFO - Chain [1] done processing
14:31:25 - cmdstanpy - INFO - Chain [1] start processing
14:31:25 - cmdstanpy - INFO - Chain [1] done processing
14:31:26 - cmdstanpy - INFO - Chain [1] start processing
14:31:26 - cmdstanpy - INFO - Chain [1] done processing
14:31:26 - cmdstanpy - INFO - Chain [1] start processing
14:31:26 - cmdstanpy - INFO - Chain [1] done processing
14:31:27 - cmdstanpy - INFO - Chain [1] start processing
14:31:27 - cmdstanpy - INFO - Chain [1] done processing
14:31:27 - cmdstanpy - INFO - Chain [1] start processing
14:31:28 - cmdstanpy - INFO - Chain [1] done processing
14:31:28 - cmdstanpy - INFO - Chain [1] start processing
14:31:28 - cmdstanpy - INFO - Chain [1] done processing
14:31:29 - cmdstanpy - INFO - Chain [1] start processing
14:31:29 - cmdstanpy - INFO - Chain [1] done processing
14:31:29 - cmdstanpy - INFO - Chain [1] start processing
14:31:30 - cmdstanpy - INFO - Chain [1] done processing
14:31:30 - cmdstanpy - INFO - Chain [1] start processing
14:31:30 - cmdstanpy - INFO - Chain [1] done processing
14:31:31 - cmdstanpy - INFO - Chain [1] start processing
14:31:31 - cmdstanpy - INFO - Chain [1] done processing
14:31:31 - cmdstanpy - INFO - Chain [1] start processing
14:31:31 - cmdstanpy - INFO - Chain [1] done processing
14:31:32 - cmdstanpy - INFO - Chain [1] start processing
14:31:33 - cmdstanpy - INFO - Chain [1] done processing
14:31:33 - cmdstanpy - INFO - Chain [1] start processing
14:31:34 - cmdstanpy - INFO - Chain [1] done processing
14:31:34 - cmdstanpy - INFO - Chain [1] start processing
14:31:35 - cmdstanpy - INFO - Chain [1] done processing
14:31:35 - cmdstanpy - INFO - Chain [1] start processing
14:31:36 - cmdstanpy - INFO - Chain [1] done processing
14:31:36 - cmdstanpy - INFO - Chain [1] start processing
14:31:36 - cmdstanpy - INFO - Chain [1] done processing
14:31:37 - cmdstanpy - INFO - Chain [1] start processing
14:31:37 - cmdstanpy - INFO - Chain [1] done processing
14:31:37 - cmdstanpy - INFO - Chain [1] start processing
14:31:38 - cmdstanpy - INFO - Chain [1] done processing
14:31:38 - cmdstanpy - INFO - Chain [1] start processing
14:31:38 - cmdstanpy - INFO - Chain [1] done processing
14:31:39 - cmdstanpy - INFO - Chain [1] start processing
14:31:39 - cmdstanpy - INFO - Chain [1] done processing
14:31:39 - cmdstanpy - INFO - Chain [1] start processing
14:31:40 - cmdstanpy - INFO - Chain [1] done processing
14:31:40 - cmdstanpy - INFO - Chain [1] start processing
14:31:40 - cmdstanpy - INFO - Chain [1] done processing
14:31:40 - cmdstanpy - INFO - Chain [1] start processing
14:31:40 - cmdstanpy - INFO - Chain [1] done processing
14:31:41 - cmdstanpy - INFO - Chain [1] start processing
14:31:41 - cmdstanpy - INFO - Chain [1] done processing
14:31:41 - cmdstanpy - INFO - Chain [1] start processing
14:31:41 - cmdstanpy - INFO - Chain [1] done processing
14:31:42 - cmdstanpy - INFO - Chain [1] start processing
14:31:42 - cmdstanpy - INFO - Chain [1] done processing
14:31:42 - cmdstanpy - INFO - Chain [1] start processing
14:31:42 - cmdstanpy - INFO - Chain [1] done processing
14:31:42 - cmdstanpy - INFO - Chain [1] start processing
14:31:42 - cmdstanpy - INFO - Chain [1] done processing
14:31:43 - cmdstanpy - INFO - Chain [1] start processing
14:31:43 - cmdstanpy - INFO - Chain [1] done processing
14:31:43 - cmdstanpy - INFO - Chain [1] start processing
14:31:43 - cmdstanpy - INFO - Chain [1] done processing
14:31:44 - cmdstanpy - INFO - Chain [1] start processing
14:31:44 - cmdstanpy - INFO - Chain [1] done processing
14:31:44 - cmdstanpy - INFO - Chain [1] start processing
14:31:44 - cmdstanpy - INFO - Chain [1] done processing
14:31:45 - cmdstanpy - INFO - Chain [1] start processing
14:31:45 - cmdstanpy - INFO - Chain [1] done processing
14:31:45 - cmdstanpy - INFO - Chain [1] start processing
14:31:45 - cmdstanpy - INFO - Chain [1] done processing
14:31:45 - cmdstanpy - INFO - Chain [1] start processing
14:31:46 - cmdstanpy - INFO - Chain [1] done processing
14:31:46 - cmdstanpy - INFO - Chain [1] start processing
14:31:46 - cmdstanpy - INFO - Chain [1] done processing
14:31:47 - cmdstanpy - INFO - Chain [1] start processing
14:31:47 - cmdstanpy - INFO - Chain [1] done processing
14:31:48 - cmdstanpy - INFO - Chain [1] start processing
14:31:48 - cmdstanpy - INFO - Chain [1] done processing
14:31:48 - cmdstanpy - INFO - Chain [1] start processing
14:31:48 - cmdstanpy - INFO - Chain [1] done processing
14:31:49 - cmdstanpy - INFO - Chain [1] start processing
14:31:49 - cmdstanpy - INFO - Chain [1] done processing
14:31:50 - cmdstanpy - INFO - Chain [1] start processing
14:31:50 - cmdstanpy - INFO - Chain [1] done processing
14:31:50 - cmdstanpy - INFO - Chain [1] start processing
14:31:50 - cmdstanpy - INFO - Chain [1] done processing
14:31:51 - cmdstanpy - INFO - Chain [1] start processing
14:31:51 - cmdstanpy - INFO - Chain [1] done processing
14:31:51 - cmdstanpy - INFO - Chain [1] start processing
14:31:52 - cmdstanpy - INFO - Chain [1] done processing
14:31:52 - cmdstanpy - INFO - Chain [1] start processing
14:31:52 - cmdstanpy - INFO - Chain [1] done processing
14:31:53 - cmdstanpy - INFO - Chain [1] start processing
14:31:53 - cmdstanpy - INFO - Chain [1] done processing
14:31:54 - cmdstanpy - INFO - Chain [1] start processing
14:31:54 - cmdstanpy - INFO - Chain [1] done processing
14:31:54 - cmdstanpy - INFO - Chain [1] start processing
14:31:54 - cmdstanpy - INFO - Chain [1] done processing
14:31:55 - cmdstanpy - INFO - Chain [1] start processing
14:31:55 - cmdstanpy - INFO - Chain [1] done processing
14:31:56 - cmdstanpy - INFO - Chain [1] start processing
14:31:56 - cmdstanpy - INFO - Chain [1] done processing
14:31:56 - cmdstanpy - INFO - Chain [1] start processing
14:31:57 - cmdstanpy - INFO - Chain [1] done processing
14:31:57 - cmdstanpy - INFO - Chain [1] start processing
14:31:57 - cmdstanpy - INFO - Chain [1] done processing
14:31:58 - cmdstanpy - INFO - Chain [1] start processing
14:31:58 - cmdstanpy - INFO - Chain [1] done processing
14:31:58 - cmdstanpy - INFO - Chain [1] start processing
14:31:58 - cmdstanpy - INFO - Chain [1] done processing
14:31:59 - cmdstanpy - INFO - Chain [1] start processing
14:31:59 - cmdstanpy - INFO - Chain [1] done processing
14:32:00 - cmdstanpy - INFO - Chain [1] start processing
14:32:00 - cmdstanpy - INFO - Chain [1] done processing
14:32:00 - cmdstanpy - INFO - Chain [1] start processing
14:32:00 - cmdstanpy - INFO - Chain [1] done processing
14:32:01 - cmdstanpy - INFO - Chain [1] start processing
14:32:01 - cmdstanpy - INFO - Chain [1] done processing
14:32:02 - cmdstanpy - INFO - Chain [1] start processing
14:32:02 - cmdstanpy - INFO - Chain [1] done processing
14:32:02 - cmdstanpy - INFO - Chain [1] start processing
14:32:02 - cmdstanpy - INFO - Chain [1] done processing
14:32:03 - cmdstanpy - INFO - Chain [1] start processing
14:32:03 - cmdstanpy - INFO - Chain [1] done processing
14:32:04 - cmdstanpy - INFO - Chain [1] start processing
14:32:04 - cmdstanpy - INFO - Chain [1] done processing
14:32:04 - cmdstanpy - INFO - Chain [1] start processing
14:32:05 - cmdstanpy - INFO - Chain [1] done processing
14:32:05 - cmdstanpy - INFO - Chain [1] start processing
14:32:05 - cmdstanpy - INFO - Chain [1] done processing
14:32:06 - cmdstanpy - INFO - Chain [1] start processing
14:32:06 - cmdstanpy - INFO - Chain [1] done processing
14:32:06 - cmdstanpy - INFO - Chain [1] start processing
14:32:06 - cmdstanpy - INFO - Chain [1] done processing
14:32:06 - cmdstanpy - INFO - Chain [1] start processing
14:32:06 - cmdstanpy - INFO - Chain [1] done processing
14:32:07 - cmdstanpy - INFO - Chain [1] start processing
14:32:07 - cmdstanpy - INFO - Chain [1] done processing
14:32:07 - cmdstanpy - INFO - Chain [1] start processing
14:32:07 - cmdstanpy - INFO - Chain [1] done processing
14:32:07 - cmdstanpy - INFO - Chain [1] start processing
14:32:08 - cmdstanpy - INFO - Chain [1] done processing
14:32:08 - cmdstanpy - INFO - Chain [1] start processing
14:32:08 - cmdstanpy - INFO - Chain [1] done processing
14:32:08 - cmdstanpy - INFO - Chain [1] start processing
14:32:08 - cmdstanpy - INFO - Chain [1] done processing
14:32:09 - cmdstanpy - INFO - Chain [1] start processing
14:32:09 - cmdstanpy - INFO - Chain [1] done processing
14:32:09 - cmdstanpy - INFO - Chain [1] start processing
14:32:09 - cmdstanpy - INFO - Chain [1] done processing
14:32:10 - cmdstanpy - INFO - Chain [1] start processing
14:32:10 - cmdstanpy - INFO - Chain [1] done processing
14:32:10 - cmdstanpy - INFO - Chain [1] start processing
14:32:10 - cmdstanpy - INFO - Chain [1] done processing
14:32:10 - cmdstanpy - INFO - Chain [1] start processing
14:32:11 - cmdstanpy - INFO - Chain [1] done processing
14:32:11 - cmdstanpy - INFO - Chain [1] start processing
14:32:11 - cmdstanpy - INFO - Chain [1] done processing
14:32:11 - cmdstanpy - INFO - Chain [1] start processing
14:32:11 - cmdstanpy - INFO - Chain [1] done processing
14:32:12 - cmdstanpy - INFO - Chain [1] start processing
14:32:12 - cmdstanpy - INFO - Chain [1] done processing
14:32:12 - cmdstanpy - INFO - Chain [1] start processing
14:32:12 - cmdstanpy - INFO - Chain [1] done processing
14:32:13 - cmdstanpy - INFO - Chain [1] start processing
14:32:31 - cmdstanpy - INFO - Chain [1] done processing
14:32:31 - cmdstanpy - INFO - Chain [1] start processing
14:32:50 - cmdstanpy - INFO - Chain [1] done processing
14:32:50 - cmdstanpy - INFO - Chain [1] start processing
14:32:51 - cmdstanpy - INFO - Chain [1] done processing
14:32:51 - cmdstanpy - INFO - Chain [1] start processing
14:32:51 - cmdstanpy - INFO - Chain [1] done processing
14:32:51 - cmdstanpy - INFO - Chain [1] start processing
14:32:52 - cmdstanpy - INFO - Chain [1] done processing
14:32:52 - cmdstanpy - INFO - Chain [1] start processing
14:32:52 - cmdstanpy - INFO - Chain [1] done processing
14:32:53 - cmdstanpy - INFO - Chain [1] start processing
14:32:53 - cmdstanpy - INFO - Chain [1] done processing
14:32:53 - cmdstanpy - INFO - Chain [1] start processing
14:32:54 - cmdstanpy - INFO - Chain [1] done processing
14:32:54 - cmdstanpy - INFO - Chain [1] start processing
14:32:55 - cmdstanpy - INFO - Chain [1] done processing
14:32:55 - cmdstanpy - INFO - Chain [1] start processing
14:32:55 - cmdstanpy - INFO - Chain [1] done processing
14:32:56 - cmdstanpy - INFO - Chain [1] start processing
14:32:56 - cmdstanpy - INFO - Chain [1] done processing
14:32:56 - cmdstanpy - INFO - Chain [1] start processing
14:32:56 - cmdstanpy - INFO - Chain [1] done processing
14:32:57 - cmdstanpy - INFO - Chain [1] start processing
14:32:57 - cmdstanpy - INFO - Chain [1] done processing
14:32:57 - cmdstanpy - INFO - Chain [1] start processing
14:32:58 - cmdstanpy - INFO - Chain [1] done processing
14:32:58 - cmdstanpy - INFO - Chain [1] start processing
14:32:58 - cmdstanpy - INFO - Chain [1] done processing
14:32:59 - cmdstanpy - INFO - Chain [1] start processing
14:32:59 - cmdstanpy - INFO - Chain [1] done processing
14:32:59 - cmdstanpy - INFO - Chain [1] start processing
14:33:00 - cmdstanpy - INFO - Chain [1] done processing
14:33:00 - cmdstanpy - INFO - Chain [1] start processing
14:33:00 - cmdstanpy - INFO - Chain [1] done processing
14:33:00 - cmdstanpy - INFO - Chain [1] start processing
14:33:01 - cmdstanpy - INFO - Chain [1] done processing
14:33:01 - cmdstanpy - INFO - Chain [1] start processing
14:33:01 - cmdstanpy - INFO - Chain [1] done processing
14:33:02 - cmdstanpy - INFO - Chain [1] start processing
14:33:02 - cmdstanpy - INFO - Chain [1] done processing
14:33:03 - cmdstanpy - INFO - Chain [1] start processing
14:33:03 - cmdstanpy - INFO - Chain [1] done processing
14:33:03 - cmdstanpy - INFO - Chain [1] start processing
14:33:03 - cmdstanpy - INFO - Chain [1] done processing
14:33:04 - cmdstanpy - INFO - Chain [1] start processing
14:33:04 - cmdstanpy - INFO - Chain [1] done processing
14:33:04 - cmdstanpy - INFO - Chain [1] start processing
14:33:05 - cmdstanpy - INFO - Chain [1] done processing
14:33:05 - cmdstanpy - INFO - Chain [1] start processing
14:33:05 - cmdstanpy - INFO - Chain [1] done processing
14:33:05 - cmdstanpy - INFO - Chain [1] start processing
14:33:06 - cmdstanpy - INFO - Chain [1] done processing
14:33:06 - cmdstanpy - INFO - Chain [1] start processing
14:33:06 - cmdstanpy - INFO - Chain [1] done processing
14:33:07 - cmdstanpy - INFO - Chain [1] start processing
14:33:07 - cmdstanpy - INFO - Chain [1] done processing
14:33:07 - cmdstanpy - INFO - Chain [1] start processing
14:33:08 - cmdstanpy - INFO - Chain [1] done processing
14:33:08 - cmdstanpy - INFO - Chain [1] start processing
14:33:08 - cmdstanpy - INFO - Chain [1] done processing
14:33:08 - cmdstanpy - INFO - Chain [1] start processing
14:33:08 - cmdstanpy - INFO - Chain [1] done processing
14:33:09 - cmdstanpy - INFO - Chain [1] start processing
14:33:09 - cmdstanpy - INFO - Chain [1] done processing
14:33:09 - cmdstanpy - INFO - Chain [1] start processing
14:33:09 - cmdstanpy - INFO - Chain [1] done processing
14:33:10 - cmdstanpy - INFO - Chain [1] start processing
14:33:10 - cmdstanpy - INFO - Chain [1] done processing
14:33:10 - cmdstanpy - INFO - Chain [1] start processing
14:33:10 - cmdstanpy - INFO - Chain [1] done processing
14:33:11 - cmdstanpy - INFO - Chain [1] start processing

Результаты прогнозов Prophet на 3 месяца:

,Регион,Test start,Test end,RMSE,MAE,MAPE_%,Forecast,Actual
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,511.26,495.42,19.22,"[1759.78, 2565.87, 2118.73]","[2412.7, 2909.66, 2608.27]"
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,420.06,407.86,13.38,"[2633.93, 2179.81, 3129.8]","[2909.66, 2608.27, 3649.19]"
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,459.04,457.81,13.46,"[2193.67, 3152.81, 3791.12]","[2608.27, 3649.19, 4253.58]"
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,356.61,297.23,7.60,"[3188.29, 3842.87, 3968.08]","[3649.19, 4253.58, 3947.99]"
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,226.80,195.88,4.87,"[3899.86, 4034.64, 3441.66]","[4253.58, 3947.99, 3588.93]"
...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,1292.37,1172.37,14.26,"[9160.92, 8922.62, 10158.1]","[8467.16, 8032.34, 8225.02]"
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,2397.91,2132.63,29.50,"[8937.81, 10150.69, 10195.06]","[8032.34, 8225.02, 6628.3]"
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,2440.76,2311.20,31.92,"[10017.97, 10048.36, 9418.15]","[8225.02, 6628.3, 7697.58]"
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,2237.45,2127.17,28.21,"[9594.08, 8964.37, 11316.3]","[6628.3, 7697.58, 9167.36]"
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,993.98,892.80,10.38,"[8467.39, 10646.06, 8150.39]","[7697.58, 9167.36, 8580.29]"

Средние метрики Prophet по регионам (rolling-3):

                            Регион     RMSE      MAE  MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ   318.48   289.78    8.62
1              АКТЮБИНСКАЯ ОБЛАСТЬ   527.97   462.49    8.93
2              АЛМАТИНСКАЯ ОБЛАСТЬ  1325.38  1131.20   15.36
3               АТЫРАУСКАЯ ОБЛАСТЬ   383.52   348.61   15.71
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   594.72   540.54   12.76
5                          ГАЛМАТЫ    11.13     8.34     NaN
6                          ГАСТАНА     0.45     0.38   16.69
7                         ГШЫМКЕНТ   184.02   164.59   33.20
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ  1268.03   894.39   13.19
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   205.36   162.47    4.02
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ   596.79   537.56   14.75
11            КОСТАНАЙСКАЯ ОБЛАСТЬ   349.58   282.55    9.93
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ   190.06   157.73    9.06
13           МАНГИСТАУСКАЯ ОБЛАСТЬ   141.49    99.49   55.99
14                    ОБЛАСТЬ АБАЙ  1917.32  1527.36   32.95
15                  ОБЛАСТЬ ЖЕТІСУ  2294.51  1992.80   31.17
16                  ОБЛАСТЬ ҰЛЫТАУ   777.27   603.52   95.32
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ   484.74   414.12   12.82
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   384.96   321.99   13.73
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ  4063.44  2945.10   21.59

In [9]:
# Переименуем колонки с MAPE, чтобы было понятно, к какому методу относятся
hw = final_hw.rename(columns={"MAPE_%": "MAPE_HW"})
sar = final_sarima.rename(columns={"MAPE_%": "MAPE_SARIMA"})
pr  = final_prophet.rename(columns={"MAPE_%": "MAPE_Prophet"})

# Мёрджим по региону
summary = (
    hw[["Регион", "MAPE_HW"]]
    .merge(sar[["Регион", "MAPE_SARIMA"]], on="Регион")
    .merge(pr[["Регион", "MAPE_Prophet"]], on="Регион")
)

# Определяем для каждой строки, какой столбец MAPE минимален
# idxmin вернёт название столбца с минимальным значением
summary["Best_method"] = summary[["MAPE_HW","MAPE_SARIMA","MAPE_Prophet"]] \
                           .idxmin(axis=1) \
                           .str.replace("MAPE_","")  # убираем префикс для красоты

# Если нужно, можно сразу отсортировать
# summary = summary.sort_values("Best_method")

# Готово!
print(summary.to_string(index=False))
summary.to_excel("results/КРС - Лучшие модели.xlsx", index=False)

                        Регион  MAPE_HW  MAPE_SARIMA  MAPE_Prophet Best_method
           АКМОЛИНСКАЯ ОБЛАСТЬ     5.59 4.670000e+00          8.62      SARIMA
           АКТЮБИНСКАЯ ОБЛАСТЬ     4.65 6.460000e+00          8.93          HW
           АЛМАТИНСКАЯ ОБЛАСТЬ    10.36 5.710000e+00         15.36      SARIMA
            АТЫРАУСКАЯ ОБЛАСТЬ     6.33 6.660000e+00         15.71          HW
ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ     7.59 6.530000e+00         12.76      SARIMA
                       ГАЛМАТЫ      NaN 2.286067e+22           NaN      SARIMA
                       ГАСТАНА    13.02 1.114000e+01         16.69      SARIMA
                      ГШЫМКЕНТ    35.63 3.761000e+01         33.20     Prophet
            ЖАМБЫЛСКАЯ ОБЛАСТЬ    13.97 1.155000e+01         13.19      SARIMA
 ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ     4.54 4.250000e+00          4.02     Prophet
        КАРАГАНДИНСКАЯ ОБЛАСТЬ     3.69 5.620000e+00         14.75          HW
          КОСТАНАЙСКАЯ ОБЛАСТЬ    12.74 1.168000e+01          9.93     Prophet
        КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ     8.25 1.239000e+01          9.06          HW
         МАНГИСТАУСКАЯ ОБЛАСТЬ    26.67 4.321000e+01         55.99          HW
                  ОБЛАСТЬ АБАЙ    13.01 1.321000e+01         32.95          HW
                ОБЛАСТЬ ЖЕТІСУ    14.94 3.085000e+01         31.17          HW
                ОБЛАСТЬ ҰЛЫТАУ    23.12 1.724000e+01         95.32      SARIMA
          ПАВЛОДАРСКАЯ ОБЛАСТЬ    14.97 1.115000e+01         12.82      SARIMA
  СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ     6.26 5.990000e+00         13.73      SARIMA
         ТУРКЕСТАНСКАЯ ОБЛАСТЬ    16.20 1.674000e+01         21.59          HW