### Подготовка датасета по показателю объем убоя КРС

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import kpss
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.arima.model import ARIMA
from pmdarima import auto_arima
from statsmodels.graphics.tsaplots import plot_acf
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

from pylab import rcParams
from IPython.display import display
import math
from prophet import Prophet
pd.set_option('display.max_columns', 130)


import warnings
from statsmodels.tools.sm_exceptions import InterpolationWarning
warnings.simplefilter("ignore", category=InterpolationWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

In [53]:
df = pd.read_excel("../../Data cleansing/output data/Просуммированные по категориям с доп регрессорами.xlsx")
df.head(5)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,Верблюды,АКМОЛИНСКАЯ ОБЛАСТЬ,0.00,0.00,0.40,0.00,0.00,0.00,0.09,1.00,0.00,0.00,0.20,0.00,0.00,0.18,0.28,0.00,0.00,0.40,0.00,0.00,0.65,0.00,0.31,1.00,0.00,0.00,0.00,0.00,0.00,2.01,0.00,1.20,0.00,0.00,2.18,0.39,0.00,0.00,1.04,0.00,0.14,2.08,0.00,0.00,0.00,0.00,0.00,0.30,0.00,0.00,0.00,0.66,0.00,0.33,0.00,0.9,0.00,0.00,0.00,10.08,0.00,0.0,0.00,0.0,0.00,0.54,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.36,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.40,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00
1,Верблюды,АКТЮБИНСКАЯ ОБЛАСТЬ,101.98,67.47,374.84,115.59,218.72,14.15,19.77,3.00,39.16,46.16,238.56,463.35,109.04,72.94,384.96,114.35,221.89,10.93,18.79,3.50,38.53,46.64,216.08,472.07,110.32,68.17,380.15,127.12,217.61,14.98,21.26,7.14,44.63,51.78,239.43,513.33,115.70,69.40,371.53,130.17,218.41,14.59,21.76,7.19,45.97,55.48,252.68,527.66,117.94,70.37,385.75,117.80,218.45,15.54,21.78,7.2,47.06,58.02,257.54,543.35,119.80,71.3,396.90,121.8,228.10,15.90,21.9,7.2,63.00,59.90,260.20,552.10,121.60,71.8,398.40,128.50,228.80,13.10,22.50,7.20,63.90,61.90,150.70,554.90,121.30,73.3,404.20,128.70,234.90,13.60,23.60,6.3,49.80,62.4,153.70,552.8,118.07,69.17,384.21,121.01,223.46,11.76,21.39,5.52,48.18,61.39,150.87,531.79,119.50,72.60,391.0,126.1,229.10,12.2,24.10,5.7,49.87,63.00,154.3,538.40
2,Верблюды,АЛМАТИНСКАЯ ОБЛАСТЬ,1.00,0.20,51.60,25.40,0.00,61.90,76.87,95.57,16.09,0.10,10.80,46.78,15.06,13.70,131.80,9.20,17.89,130.12,2.00,0.00,4.99,2.06,4.90,44.48,15.06,23.94,41.60,19.54,3.00,15.14,18.50,14.82,14.52,12.60,9.92,43.11,20.72,2.96,15.24,0.00,1.00,20.03,3.44,7.77,117.25,1.00,0.00,20.34,21.95,3.04,17.91,26.81,9.16,18.80,13.37,0.0,17.29,15.90,4.69,23.10,10.85,9.7,42.75,0.0,6.21,21.10,4.0,2.6,28.10,4.53,79.50,93.18,23.70,11.2,16.00,2.00,3.10,19.62,2.30,4.85,11.18,2.80,9.65,36.44,10.60,11.5,26.10,7.20,12.75,11.20,11.20,27.0,25.26,17.9,21.90,12.5,16.55,16.81,22.78,12.10,12.44,6.85,39.65,17.22,8.85,27.48,0.48,29.72,18.90,17.40,12.5,16.4,11.60,16.7,15.70,24.0,7.70,6.90,5.4,12.60
3,Верблюды,АТЫРАУСКАЯ ОБЛАСТЬ,213.89,167.70,306.60,164.97,342.57,192.00,43.60,113.03,262.37,193.97,308.17,1087.33,325.10,190.60,301.10,154.84,328.50,220.30,66.10,118.20,234.90,196.51,270.92,974.18,303.30,167.41,323.54,182.34,349.10,249.40,57.57,88.40,221.21,199.63,278.80,964.02,305.22,159.62,326.87,159.50,367.20,257.50,60.01,78.10,253.27,332.00,355.05,989.86,280.08,165.05,334.51,134.85,367.97,321.22,126.22,93.7,263.10,366.66,348.54,1041.38,293.40,154.8,339.44,143.6,405.80,308.35,88.5,130.5,575.30,458.70,357.62,998.10,292.76,188.3,487.02,129.28,421.44,351.20,95.77,97.54,624.80,631.65,499.30,1179.66,286.67,189.8,513.16,171.46,402.10,432.22,121.53,126.2,637.50,651.7,482.94,1412.2,307.85,200.59,466.60,182.63,414.56,405.19,184.80,154.96,717.92,719.01,522.83,1164.77,323.81,423.76,441.9,219.1,487.69,446.9,191.43,133.5,730.34,709.68,537.6,930.28
4,Верблюды,ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,0.30,0.00,0.00,1.14,6.12,4.70,4.20,1.80,1.80,0.00,6.82,18.78,0.74,0.00,1.80,2.38,1.22,2.40,3.20,2.45,0.90,2.20,0.74,12.46,0.74,2.70,1.80,0.00,0.00,3.00,0.00,0.00,0.90,7.58,1.85,13.27,0.50,0.60,1.27,0.00,0.50,1.70,0.00,0.00,3.54,3.01,11.51,21.95,0.90,0.00,0.75,4.56,4.50,3.20,0.40,8.4,5.40,0.50,2.30,17.77,0.00,0.6,0.60,2.7,0.00,3.10,0.0,0.6,5.85,3.15,3.50,2.80,0.00,0.0,0.90,1.35,0.00,3.30,0.50,0.00,7.60,0.00,2.20,5.50,0.00,0.2,0.00,1.00,0.00,0.00,0.00,0.0,0.00,0.0,0.30,1.7,0.00,0.00,0.00,0.40,0.00,0.00,0.00,0.30,0.00,0.00,0.70,0.50,0.00,0.00,0.0,0.8,0.00,0.0,0.50,0.0,0.00,0.40,0.0,0.00

In [54]:
df_krs = df[df['Показатель'].isin(['КРС', 'Температура', 'Осадки', 'Поголовье: КРС', 'Цена: Говядина'])]
df_krs.sample(10)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
203,Поголовье: КРС,ГШЫМКЕНТ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.088600e+04,7.613100e+04,75339.000000,74160.000000,74368.000000,73776.000000,74246.000000,72529.000000,7.185000e+04,7.236400e+04,7.077700e+04,7.530800e+04,7.345400e+04,8.611800e+04,8.516600e+04,8.451700e+04,83226.000000,82415.000000,8.074100e+04,8.207100e+04,7.427800e+04,7.371500e+04,7.486400e+04,7.519100e+04,8.258400e+04,8.272500e+04,8.169800e+04,8.157400e+04,8.095800e+04,7.894800e+04,7.846900e+04,7.622300e+04,7.442500e+04,7.373100e+04,7.446600e+04,7.547200e+04,8.244400e+04,8.143500e+04,8.040200e+04,7.922600e+04,7.857400e+04,7.790000e+04,7.763500e+04,7.522400e+04,7.358800e+04,7.191400e+04,7.226800e+04,7.276700e+04,7.979500e+04,7.986000e+04,7.880200e+04,7.771100e+04,7.775800e+04,7.705900e+04,7.631200e+04,4103.000000,4382.000000,4358.000000,4394.000000,4514.000000,4585.000000,4578.000000,4867.000000,5018.000000,3956.000000,5656.000000,5974.000000,94841.000000,91980.000000,90275.000000,89035.000000,89502.000000,88345.000000,1.102320e+05,1.094440e+05,1.095570e+05,1.085920e+05,1.074790e+05,1.065180e+05
41,КРС,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.079520e+03,8.805580e+03,7908.160000,9309.420000,8758.150000,10167.940000,13879.820000,7920.240000,7.586870e+03,9.335520e+03,7.608450e+03,8.279780e+03,1.055346e+04,7.745530e+03,7.067920e+03,9.366440e+03,13418.880000,11198.800000,1.584204e+04,8.100430e+03,7.896170e+03,1.012037e+04,7.816520e+03,8.071890e+03,1.019411e+04,7.587560e+03,8.019090e+03,1.037002e+04,1.331023e+04,1.333519e+04,1.566702e+04,8.540110e+03,8.646890e+03,8.820660e+03,8.933600e+03,8.980520e+03,7.566120e+03,7.968020e+03,1.246794e+04,1.098813e+04,1.279660e+04,1.310092e+04,1.756676e+04,8.683130e+03,8.849710e+03,9.935200e+03,8.989710e+03,9.127380e+03,7.984620e+03,8.620210e+03,1.206302e+04,1.188536e+04,1.407690e+04,1.295565e+04,1.750862e+04,6439.160000,6467.490000,7094.660000,8814.220000,7313.340000,6093.710000,6506.790000,10592.780000,11356.820000,8339.580000,9039.420000,14533.010000,6351.970000,11020.910000,7050.970000,9224.010000,6776.160000,15715.540000,6.948860e+03,9.372790e+03,1.573807e+04,1.056650e+04,1.144198e+04,2.935324e+04
204,Поголовье: КРС,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.163656e+06,1.020139e+06,998103.000000,972607.000000,948020.000000,921291.000000,994197.000000,993585.000000,1.036129e+06,1.105563e+06,1.151679e+06,1.175596e+06,1.157862e+06,1.070131e+06,1.050766e+06,1.024687e+06,989405.000000,960061.000000,1.052929e+06,1.052923e+06,1.053058e+06,1.095066e+06,1.166149e+06,1.229438e+06,1.257755e+06,1.229017e+06,1.130048e+06,1.109185e+06,1.080921e+06,1.047005e+06,1.011931e+06,1.128961e+06,1.129187e+06,1.167476e+06,1.241657e+06,1.300960e+06,1.328507e+06,1.326518e+06,1.175543e+06,1.145326e+06,1.115487e+06,1.082934e+06,1.050596e+06,1.129795e+06,1.129399e+06,1.167779e+06,1.233222e+06,1.292289e+06,1.318014e+06,1.314526e+06,1.199207e+06,1.170818e+06,1.141339e+06,1.108385e+06,1.078266e+06,45740.000000,46350.000000,46472.000000,46477.000000,43529.000000,43023.000000,42494.000000,43020.000000,42066.000000,60867.000000,64246.000000,63683.000000,799566.000000,795558.000000,808773.000000,848304.000000,886504.000000,904028.000000,1.145108e+06,1.120067e+06,1.101103e+06,1.078583e+06,1.056289e+06,1.030359e+06
353,Цена: Говядина,ОБЛАСТЬ ҰЛЫТАУ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.016000e+02,1.029208e+02,1.029208e+02,1.066259e+02,1.066259e+02,1.061994e+02,1.061994e+02,106.942841,108.974755,109.628604,110.505632,113.157768,118.476183,121.438087,121.438087,121.802402,121.802402,121.802402,121.924204,121.924204,122.533825,122.656359,122.901672,122.901672,122.901672,1.225330e+02,1.183668e+02,1.182485e+02,1.200222e+02,1.200222e+02,1.206223e+02
354,Цена: Говядина,ОБЛАСТЬ АБАЙ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,100.200000,100.500600,100.902602,102.214336,104.463052,106.134460,106.134460,107.938746,108.586379,108.912138,108.912138,108.912138,108.912138,108.912138,109.021050,110.220282,111.873586,111.873586,1.117617e+02,1.117617e+02,1.117617e+02,1.119852e+02,1.120972e+02,1.120972e+02
178,Температура,ПАВЛОДАРСКАЯ ОБЛАСТЬ,-13.822581,-12.507143,-6.219355,7.010000,15.622581,21.330000,21.487097,18.522581,11.726667,4.558065,-8.146667,-5.448387,-21.106452,-9.168966,-1.925806,10.373333,13.654839,20.090000,21.196774,19.154839,15.370000,-0.364516,-11.570000,-10.822581,-11.709677,-14.510714,-7.693548,7.443333,14.783871,21.256667,20.561290,19.264516,11.720000,3.464516,-3.220000,-13.458065,-22.641935,-16.282143,-6.487097,5.953333,9.958065,1.935667e+01,2.052581e+01,18.374194,11.623333,4.996774,-5.430000,-17.070968,-16.467742,-1.567143e+01,-2.877419e+00,6.056667e+00,1.224194e+01,1.710333e+01,2.196129e+01,2.067097e+01,1.213333e+01,6.967742,-8.313333,-8.512903e+00,-1.029677e+01,-7.862069e+00,-2.141935e+00,1.113333e+01,1.862581e+01,1.993667e+01,2.230323e+01,2.036452e+01,1.207000e+01,4.683871e+00,-5.173333e+00,-1.614194e+01,-2.002258e+01,-1.379286e+01,-5.874194e+00,6.513333e+00,1.747097e+01,1.826000e+01,2.135161e+01,1.981935e+01,1.058667e+01,3.964516e+00,-5.336667e+00,-8.429032e+00,-1.478387e+01,-1.278214e+01,-7.351613e+00,8.326667e+00,1.725806e+01,2.036667e+01,2.201290e+01,1.740000e+01,1.365333e+01,5.300000e+00,-7.626667e+00,-1.765484e+01,-11.680645,-15.171429,-0.506452,3.690000,14.054839,21.153333,23.532258,19.880645,13.710000,6.458065,0.016667,-11.680645,-13.922581,-14.055172,-3.677419,8.050000,12.045161,21.756667,2.243226e+01,1.919355e+01,1.070000e+01,4.567742e+00,-4.350000e+00,-1.125806e+01
22,КРС,АКТЮБИНСКАЯ ОБЛАСТЬ,5786.800000,5425.850000,6578.370000,5130.340000,5668.000000,6705.200000,3102.750000,3943.240000,4956.540000,2532.690000,4176.210000,14795.470000,5656.750000,5156.980000,6489.830000,5275.360000,5478.500000,7051.590000,3391.550000,4231.110000,5183.280000,2588.550000,4317.450000,12354.690000,5371.210000,5557.410000,7130.650000,5622.170000,5965.320000,7682.020000,3919.000000,4428.650000,5336.510000,2851.920000,4300.240000,12791.730000,5795.670000,5667.250000,7517.220000,6160.600000,6406.960000,7.933990e+03,4.435270e+03,4935.660000,6078.830000,3663.140000,5562.730000,14013.660000,5934.150000,6.141810e+03,8.358610e+03,6.662110e+03,6.725810e+03,8.915520e+03,4.726850e+03,5.674060e+03,7.976890e+03,4499.670000,7865.520000,1.636008e+04,6.385730e+03,5.963250e+03,8.157250e+03,6.614760e+03,7.887670e+03,9.793370e+03,5.534770e+03,6.065690e+03,8.354770e+03,5.336400e+03,7.383800e+03,1.625857e+04,6.121390e+03,6.405340e+03,8.425610e+03,7.339560e+03,8.111310e+03,1.046886e+04,5.692510e+03,6.907160e+03,9.365770e+03,6.490620e+03,7.943550e+03,1.718179e+04,6.464270e+03,6.818110e+03,8.957210e+03,7.666460e+03,6.958910e+03,1.269689e+04,4.676770e+03,5.466590e+03,7.014260e+03,4.594760e+03,5.580550e+03,1.452988e+04,4375.570000,5042.470000,6437.910000,5394.670000,5264.800000,8731.440000,3528.550000,4145.930000,6890.750000,3947.570000,4564.820000,10426.460000,4438.180000,4677.050000,6615.110000,5874.290000,5485.300000,7246.460000,3.784330e+03,4.406210e+03,5.198020e+03,3.894840e+03,4.389740e+03,1.060399e+04
36,КРС,ОБЛАСТЬ ЖЕТІСУ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.217272e+04,1.089690e+03,3.032750e+03,9.260090e+03,8.739990e+03,1.001237e+04,1.350990e+04,2316.140000,1617.230000,7428.000000,1982.780000,2425.270000,9047.110000,833.060000,2506.930000,6977.250000,6500.460000,7467.000000,11642.130000,2364.300000,1650.360000,7392.250000,2011.370000,2736.150000,8860.620000,1.923470e+03,2.568130e+03,7.223750e+03,6.626000e+03,6.669330e+03,1.241316e+04
337,Цена: Говядина,АЛМАТИНСКАЯ ОБЛАСТЬ,100.000000,100.000000,100.000000,98.700000,98.700000,98.700000,98.700000,98.700000,98.798700,98.798700,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.644579,110.899699,112.341395,114.475882,114.819309,114.819309,114.819309,114.819309,114.819309,114.819309,114.819309,114.819309,114.934129,115.163997,115.163997,115.163997,117.927933,118.045861,1.176917e+02,1.176917e+02,117.691723,117.691723,118.750949,121.719722,124.275837,124.275837,1.242758e+02,1.242758e+02,1.293711e+02,1.335110e+02,1.347126e+02,1.347126e+02,1.399664e+02,1.405263e+02,147.974173,148.862018,1.528813e+02,1.542572e+02,1.542572e+02,1.556455e+02,1.589141e+02,1.589141e+02,1.692435e+02,1.694128e+02,1.694128e+02,1.719539e+02,1.719539e+02,1.719539e+02,1.731576e+02,1.733308e+02,1.733308e+02,1.790507e+02,1.790507e+02,1.790507e+02,1.794088e+02,1.815617e+02,1.817433e+02,1.822885e+02,1.824708e+02,1.844780e+02,1.844780e+02,1.844780e+02,1.844780e+02,1.949932e+02,1.951882e+02,1.951882e+02,1.971401e+02,1.979286e+02,1.983245e+02,2.011010e+02,2.031121e+02,2.045338e+02,2.049429e+02,204.942905,205.147848,230.791329,231.022120,235.642562,238.470273,238.947214,238.947214,238.947214,238.947214,238.947214,238.947214,238.947214,239.186161,239.425347,240.143623,232.939314,232.939314,2.329393e+02,2.320076e+02,2.303835e+02,2.306139e+02,2.306139e+02,2.343037e+02
176,Температура,КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ,-4.751613,-0.742857,3.432258,15.046667,21.690323,29.156667,29.741935,25.906452,19.143333,9.332258,3.060000,0.561290,-0.987097,1.875862,9.351613,14.700000,21.293548,26.540000,29.016129,27.641935,20.766667,7.348387,-2.546667,-3.219355,-3.206452,-7.664286,2.341935,14.150000,22.400000,26.823333,30.283871,27.332258,20.216667,10.632258,4.556667,-5.241935,-8.732258,-5.689286,5.683871,13.416667,20.093548,2.567333e+01,3.081290e+01,25.858065,18.230000,11.458065,-0.543333,-5.700000,-3.361290,-2.864286e+00,8.306452e+00,1.407000e+01,2.204839e+01,2.746667e+01,3.168710e+01,2.565484e+01,1.855333e+01,12.648387,-0.650000,-9.000000e-01,-2.519355e+00,1.317241e+00,6.993548e+00,1.561000e+01,2.349677e+01,2.717000e+01,2.965806e+01,2.625484e+01,1.791667e+01,1.003548e+01,-1.356667e+00,-1.100968e+01,-8.745161e+00,-2.275000e+00,2.967742e+00,1.569667e+01,2.561613e+01,2.865000e+01,3.044194e+01,2.852903e+01,1.925667e+01,8.564516e+00,7.166667e-01,-3.096774e-01,-2.125806e+00,-8.214286e-02,4.470968e+00,1.835333e+01,2.263226e+01,2.935667e+01,2.935161e+01,2.625161e+01,2.135667e+01,1.069032e+01,2.990000e+00,-8.341935e+00,-5.845161,-1.207143,9.509677,15.840000,22.848387,28.156667,30.993548,26.841935,18.716667,12.900000,7.790000,-1.867742,-4.109677,-2.831034,5.387097,17.630000,20.632258,29.303333,2.799677e+01,2.670968e+01,1.836000e+01,1.153871e+01,3.476667e+00,-4.032258e+00

In [55]:
# Step 1: Pivot to wide format (each indicator becomes columns of periods)
df_wide = df_krs.pivot(index="Регион", columns="Показатель")

# Step 2: Flatten multi-level columns: ('2015-01', 'КРС') → 'КРС_2015-01'
df_wide.columns = [f"{col[1]}_{col[0]}" for col in df_wide.columns]
df_wide = df_wide.reset_index()

# Step 3: Melt: one row per region-period-indicator
df_melted = df_wide.melt(id_vars="Регион", var_name="indicator_period", value_name="value")

# Step 4: Extract 'Период' and 'Показатель' from the combined column
df_melted["Период"] = df_melted["indicator_period"].str.extract(r"_(\d{4}-\d{2})$")
df_melted["Показатель"] = df_melted["indicator_period"].str.extract(r"^(.+)_\d{4}-\d{2}")

# Step 5: Pivot again to get final modeling format: one row per region+period, one column per indicator
df_krs = df_melted.pivot_table(index=["Регион", "Период"], columns="Показатель", values="value").reset_index()
print(df_krs.groupby("Регион").size().reset_index(name="Количество строк"))
df_krs

                            Регион  Количество строк
0              АКМОЛИНСКАЯ ОБЛАСТЬ               120
1              АКТЮБИНСКАЯ ОБЛАСТЬ               120
2              АЛМАТИНСКАЯ ОБЛАСТЬ               120
3               АТЫРАУСКАЯ ОБЛАСТЬ               120
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ               120
5                          ГАЛМАТЫ               120
6                          ГАСТАНА               120
7                         ГШЫМКЕНТ                79
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ               120
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ               120
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ               120
11            КОСТАНАЙСКАЯ ОБЛАСТЬ               120
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ               120
13           МАНГИСТАУСКАЯ ОБЛАСТЬ               120
14                    ОБЛАСТЬ АБАЙ                31
15                  ОБЛАСТЬ ЖЕТІСУ                31
16                  ОБЛАСТЬ ҰЛЫТАУ                31
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ               120
18            РЕСПУБЛИКА КАЗАХСТАН               120
19    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ               120
20           ТУРКЕСТАНСКАЯ ОБЛАСТЬ                79

Показатель,Регион,Период,КРС,Осадки,Поголовье: КРС,Температура,Цена: Говядина
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-01,4455.35,9.8,372560.0,-12.490323,100.000000
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-02,3654.20,9.8,399442.0,-10.192857,100.000000
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-03,4287.08,8.3,425605.0,-5.870968,100.000000
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-04,3923.21,8.8,440023.0,4.490000,99.800000
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-05,3849.70,42.8,444647.0,14.574194,99.800000
...,...,...,...,...,...,...,...
2166,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-08,9372.79,0.0,1120067.0,27.874194,164.973838
2167,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-09,15738.07,0.5,1101103.0,20.766667,164.973838
2168,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-10,10566.50,13.6,1078583.0,13.200000,165.138812
2169,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-11,11441.98,12.1,1056289.0,6.500000,165.469090
2170,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-12,29353.24,17.3,1030359.0,-1.854839,165.965497

In [56]:
df_krs = df_krs[df_krs["Регион"] != 'РЕСПУБЛИКА КАЗАХСТАН']

In [57]:
df_krs

Показатель,Регион,Период,КРС,Осадки,Поголовье: КРС,Температура,Цена: Говядина
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-01,4455.35,9.8,372560.0,-12.490323,100.000000
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-02,3654.20,9.8,399442.0,-10.192857,100.000000
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-03,4287.08,8.3,425605.0,-5.870968,100.000000
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-04,3923.21,8.8,440023.0,4.490000,99.800000
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2015-05,3849.70,42.8,444647.0,14.574194,99.800000
...,...,...,...,...,...,...,...
2166,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-08,9372.79,0.0,1120067.0,27.874194,164.973838
2167,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-09,15738.07,0.5,1101103.0,20.766667,164.973838
2168,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-10,10566.50,13.6,1078583.0,13.200000,165.138812
2169,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-11,11441.98,12.1,1056289.0,6.500000,165.469090
2170,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2024-12,29353.24,17.3,1030359.0,-1.854839,165.965497

In [58]:
df_krs.to_excel("Датасет по КРС с регрессорами.xlsx", index=False)

In [59]:
df_krs = df_krs.drop(columns=['Осадки', 'Поголовье: КРС', 'Температура',
       'Цена: Говядина'])
df_krs.sample(10)

Показатель                        Регион   Период       КРС
1690                      ОБЛАСТЬ ЖЕТІСУ  2024-02   1650.36
1669                        ОБЛАСТЬ АБАЙ  2024-12  18068.25
1394                КОСТАНАЙСКАЯ ОБЛАСТЬ  2024-08   2421.12
1729                      ОБЛАСТЬ ҰЛЫТАУ  2024-10    507.00
2024        СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  2019-05   2675.35
48                   АКМОЛИНСКАЯ ОБЛАСТЬ  2019-01   4842.70
1541               МАНГИСТАУСКАЯ ОБЛАСТЬ  2016-11     68.25
676                              ГАЛМАТЫ  2021-05      1.00
1805                ПАВЛОДАРСКАЯ ОБЛАСТЬ  2021-02   3169.99
1627               МАНГИСТАУСКАЯ ОБЛАСТЬ  2024-01     95.22

In [60]:
df_krs.to_excel("Датасет по КРС.xlsx", index=False)

In [61]:
# 1) приведение типов
df = df_krs.copy()
df["Период"] = pd.to_datetime(df["Период"], format="%Y-%m", errors="coerce")
df["КРС"] = pd.to_numeric(df["КРС"], errors="coerce")

# 2) wide-таблица: строки — месяцы, столбцы — регионы, значения — КРС
df_krs_wide = (df
        .pivot_table(index="Период", columns="Регион", values="КРС", aggfunc="sum")  # если дублей нет — можно aggfunc="first"
        .sort_index())
# 3) Убираем лишний уровень индекса у колонок
df_krs_wide.columns.name = None

# 4) Возвращаем "Период" в строковый формат YYYY-MM
df_krs_wide = df_krs_wide.reset_index()
df_krs_wide["Период"] = df_krs_wide["Период"].dt.strftime("%Y-%m")

df_krs_wide.to_excel("Датасет по КРС wide.xlsx", index=False)
df_krs_wide

,Период,АКМОЛИНСКАЯ ОБЛАСТЬ,АКТЮБИНСКАЯ ОБЛАСТЬ,АЛМАТИНСКАЯ ОБЛАСТЬ,АТЫРАУСКАЯ ОБЛАСТЬ,ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,ГАЛМАТЫ,ГАСТАНА,ГШЫМКЕНТ,ЖАМБЫЛСКАЯ ОБЛАСТЬ,ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,КАРАГАНДИНСКАЯ ОБЛАСТЬ,КОСТАНАЙСКАЯ ОБЛАСТЬ,КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ,МАНГИСТАУСКАЯ ОБЛАСТЬ,ОБЛАСТЬ АБАЙ,ОБЛАСТЬ ЖЕТІСУ,ОБЛАСТЬ ҰЛЫТАУ,ПАВЛОДАРСКАЯ ОБЛАСТЬ,СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,ТУРКЕСТАНСКАЯ ОБЛАСТЬ
0,2015-01,4455.35,5786.80,6087.47,1957.38,4151.27,35.38,7.48,NaN,2731.22,2406.30,4276.61,3858.83,1446.34,30.15,NaN,NaN,NaN,2646.74,6302.91,NaN
1,2015-02,3654.20,5425.85,4454.61,1755.18,6473.64,14.65,27.08,NaN,3109.06,2980.56,2663.85,5661.27,1165.32,225.79,NaN,NaN,NaN,2934.07,3236.66,NaN
2,2015-03,4287.08,6578.37,16005.48,2085.52,6837.39,34.19,13.91,NaN,2538.81,3497.07,3105.64,4313.48,1233.92,581.50,NaN,NaN,NaN,3230.62,1531.42,NaN
3,2015-04,3923.21,5130.34,3934.04,1346.93,5875.35,40.53,19.11,NaN,3379.88,3061.07,2216.56,4841.38,1355.81,574.71,NaN,NaN,NaN,2731.05,2111.45,NaN
4,2015-05,3849.70,5668.00,7098.30,2073.99,5952.33,36.70,17.31,NaN,2921.49,3678.77,3436.05,7257.34,1189.73,270.72,NaN,NaN,NaN,2830.10,2218.93,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2024-08,2412.70,4406.21,5453.39,1640.07,2845.28,2.30,1.70,352.82,4488.08,3873.69,3097.30,2421.12,1581.37,84.38,3114.29,2568.13,593.10,4061.35,3472.15,9372.79
116,2024-09,2909.66,5198.02,11705.42,2317.39,5000.88,12.50,3.40,350.02,4264.39,5466.61,5874.20,3723.42,1724.95,242.24,5453.19,7223.75,750.95,4014.27,5090.14,15738.07
117,2024-10,2608.27,3894.84,8880.02,2004.60,3396.22,4.00,2.60,466.45,3418.05,3586.35,2631.65,1925.96,1919.48,168.08,3460.45,6626.00,507.00,4697.04,2367.75,10566.50
118,2024-11,3649.19,4389.74,5882.78,3124.16,4578.81,5.90,2.00,494.05,5708.50,4578.05,4280.10,1575.93,1838.46,258.08,5847.30,6669.33,248.25,5946.29,2041.65,11441.98
119,2024-12,4253.58,10603.99,12400.36,3594.82,9958.40,18.80,3.60,744.54,15350.76,9000.38,6972.33,2429.17,2285.11,517.28,18068.25,12413.16,1142.30,7538.52,3772.16,29353.24