In [1]:
# --- 1. Импорты и общие настройки ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from pmdarima import auto_arima
from statsmodels.tsa.statespace.sarimax import SARIMAX
from prophet import Prophet  # pip install prophet
from sklearn.metrics import mean_squared_error, mean_absolute_error
import warnings
pd.options.display.float_format = '{:.2f}'.format
warnings.filterwarnings("ignore")
# plt.style.use("seaborn-whitegrid")

In [2]:
# --- 2. Загрузка данных ---
# df должен содержать столбцы: "Регион", "Период" (YYYY-MM), и целевой столбец с показателем.
df = pd.read_excel("Датасет по свиньям.xlsx")
df["Период"] = pd.to_datetime(df["Период"], format="%Y-%m")
df.sample(10)

                      Регион     Период  Свиньи
1808          ОБЛАСТЬ ЖЕТІСУ 2025-03-01  208.34
123      АКМОЛИНСКАЯ ОБЛАСТЬ 2025-04-01  467.44
880                  ГАСТАНА 2024-11-01    0.00
25       АКМОЛИНСКАЯ ОБЛАСТЬ 2017-02-01  763.08
835                  ГАСТАНА 2021-02-01    0.00
392       АТЫРАУСКАЯ ОБЛАСТЬ 2015-12-01    7.10
162      АКТЮБИНСКАЯ ОБЛАСТЬ 2017-12-01 1059.16
1708   МАНГИСТАУСКАЯ ОБЛАСТЬ 2023-03-01    0.00
89       АКМОЛИНСКАЯ ОБЛАСТЬ 2022-06-01 1578.44
1485  КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ 2015-03-01   15.33

In [3]:
regions = df['Регион'].unique()
target   = "Свиньи"
horizon  = 3
epsilon = 1e-6

In [4]:
first_test = pd.to_datetime("2024-08-01")
last_possible = df["Период"].max() - pd.DateOffset(months=horizon-1)
test_starts = pd.date_range(first_test, last_possible, freq="MS")

## Holw-Winter's (log)

In [5]:
results_hw = []
for region in regions:
    ts = (df[df["Регион"] == region]
          .set_index("Период")[target]
          .dropna()
          .sort_index())
    if len(ts) < 24:
        print(f"{region}: всего {len(ts)} мес. — сезонный Holt-Winter's невозможен.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        # формируем train / test
        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]

        # пропускаем, если недостаточно данных или неполный test
        if len(train) < 24 or len(test) < horizon:
            continue

        # обучаем модель
        train_log = np.log1p(train)

        hw_log = ExponentialSmoothing(
            train_log,
            seasonal="add",
            seasonal_periods=12
        ).fit(optimized=True)

        # прогноз и метрики
        fc_log = hw_log.forecast(horizon)
        fc = np.expm1(fc_log) 
        # fc   = model.forecast(horizon)
        rmse = np.sqrt(mean_squared_error(test, fc))
        mae  = mean_absolute_error(test, fc)
        mape = (np.abs((test - fc) / test).mean()) * 100

        results_hw.append({
            "Регион":      region,
            "Test start":  test_start.strftime("%Y-%m"),
            "Test end":    test_end.strftime("%Y-%m"),
            "Forecast":    [x.round(2) for x in list(fc.values)],
            "Actual":      [y.round(2) for y in list(test.values)],
            "RMSE":        rmse,
            "MAE":         mae,
            "MAPE_%":      mape
        })

# 4) Усреднение по всем скользящим окнам для каждого региона
res_hw = pd.DataFrame(results_hw)
res_hw.to_excel("results/Свиньи - Результаты прогнозов ХВ.xlsx", index=False)
print("Результаты прогнозов HW на 3 месяца:")

display(res_hw)

final_hw = (
    res_hw
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_hw.to_excel("results/Свиньи - Результаты прогнозов ХВ средние.xlsx", index=False)
print("Средние метрики Holt–Winter's по регионам (rolling-3):")
display(final_hw)

Результаты прогнозов HW на 3 месяца:

,Регион,Test start,Test end,Forecast,Actual,RMSE,MAE,MAPE_%
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,"[452.55, 535.04, 559.53]","[553.23, 566.96, 496.85]",70.91,65.09,12.15
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,"[579.8, 605.93, 796.64]","[566.96, 496.85, 488.59]",188.82,143.33,29.09
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,"[600.71, 789.75, 1297.47]","[496.85, 488.59, 480.05]",506.51,407.48,84.27
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,"[734.57, 1207.56, 319.13]","[488.59, 480.05, 263.72]",444.54,342.97,74.30
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,"[1010.19, 267.49, 343.74]","[480.05, 263.72, 340.79]",306.09,178.95,37.58
...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,"[0.82, 1.83, 2.06]","[0.4, 1.1, 1.8]",0.51,0.47,62.23
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,"[1.48, 1.68, 1.29]","[1.1, 1.8, 0.4]",0.56,0.46,87.81
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,"[1.47, 1.11, 1.15]","[1.8, 0.4, 0.7]",0.52,0.50,86.65
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,"[1.25, 1.28, 1.96]","[0.4, 0.7, 0.2]",1.18,1.06,391.29
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,"[0.8, 1.34, 2.78]","[0.7, 0.2, 1.4]",1.04,0.88,228.52

Средние метрики Holt–Winter's по регионам (rolling-3):

                            Регион   RMSE    MAE  MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ 212.06 167.22   35.99
1              АКТЮБИНСКАЯ ОБЛАСТЬ  14.34  11.83   23.21
2              АЛМАТИНСКАЯ ОБЛАСТЬ  80.16  71.08  193.80
3               АТЫРАУСКАЯ ОБЛАСТЬ   0.56   0.44     NaN
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  98.05  89.04   27.16
5                          ГАЛМАТЫ   0.67   0.49     NaN
6                          ГАСТАНА   0.08   0.07     NaN
7                         ГШЫМКЕНТ   3.15   2.55   96.04
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ  11.06   9.95   41.37
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  24.04  20.98   11.99
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ 169.66 150.24   15.53
11            КОСТАНАЙСКАЯ ОБЛАСТЬ 117.46 108.56   29.30
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ   8.42   5.55   31.71
13           МАНГИСТАУСКАЯ ОБЛАСТЬ   0.32   0.26     NaN
14                    ОБЛАСТЬ АБАЙ  35.54  28.26   34.83
15                  ОБЛАСТЬ ЖЕТІСУ 154.22 117.75   58.23
16                  ОБЛАСТЬ ҰЛЫТАУ   1.53   1.25     NaN
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ 304.75 256.93   16.26
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 430.98 389.15   24.42
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ   1.05   0.88  107.47

In [6]:
# res_hw[res_hw['Регион'] == 'КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ']

## SARIMA

In [6]:
results_sarima = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    ts = ts + epsilon
    ts_log = np.log(ts)

    if len(ts_log) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. для авто-ARIMA, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train_log = ts_log[ts_log.index < test_start]
        test_log  = ts_log[(ts_log.index >= test_start) & (ts_log.index <= test_end)]
        if len(train_log) < 12 + horizon or len(test_log) < horizon:
            continue

        # автоподбор на лог-данных
        use_seasonal = len(train_log) >= 2 * 12

        sarima_log = auto_arima(
            train_log,
            seasonal=use_seasonal,
            m=12 if use_seasonal else 1,
            D=1 if use_seasonal else 0,      # фиксируем порядок сезонной разности
            seasonal_test=None,               # пропустить nsdiffs
            boxcox=True,
            stepwise=True,
            suppress_warnings=True,
            error_action="ignore"
        )
      
        # прогноз в лог-шкале
        fc_log = sarima_log.predict(n_periods=horizon, return_conf_int=False)

        # возвращаем прогноз в исходные единицы
        fc = np.exp(fc_log) - epsilon
        actual = np.exp(test_log.values) - epsilon  # но exp(log(x)) == x

        # метрики на исходном уровне
        rmse = np.sqrt(mean_squared_error(actual, fc))
        mae  = mean_absolute_error(actual, fc)
        mape = (np.abs((actual - fc) / actual).mean()) * 100

        results_sarima.append({
            "Регион":         region,
            "Test start":     test_start.strftime("%Y-%m"),
            "Test end":       test_end.strftime("%Y-%m"),
            "order":          sarima_log.order,
            "seasonal_order": sarima_log.seasonal_order,
            "RMSE":           round(rmse,2),
            "MAE":            round(mae,2),
            "MAPE_%":         round(mape,2),
            "Forecast":       [round(x,2) for x in fc],
            "Actual":         [round(y,2) for y in actual]
        })
# формируем DataFrame с результатами
res_sarima = pd.DataFrame(results_sarima)
res_sarima.to_excel("results/Свиньи - Результаты прогнозов SARIMA.xlsx", index=False)
print("Результаты прогнозов SARIMA на 3 месяца:")

display(res_sarima)

final_sarima = (
    res_sarima
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_sarima.to_excel("results/Свиньи - Результаты прогнозов SARIMA средние.xlsx", index=False)
print("Средние метрики SARIMA по регионам (rolling-3):")
display(final_sarima)

Результаты прогнозов SARIMA на 3 месяца:

,Регион,Test start,Test end,order,seasonal_order,RMSE,MAE,MAPE_%,Forecast,Actual
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,"(0, 1, 1)","(0, 1, 1, 12)",73.08,61.25,11.18,"[436.41, 525.28, 522.1]","[553.23, 566.96, 496.85]"
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,"(0, 1, 1)","(0, 1, 1, 12)",154.51,110.54,22.52,"[569.74, 567.61, 746.67]","[566.96, 496.85, 488.59]"
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,"(0, 1, 1)","(0, 1, 1, 12)",427.94,339.58,70.26,"[567.02, 745.43, 1171.78]","[496.85, 488.59, 480.05]"
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,"(0, 1, 1)","(0, 1, 1, 12)",390.28,297.82,63.53,"[714.92, 1116.26, 294.65]","[488.59, 480.05, 263.72]"
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,"(0, 1, 1)","(0, 1, 1, 12)",285.98,168.29,35.52,"[975.33, 257.0, 343.66]","[480.05, 263.72, 340.79]"
...,...,...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,"(0, 1, 1)","(0, 1, 0, 12)",0.76,0.65,57.04,"[0.17, 0.57, 0.62]","[0.4, 1.1, 1.8]"
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,"(0, 1, 1)","(0, 1, 0, 12)",0.70,0.59,51.82,"[0.64, 0.69, 0.19]","[1.1, 1.8, 0.4]"
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,"(0, 1, 1)","(0, 1, 0, 12)",0.66,0.55,54.50,"[0.75, 0.21, 0.3]","[1.8, 0.4, 0.7]"
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,"(0, 1, 1)","(0, 1, 0, 12)",0.26,0.24,63.91,"[0.24, 0.34, -0.0]","[0.4, 0.7, 0.2]"
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,"(0, 1, 1)","(0, 1, 0, 12)",0.36,0.34,60.56,"[0.37, -0.0, 1.88]","[0.7, 0.2, 1.4]"

Средние метрики SARIMA по регионам (rolling-3):

                            Регион   RMSE    MAE                    MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ 199.53 157.56                     34.23
1              АКТЮБИНСКАЯ ОБЛАСТЬ  10.68   9.25                     17.36
2              АЛМАТИНСКАЯ ОБЛАСТЬ  77.30  67.11                    196.48
3               АТЫРАУСКАЯ ОБЛАСТЬ   0.22   0.13  156015071304232927232.00
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 133.94 119.29                     34.98
5                          ГАЛМАТЫ   0.37   0.21    4753769302223073280.00
6                          ГАСТАНА   0.03   0.02  108808626061915291648.00
7                         ГШЫМКЕНТ   0.76   0.62                     38.45
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ   8.15   6.87                     24.22
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  23.06  20.13                     11.33
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ 174.15 154.27                     16.62
11            КОСТАНАЙСКАЯ ОБЛАСТЬ 112.30 102.88                     25.73
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ   5.85   4.02                     28.63
13           МАНГИСТАУСКАЯ ОБЛАСТЬ   0.00   0.00     356635791936596160.00
14                    ОБЛАСТЬ АБАЙ  46.68  30.21                     38.66
15                  ОБЛАСТЬ ЖЕТІСУ 355.47 296.42                    168.03
16                  ОБЛАСТЬ ҰЛЫТАУ   1.52   1.26 2304214110064169451520.00
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ 256.83 224.91                     14.41
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 310.93 280.43                     16.90
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ   1.90   1.56                     71.05

## Facebook Prophet

In [7]:
results_prophet = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    if len(ts) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. данных, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]
        if len(train) < 12 + horizon or len(test) < horizon:
            continue

        # Подготовка данных для Prophet
#         df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
# # подготовка для одного региона
        df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
        df_prophet["y"] = np.log(df_prophet["y"] + epsilon)

        m = Prophet()
        m.fit(df_prophet)

        future = m.make_future_dataframe(periods=horizon, freq="MS")
        forecast = m.predict(future)

        # берем только прогнозные точки
        yhat_log = forecast["yhat"].values[-horizon:]
        fc = np.exp(yhat_log) - epsilon

        # m = Prophet()
        # m.fit(df_prophet)

        # # Создаем DataFrame будущих дат и делаем прогноз
        # # future = m.make_future_dataframe(periods=horizon, freq="MS")
        # # forecast = m.predict(future)

        # # Отбираем только наши горизонты
        # fc = forecast.set_index("ds")["yhat"].loc[test.index].values
        actual = test.values

        # Расчет метрик
        rmse  = np.sqrt(mean_squared_error(actual, fc))
        mae   = mean_absolute_error(actual, fc)
        mape  = (np.abs((actual - fc) / actual).mean()) * 100

        results_prophet.append({
            "Регион":     region,
            "Test start": test_start.strftime("%Y-%m"),
            "Test end":   test_end.strftime("%Y-%m"),
            "RMSE":       round(rmse, 2),
            "MAE":        round(mae, 2),
            "MAPE_%":     round(mape, 2),
            "Forecast":   [round(x, 2) for x in fc],
            "Actual":     [round(x, 2) for x in actual]
        })

# Собираем результаты в DataFrame
res_prophet = pd.DataFrame(results_prophet)
res_prophet.to_excel("results/Свиньи - Результаты прогнозов Prophet.xlsx", index=False)
print("Результаты прогнозов Prophet на 3 месяца:")
display(res_prophet)

final_prophet = (
    res_prophet
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_prophet.to_excel("results/Свиньи - Результаты прогнозов Prophet средние.xlsx", index=False)
print("Средние метрики Prophet по регионам (rolling-3):")
display(final_prophet)

01:27:20 - cmdstanpy - INFO - Chain [1] start processing
01:27:22 - cmdstanpy - INFO - Chain [1] done processing
01:27:22 - cmdstanpy - INFO - Chain [1] start processing
01:27:22 - cmdstanpy - INFO - Chain [1] done processing
01:27:22 - cmdstanpy - INFO - Chain [1] start processing
01:27:22 - cmdstanpy - INFO - Chain [1] done processing
01:27:22 - cmdstanpy - INFO - Chain [1] start processing
01:27:23 - cmdstanpy - INFO - Chain [1] done processing
01:27:23 - cmdstanpy - INFO - Chain [1] start processing
01:27:23 - cmdstanpy - INFO - Chain [1] done processing
01:27:23 - cmdstanpy - INFO - Chain [1] start processing
01:27:23 - cmdstanpy - INFO - Chain [1] done processing
01:27:24 - cmdstanpy - INFO - Chain [1] start processing
01:27:24 - cmdstanpy - INFO - Chain [1] done processing
01:27:24 - cmdstanpy - INFO - Chain [1] start processing
01:27:24 - cmdstanpy - INFO - Chain [1] done processing
01:27:24 - cmdstanpy - INFO - Chain [1] start processing
01:27:24 - cmdstanpy - INFO - Chain [1] done processing
01:27:25 - cmdstanpy - INFO - Chain [1] start processing
01:27:25 - cmdstanpy - INFO - Chain [1] done processing
01:27:25 - cmdstanpy - INFO - Chain [1] start processing
01:27:25 - cmdstanpy - INFO - Chain [1] done processing
01:27:25 - cmdstanpy - INFO - Chain [1] start processing
01:27:25 - cmdstanpy - INFO - Chain [1] done processing
01:27:26 - cmdstanpy - INFO - Chain [1] start processing
01:27:26 - cmdstanpy - INFO - Chain [1] done processing
01:27:26 - cmdstanpy - INFO - Chain [1] start processing
01:27:26 - cmdstanpy - INFO - Chain [1] done processing
01:27:26 - cmdstanpy - INFO - Chain [1] start processing
01:27:26 - cmdstanpy - INFO - Chain [1] done processing
01:27:27 - cmdstanpy - INFO - Chain [1] start processing
01:27:27 - cmdstanpy - INFO - Chain [1] done processing
01:27:27 - cmdstanpy - INFO - Chain [1] start processing
01:27:27 - cmdstanpy - INFO - Chain [1] done processing
01:27:27 - cmdstanpy - INFO - Chain [1] start processing
01:27:27 - cmdstanpy - INFO - Chain [1] done processing
01:27:28 - cmdstanpy - INFO - Chain [1] start processing
01:27:28 - cmdstanpy - INFO - Chain [1] done processing
01:27:28 - cmdstanpy - INFO - Chain [1] start processing
01:27:28 - cmdstanpy - INFO - Chain [1] done processing
01:27:28 - cmdstanpy - INFO - Chain [1] start processing
01:27:28 - cmdstanpy - INFO - Chain [1] done processing
01:27:29 - cmdstanpy - INFO - Chain [1] start processing
01:27:29 - cmdstanpy - INFO - Chain [1] done processing
01:27:29 - cmdstanpy - INFO - Chain [1] start processing
01:27:29 - cmdstanpy - INFO - Chain [1] done processing
01:27:29 - cmdstanpy - INFO - Chain [1] start processing
01:27:29 - cmdstanpy - INFO - Chain [1] done processing
01:27:30 - cmdstanpy - INFO - Chain [1] start processing
01:27:30 - cmdstanpy - INFO - Chain [1] done processing
01:27:30 - cmdstanpy - INFO - Chain [1] start processing
01:27:30 - cmdstanpy - INFO - Chain [1] done processing
01:27:30 - cmdstanpy - INFO - Chain [1] start processing
01:27:31 - cmdstanpy - INFO - Chain [1] done processing
01:27:31 - cmdstanpy - INFO - Chain [1] start processing
01:27:31 - cmdstanpy - INFO - Chain [1] done processing
01:27:31 - cmdstanpy - INFO - Chain [1] start processing
01:27:31 - cmdstanpy - INFO - Chain [1] done processing
01:27:32 - cmdstanpy - INFO - Chain [1] start processing
01:27:32 - cmdstanpy - INFO - Chain [1] done processing
01:27:32 - cmdstanpy - INFO - Chain [1] start processing
01:27:32 - cmdstanpy - INFO - Chain [1] done processing
01:27:32 - cmdstanpy - INFO - Chain [1] start processing
01:27:32 - cmdstanpy - INFO - Chain [1] done processing
01:27:33 - cmdstanpy - INFO - Chain [1] start processing
01:27:33 - cmdstanpy - INFO - Chain [1] done processing
01:27:33 - cmdstanpy - INFO - Chain [1] start processing
01:27:33 - cmdstanpy - INFO - Chain [1] done processing
01:27:33 - cmdstanpy - INFO - Chain [1] start processing
01:27:33 - cmdstanpy - INFO - Chain [1] done processing
01:27:34 - cmdstanpy - INFO - Chain [1] start processing
01:27:34 - cmdstanpy - INFO - Chain [1] done processing
01:27:34 - cmdstanpy - INFO - Chain [1] start processing
01:27:34 - cmdstanpy - INFO - Chain [1] done processing
01:27:34 - cmdstanpy - INFO - Chain [1] start processing
01:27:34 - cmdstanpy - INFO - Chain [1] done processing
01:27:35 - cmdstanpy - INFO - Chain [1] start processing
01:27:35 - cmdstanpy - INFO - Chain [1] done processing
01:27:35 - cmdstanpy - INFO - Chain [1] start processing
01:27:35 - cmdstanpy - INFO - Chain [1] done processing
01:27:35 - cmdstanpy - INFO - Chain [1] start processing
01:27:35 - cmdstanpy - INFO - Chain [1] done processing
01:27:36 - cmdstanpy - INFO - Chain [1] start processing
01:27:36 - cmdstanpy - INFO - Chain [1] done processing
01:27:36 - cmdstanpy - INFO - Chain [1] start processing
01:27:36 - cmdstanpy - INFO - Chain [1] done processing
01:27:36 - cmdstanpy - INFO - Chain [1] start processing
01:27:36 - cmdstanpy - INFO - Chain [1] done processing
01:27:37 - cmdstanpy - INFO - Chain [1] start processing
01:27:37 - cmdstanpy - INFO - Chain [1] done processing
01:27:37 - cmdstanpy - INFO - Chain [1] start processing
01:27:37 - cmdstanpy - INFO - Chain [1] done processing
01:27:37 - cmdstanpy - INFO - Chain [1] start processing
01:27:37 - cmdstanpy - INFO - Chain [1] done processing
01:27:37 - cmdstanpy - INFO - Chain [1] start processing
01:27:37 - cmdstanpy - INFO - Chain [1] done processing
01:27:38 - cmdstanpy - INFO - Chain [1] start processing
01:27:38 - cmdstanpy - INFO - Chain [1] done processing
01:27:38 - cmdstanpy - INFO - Chain [1] start processing
01:27:38 - cmdstanpy - INFO - Chain [1] done processing
01:27:38 - cmdstanpy - INFO - Chain [1] start processing
01:27:38 - cmdstanpy - INFO - Chain [1] done processing
01:27:38 - cmdstanpy - INFO - Chain [1] start processing
01:27:38 - cmdstanpy - INFO - Chain [1] done processing
01:27:39 - cmdstanpy - INFO - Chain [1] start processing
01:27:39 - cmdstanpy - INFO - Chain [1] done processing
01:27:39 - cmdstanpy - INFO - Chain [1] start processing
01:27:39 - cmdstanpy - INFO - Chain [1] done processing
01:27:39 - cmdstanpy - INFO - Chain [1] start processing
01:27:39 - cmdstanpy - INFO - Chain [1] done processing
01:27:39 - cmdstanpy - INFO - Chain [1] start processing
01:27:40 - cmdstanpy - INFO - Chain [1] done processing
01:27:40 - cmdstanpy - INFO - Chain [1] start processing
01:27:40 - cmdstanpy - INFO - Chain [1] done processing
01:27:40 - cmdstanpy - INFO - Chain [1] start processing
01:27:40 - cmdstanpy - INFO - Chain [1] done processing
01:27:40 - cmdstanpy - INFO - Chain [1] start processing
01:27:40 - cmdstanpy - INFO - Chain [1] done processing
01:27:40 - cmdstanpy - INFO - Chain [1] start processing
01:27:41 - cmdstanpy - INFO - Chain [1] done processing
01:27:41 - cmdstanpy - INFO - Chain [1] start processing
01:27:41 - cmdstanpy - INFO - Chain [1] done processing
01:27:41 - cmdstanpy - INFO - Chain [1] start processing
01:27:41 - cmdstanpy - INFO - Chain [1] done processing
01:27:41 - cmdstanpy - INFO - Chain [1] start processing
01:27:41 - cmdstanpy - INFO - Chain [1] done processing
01:27:42 - cmdstanpy - INFO - Chain [1] start processing
01:27:42 - cmdstanpy - INFO - Chain [1] done processing
01:27:42 - cmdstanpy - INFO - Chain [1] start processing
01:27:42 - cmdstanpy - INFO - Chain [1] done processing
01:27:42 - cmdstanpy - INFO - Chain [1] start processing
01:27:42 - cmdstanpy - INFO - Chain [1] done processing
01:27:42 - cmdstanpy - INFO - Chain [1] start processing
01:27:42 - cmdstanpy - INFO - Chain [1] done processing
01:27:43 - cmdstanpy - INFO - Chain [1] start processing
01:27:43 - cmdstanpy - INFO - Chain [1] done processing
01:27:43 - cmdstanpy - INFO - Chain [1] start processing
01:27:43 - cmdstanpy - INFO - Chain [1] done processing
01:27:43 - cmdstanpy - INFO - Chain [1] start processing
01:27:43 - cmdstanpy - INFO - Chain [1] done processing
01:27:43 - cmdstanpy - INFO - Chain [1] start processing
01:27:44 - cmdstanpy - INFO - Chain [1] done processing
01:27:44 - cmdstanpy - INFO - Chain [1] start processing
01:27:44 - cmdstanpy - INFO - Chain [1] done processing
01:27:44 - cmdstanpy - INFO - Chain [1] start processing
01:27:45 - cmdstanpy - INFO - Chain [1] done processing
01:27:45 - cmdstanpy - INFO - Chain [1] start processing
01:27:45 - cmdstanpy - INFO - Chain [1] done processing
01:27:45 - cmdstanpy - INFO - Chain [1] start processing
01:27:46 - cmdstanpy - INFO - Chain [1] done processing
01:27:46 - cmdstanpy - INFO - Chain [1] start processing
01:27:46 - cmdstanpy - INFO - Chain [1] done processing
01:27:46 - cmdstanpy - INFO - Chain [1] start processing
01:27:47 - cmdstanpy - INFO - Chain [1] done processing
01:27:47 - cmdstanpy - INFO - Chain [1] start processing
01:27:47 - cmdstanpy - INFO - Chain [1] done processing
01:27:47 - cmdstanpy - INFO - Chain [1] start processing
01:27:48 - cmdstanpy - INFO - Chain [1] done processing
01:27:48 - cmdstanpy - INFO - Chain [1] start processing
01:27:48 - cmdstanpy - INFO - Chain [1] done processing
01:27:48 - cmdstanpy - INFO - Chain [1] start processing
01:27:48 - cmdstanpy - INFO - Chain [1] done processing
01:27:49 - cmdstanpy - INFO - Chain [1] start processing
01:27:49 - cmdstanpy - INFO - Chain [1] done processing
01:27:49 - cmdstanpy - INFO - Chain [1] start processing
01:27:49 - cmdstanpy - INFO - Chain [1] done processing
01:27:49 - cmdstanpy - INFO - Chain [1] start processing
01:27:49 - cmdstanpy - INFO - Chain [1] done processing
01:27:49 - cmdstanpy - INFO - Chain [1] start processing
01:27:49 - cmdstanpy - INFO - Chain [1] done processing
01:27:50 - cmdstanpy - INFO - Chain [1] start processing
01:27:50 - cmdstanpy - INFO - Chain [1] done processing
01:27:50 - cmdstanpy - INFO - Chain [1] start processing
01:27:50 - cmdstanpy - INFO - Chain [1] done processing
01:27:50 - cmdstanpy - INFO - Chain [1] start processing
01:27:50 - cmdstanpy - INFO - Chain [1] done processing
01:27:50 - cmdstanpy - INFO - Chain [1] start processing
01:27:50 - cmdstanpy - INFO - Chain [1] done processing
01:27:51 - cmdstanpy - INFO - Chain [1] start processing
01:27:51 - cmdstanpy - INFO - Chain [1] done processing
01:27:51 - cmdstanpy - INFO - Chain [1] start processing
01:27:51 - cmdstanpy - INFO - Chain [1] done processing
01:27:51 - cmdstanpy - INFO - Chain [1] start processing
01:27:51 - cmdstanpy - INFO - Chain [1] done processing
01:27:51 - cmdstanpy - INFO - Chain [1] start processing
01:27:52 - cmdstanpy - INFO - Chain [1] done processing
01:27:52 - cmdstanpy - INFO - Chain [1] start processing
01:27:52 - cmdstanpy - INFO - Chain [1] done processing
01:27:52 - cmdstanpy - INFO - Chain [1] start processing
01:27:52 - cmdstanpy - INFO - Chain [1] done processing
01:27:52 - cmdstanpy - INFO - Chain [1] start processing
01:27:52 - cmdstanpy - INFO - Chain [1] done processing
01:27:53 - cmdstanpy - INFO - Chain [1] start processing
01:27:53 - cmdstanpy - INFO - Chain [1] done processing
01:27:53 - cmdstanpy - INFO - Chain [1] start processing
01:27:53 - cmdstanpy - INFO - Chain [1] done processing
01:27:53 - cmdstanpy - INFO - Chain [1] start processing
01:27:53 - cmdstanpy - INFO - Chain [1] done processing
01:27:53 - cmdstanpy - INFO - Chain [1] start processing
01:27:53 - cmdstanpy - INFO - Chain [1] done processing
01:27:54 - cmdstanpy - INFO - Chain [1] start processing
01:27:54 - cmdstanpy - INFO - Chain [1] done processing
01:27:54 - cmdstanpy - INFO - Chain [1] start processing
01:27:54 - cmdstanpy - INFO - Chain [1] done processing
01:27:54 - cmdstanpy - INFO - Chain [1] start processing
01:27:54 - cmdstanpy - INFO - Chain [1] done processing
01:27:54 - cmdstanpy - INFO - Chain [1] start processing
01:27:55 - cmdstanpy - INFO - Chain [1] done processing
01:27:55 - cmdstanpy - INFO - Chain [1] start processing
01:27:55 - cmdstanpy - INFO - Chain [1] done processing
01:27:55 - cmdstanpy - INFO - Chain [1] start processing
01:27:55 - cmdstanpy - INFO - Chain [1] done processing
01:27:55 - cmdstanpy - INFO - Chain [1] start processing
01:27:55 - cmdstanpy - INFO - Chain [1] done processing
01:27:55 - cmdstanpy - INFO - Chain [1] start processing
01:27:56 - cmdstanpy - INFO - Chain [1] done processing
01:27:56 - cmdstanpy - INFO - Chain [1] start processing
01:27:56 - cmdstanpy - INFO - Chain [1] done processing
01:27:56 - cmdstanpy - INFO - Chain [1] start processing
01:27:56 - cmdstanpy - INFO - Chain [1] done processing
01:27:56 - cmdstanpy - INFO - Chain [1] start processing
01:27:56 - cmdstanpy - INFO - Chain [1] done processing
01:27:57 - cmdstanpy - INFO - Chain [1] start processing
01:27:57 - cmdstanpy - INFO - Chain [1] done processing
01:27:57 - cmdstanpy - INFO - Chain [1] start processing
01:27:57 - cmdstanpy - INFO - Chain [1] done processing
01:27:57 - cmdstanpy - INFO - Chain [1] start processing
01:27:57 - cmdstanpy - INFO - Chain [1] done processing
01:27:57 - cmdstanpy - INFO - Chain [1] start processing
01:27:57 - cmdstanpy - INFO - Chain [1] done processing
01:27:58 - cmdstanpy - INFO - Chain [1] start processing
01:27:58 - cmdstanpy - INFO - Chain [1] done processing
01:27:58 - cmdstanpy - INFO - Chain [1] start processing
01:27:58 - cmdstanpy - INFO - Chain [1] done processing
01:27:58 - cmdstanpy - INFO - Chain [1] start processing
01:27:58 - cmdstanpy - INFO - Chain [1] done processing
01:27:58 - cmdstanpy - INFO - Chain [1] start processing
01:27:59 - cmdstanpy - INFO - Chain [1] done processing
01:27:59 - cmdstanpy - INFO - Chain [1] start processing
01:27:59 - cmdstanpy - INFO - Chain [1] done processing
01:27:59 - cmdstanpy - INFO - Chain [1] start processing
01:27:59 - cmdstanpy - INFO - Chain [1] done processing
01:27:59 - cmdstanpy - INFO - Chain [1] start processing
01:27:59 - cmdstanpy - INFO - Chain [1] done processing
01:28:00 - cmdstanpy - INFO - Chain [1] start processing
01:28:00 - cmdstanpy - INFO - Chain [1] done processing
01:28:00 - cmdstanpy - INFO - Chain [1] start processing
01:28:00 - cmdstanpy - INFO - Chain [1] done processing
01:28:00 - cmdstanpy - INFO - Chain [1] start processing
01:28:00 - cmdstanpy - INFO - Chain [1] done processing
01:28:00 - cmdstanpy - INFO - Chain [1] start processing
01:28:00 - cmdstanpy - INFO - Chain [1] done processing
01:28:01 - cmdstanpy - INFO - Chain [1] start processing
01:28:01 - cmdstanpy - INFO - Chain [1] done processing
01:28:01 - cmdstanpy - INFO - Chain [1] start processing
01:28:01 - cmdstanpy - INFO - Chain [1] done processing
01:28:01 - cmdstanpy - INFO - Chain [1] start processing
01:28:01 - cmdstanpy - INFO - Chain [1] done processing
01:28:01 - cmdstanpy - INFO - Chain [1] start processing
01:28:01 - cmdstanpy - INFO - Chain [1] done processing
01:28:02 - cmdstanpy - INFO - Chain [1] start processing
01:28:02 - cmdstanpy - INFO - Chain [1] done processing
01:28:02 - cmdstanpy - INFO - Chain [1] start processing
01:28:02 - cmdstanpy - INFO - Chain [1] done processing
01:28:02 - cmdstanpy - INFO - Chain [1] start processing
01:28:03 - cmdstanpy - INFO - Chain [1] done processing
01:28:03 - cmdstanpy - INFO - Chain [1] start processing
01:28:03 - cmdstanpy - INFO - Chain [1] done processing
01:28:03 - cmdstanpy - INFO - Chain [1] start processing
01:28:03 - cmdstanpy - INFO - Chain [1] done processing
01:28:04 - cmdstanpy - INFO - Chain [1] start processing
01:28:04 - cmdstanpy - INFO - Chain [1] done processing
01:28:04 - cmdstanpy - INFO - Chain [1] start processing
01:28:04 - cmdstanpy - INFO - Chain [1] done processing
01:28:04 - cmdstanpy - INFO - Chain [1] start processing
01:28:04 - cmdstanpy - INFO - Chain [1] done processing
01:28:05 - cmdstanpy - INFO - Chain [1] start processing
01:28:05 - cmdstanpy - INFO - Chain [1] done processing
01:28:05 - cmdstanpy - INFO - Chain [1] start processing
01:28:05 - cmdstanpy - INFO - Chain [1] done processing
01:28:06 - cmdstanpy - INFO - Chain [1] start processing
01:28:06 - cmdstanpy - INFO - Chain [1] done processing
01:28:06 - cmdstanpy - INFO - Chain [1] start processing
01:28:06 - cmdstanpy - INFO - Chain [1] done processing
01:28:06 - cmdstanpy - INFO - Chain [1] start processing
01:28:07 - cmdstanpy - INFO - Chain [1] done processing
01:28:07 - cmdstanpy - INFO - Chain [1] start processing
01:28:07 - cmdstanpy - INFO - Chain [1] done processing
01:28:07 - cmdstanpy - INFO - Chain [1] start processing
01:28:08 - cmdstanpy - INFO - Chain [1] done processing
01:28:08 - cmdstanpy - INFO - Chain [1] start processing
01:28:08 - cmdstanpy - INFO - Chain [1] done processing
01:28:08 - cmdstanpy - INFO - Chain [1] start processing
01:28:09 - cmdstanpy - INFO - Chain [1] done processing
01:28:09 - cmdstanpy - INFO - Chain [1] start processing
01:28:09 - cmdstanpy - INFO - Chain [1] done processing
01:28:10 - cmdstanpy - INFO - Chain [1] start processing
01:28:10 - cmdstanpy - INFO - Chain [1] done processing
01:28:10 - cmdstanpy - INFO - Chain [1] start processing
01:28:11 - cmdstanpy - INFO - Chain [1] done processing
01:28:11 - cmdstanpy - INFO - Chain [1] start processing
01:28:11 - cmdstanpy - INFO - Chain [1] done processing
01:28:12 - cmdstanpy - INFO - Chain [1] start processing
01:28:12 - cmdstanpy - INFO - Chain [1] done processing
01:28:12 - cmdstanpy - INFO - Chain [1] start processing
01:28:13 - cmdstanpy - INFO - Chain [1] done processing
01:28:13 - cmdstanpy - INFO - Chain [1] start processing
01:28:13 - cmdstanpy - INFO - Chain [1] done processing
01:28:13 - cmdstanpy - INFO - Chain [1] start processing
01:28:13 - cmdstanpy - INFO - Chain [1] done processing
01:28:14 - cmdstanpy - INFO - Chain [1] start processing
01:28:14 - cmdstanpy - INFO - Chain [1] done processing
01:28:14 - cmdstanpy - INFO - Chain [1] start processing
01:28:14 - cmdstanpy - INFO - Chain [1] done processing
01:28:14 - cmdstanpy - INFO - Chain [1] start processing
01:28:15 - cmdstanpy - INFO - Chain [1] done processing
01:28:15 - cmdstanpy - INFO - Chain [1] start processing
01:28:15 - cmdstanpy - INFO - Chain [1] done processing
01:28:15 - cmdstanpy - INFO - Chain [1] start processing
01:28:16 - cmdstanpy - INFO - Chain [1] done processing
01:28:16 - cmdstanpy - INFO - Chain [1] start processing
01:28:16 - cmdstanpy - INFO - Chain [1] done processing
01:28:16 - cmdstanpy - INFO - Chain [1] start processing
01:28:16 - cmdstanpy - INFO - Chain [1] done processing
01:28:17 - cmdstanpy - INFO - Chain [1] start processing
01:28:17 - cmdstanpy - INFO - Chain [1] done processing
01:28:17 - cmdstanpy - INFO - Chain [1] start processing
01:28:18 - cmdstanpy - INFO - Chain [1] done processing
01:28:18 - cmdstanpy - INFO - Chain [1] start processing
01:28:18 - cmdstanpy - INFO - Chain [1] done processing
01:28:19 - cmdstanpy - INFO - Chain [1] start processing
01:28:19 - cmdstanpy - INFO - Chain [1] done processing
01:28:19 - cmdstanpy - INFO - Chain [1] start processing
01:28:20 - cmdstanpy - INFO - Chain [1] done processing
01:28:20 - cmdstanpy - INFO - Chain [1] start processing
01:28:20 - cmdstanpy - INFO - Chain [1] done processing
01:28:21 - cmdstanpy - INFO - Chain [1] start processing
01:28:21 - cmdstanpy - INFO - Chain [1] done processing
01:28:21 - cmdstanpy - INFO - Chain [1] start processing
01:28:21 - cmdstanpy - INFO - Chain [1] done processing
01:28:22 - cmdstanpy - INFO - Chain [1] start processing
01:28:22 - cmdstanpy - INFO - Chain [1] done processing
01:28:22 - cmdstanpy - INFO - Chain [1] start processing
01:28:22 - cmdstanpy - INFO - Chain [1] done processing
01:28:23 - cmdstanpy - INFO - Chain [1] start processing
01:28:23 - cmdstanpy - INFO - Chain [1] done processing
01:28:23 - cmdstanpy - INFO - Chain [1] start processing
01:28:23 - cmdstanpy - INFO - Chain [1] done processing
01:28:23 - cmdstanpy - INFO - Chain [1] start processing
01:28:24 - cmdstanpy - INFO - Chain [1] done processing
01:28:24 - cmdstanpy - INFO - Chain [1] start processing
01:28:24 - cmdstanpy - INFO - Chain [1] done processing
01:28:24 - cmdstanpy - INFO - Chain [1] start processing

Результаты прогнозов Prophet на 3 месяца:

,Регион,Test start,Test end,RMSE,MAE,MAPE_%,Forecast,Actual
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,63.75,56.52,10.84,"[506.29, 540.82, 593.32]","[553.23, 566.96, 496.85]"
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,154.64,123.33,24.94,"[547.69, 601.94, 734.21]","[566.96, 496.85, 488.59]"
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,442.12,352.84,72.98,"[596.11, 726.91, 1201.0]","[496.85, 488.59, 480.05]"
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,418.36,320.44,69.49,"[708.9, 1168.36, 316.42]","[488.59, 480.05, 263.72]"
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,364.46,222.68,48.43,"[1110.38, 297.84, 344.38]","[480.05, 263.72, 340.79]"
...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,0.82,0.70,58.72,"[0.22, 0.4, 0.58]","[0.4, 1.1, 1.8]"
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,0.82,0.67,49.33,"[0.37, 0.58, 0.46]","[1.1, 1.8, 0.4]"
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,0.66,0.46,38.65,"[0.68, 0.55, 0.58]","[1.8, 0.4, 0.7]"
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,0.15,0.15,46.80,"[0.56, 0.59, 0.03]","[0.4, 0.7, 0.2]"
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,0.17,0.17,39.38,"[0.58, 0.03, 1.19]","[0.7, 0.2, 1.4]"

Средние метрики Prophet по регионам (rolling-3):

                            Регион   RMSE    MAE  MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ 190.30 147.15   31.66
1              АКТЮБИНСКАЯ ОБЛАСТЬ  51.28  42.91   59.60
2              АЛМАТИНСКАЯ ОБЛАСТЬ  98.59  90.38  308.04
3               АТЫРАУСКАЯ ОБЛАСТЬ   0.22   0.13     NaN
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  75.66  68.49   19.05
5                          ГАЛМАТЫ   0.37   0.21     NaN
6                          ГАСТАНА   0.03   0.02     NaN
7                         ГШЫМКЕНТ   4.07   3.21   58.29
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ  15.72  13.11   40.19
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  27.04  24.13   13.42
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ 170.84 152.81   15.19
11            КОСТАНАЙСКАЯ ОБЛАСТЬ 124.58 109.19   33.40
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ  12.52   8.36   62.14
13           МАНГИСТАУСКАЯ ОБЛАСТЬ   0.00   0.00     NaN
14                    ОБЛАСТЬ АБАЙ 132.33  87.35   75.97
15                  ОБЛАСТЬ ЖЕТІСУ 712.77 503.12  226.78
16                  ОБЛАСТЬ ҰЛЫТАУ 613.40 354.66     NaN
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ 365.37 319.57   20.42
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 783.34 667.68   43.71
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ   1.85   1.48   61.93

In [8]:
# Переименуем колонки с MAPE, чтобы было понятно, к какому методу относятся
hw = final_hw.rename(columns={"MAPE_%": "MAPE_HW"})
sar = final_sarima.rename(columns={"MAPE_%": "MAPE_SARIMA"})
pr  = final_prophet.rename(columns={"MAPE_%": "MAPE_Prophet"})

# Мёрджим по региону
summary = (
    hw[["Регион", "MAPE_HW"]]
    .merge(sar[["Регион", "MAPE_SARIMA"]], on="Регион")
    .merge(pr[["Регион", "MAPE_Prophet"]], on="Регион")
)

# Определяем для каждой строки, какой столбец MAPE минимален
# idxmin вернёт название столбца с минимальным значением
summary["Best_method"] = summary[["MAPE_HW","MAPE_SARIMA","MAPE_Prophet"]] \
                           .idxmin(axis=1) \
                           .str.replace("MAPE_","")  # убираем префикс для красоты

# Если нужно, можно сразу отсортировать
# summary = summary.sort_values("Best_method")

# допустим, у вас уже есть summary
summary = summary.round({
    "MAPE_HW": 2,
    "MAPE_SARIMA": 2,
    "MAPE_Prophet": 2
})

# Готово!
print(summary.to_string(index=False))
summary.to_excel("results/Свиньи - Лучшие модели.xlsx", index=False)

                        Регион  MAPE_HW               MAPE_SARIMA  MAPE_Prophet Best_method
           АКМОЛИНСКАЯ ОБЛАСТЬ    35.99                     34.23         31.66     Prophet
           АКТЮБИНСКАЯ ОБЛАСТЬ    23.21                     17.36         59.60      SARIMA
           АЛМАТИНСКАЯ ОБЛАСТЬ   193.80                    196.48        308.04          HW
            АТЫРАУСКАЯ ОБЛАСТЬ      NaN  156015071304232927232.00           NaN      SARIMA
ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ    27.16                     34.98         19.05     Prophet
                       ГАЛМАТЫ      NaN    4753769302223073280.00           NaN      SARIMA
                       ГАСТАНА      NaN  108808626061915291648.00           NaN      SARIMA
                      ГШЫМКЕНТ    96.04                     38.45         58.29      SARIMA
            ЖАМБЫЛСКАЯ ОБЛАСТЬ    41.37                     24.22         40.19      SARIMA
 ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ    11.99                     11.33         13.42      SARIMA
        КАРАГАНДИНСКАЯ ОБЛАСТЬ    15.53                     16.62         15.19     Prophet
          КОСТАНАЙСКАЯ ОБЛАСТЬ    29.30                     25.73         33.40      SARIMA
        КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ    31.71                     28.63         62.14      SARIMA
         МАНГИСТАУСКАЯ ОБЛАСТЬ      NaN     356635791936596160.00           NaN      SARIMA
                  ОБЛАСТЬ АБАЙ    34.83                     38.66         75.97          HW
                ОБЛАСТЬ ЖЕТІСУ    58.23                    168.03        226.78          HW
                ОБЛАСТЬ ҰЛЫТАУ      NaN 2304214110064169451520.00           NaN      SARIMA
          ПАВЛОДАРСКАЯ ОБЛАСТЬ    16.26                     14.41         20.42      SARIMA
  СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ    24.42                     16.90         43.71      SARIMA
         ТУРКЕСТАНСКАЯ ОБЛАСТЬ   107.47                     71.05         61.93     Prophet