In [1]:
# --- 1. Импорты и общие настройки ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from pmdarima import auto_arima
from statsmodels.tsa.statespace.sarimax import SARIMAX
from prophet import Prophet  # pip install prophet
from sklearn.metrics import mean_squared_error, mean_absolute_error
import warnings
pd.options.display.float_format = '{:.2f}'.format
warnings.filterwarnings("ignore")
# plt.style.use("seaborn-whitegrid")

In [2]:
# --- 2. Загрузка данных ---
# df должен содержать столбцы: "Регион", "Период" (YYYY-MM), и целевой столбец с показателем.
df = pd.read_excel("Датасет по верблюдам.xlsx")
df["Период"] = pd.to_datetime(df["Период"], format="%Y-%m")
df.sample(10)

                             Регион     Период  Верблюды
1512         КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ 2017-06-01      0.00
1210  ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ 2024-01-01      2.40
1802                 ОБЛАСТЬ ЖЕТІСУ 2024-09-01      1.20
265             АЛМАТИНСКАЯ ОБЛАСТЬ 2015-12-01     46.78
143             АКТЮБИНСКАЯ ОБЛАСТЬ 2016-05-01    221.89
1233         КАРАГАНДИНСКАЯ ОБЛАСТЬ 2015-05-01      3.45
379             АЛМАТИНСКАЯ ОБЛАСТЬ 2025-06-01     41.60
1694          МАНГИСТАУСКАЯ ОБЛАСТЬ 2022-01-01    172.86
645                         ГАЛМАТЫ 2015-11-01      0.00
886                         ГАСТАНА 2025-05-01      0.00

In [3]:
regions = df['Регион'].unique()
target   = "Верблюды"
horizon  = 3
epsilon = 1e-6

In [4]:
first_test = pd.to_datetime("2024-08-01")
last_possible = df["Период"].max() - pd.DateOffset(months=horizon-1)
test_starts = pd.date_range(first_test, last_possible, freq="MS")

## Holw-Winter's (log)

In [5]:
results_hw = []
for region in regions:
    ts = (df[df["Регион"] == region]
          .set_index("Период")[target]
          .dropna()
          .sort_index())
    if len(ts) < 24:
        print(f"{region}: всего {len(ts)} мес. — сезонный Holt-Winter's невозможен.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        # формируем train / test
        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]

        # пропускаем, если недостаточно данных или неполный test
        if len(train) < 24 or len(test) < horizon:
            continue

        # обучаем модель
        train_log = np.log1p(train)

        hw_log = ExponentialSmoothing(
            train_log,
            seasonal="add",
            seasonal_periods=12
        ).fit(optimized=True)

        # прогноз и метрики
        fc_log = hw_log.forecast(horizon)
        fc = np.expm1(fc_log) 
        # fc   = model.forecast(horizon)
        rmse = np.sqrt(mean_squared_error(test, fc))
        mae  = mean_absolute_error(test, fc)
        mape = (np.abs((test - fc) / test).mean()) * 100

        results_hw.append({
            "Регион":      region,
            "Test start":  test_start.strftime("%Y-%m"),
            "Test end":    test_end.strftime("%Y-%m"),
            "Forecast":    [x.round(2) for x in list(fc.values)],
            "Actual":      [y.round(2) for y in list(test.values)],
            "RMSE":        rmse,
            "MAE":         mae,
            "MAPE_%":      mape
        })

# 4) Усреднение по всем скользящим окнам для каждого региона
res_hw = pd.DataFrame(results_hw)
res_hw.to_excel("results/Верблюды - Результаты прогнозов ХВ.xlsx", index=False)

print("Результаты прогнозов HW на 3 месяца:")

display(res_hw)

final_hw = (
    res_hw
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_hw.to_excel("results/Верблюды - Результаты прогнозов ХВ средние.xlsx", index=False)
print("Средние метрики Holt–Winter's по регионам (rolling-3):")
display(final_hw)

Результаты прогнозов HW на 3 месяца:

,Регион,Test start,Test end,Forecast,Actual,RMSE,MAE,MAPE_%
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,"[0.15, -0.04, -0.09]","[0.0, 0.0, 0.0]",0.10,0.09,inf
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,"[-0.05, -0.1, 0.08]","[0.0, 0.0, 0.0]",0.08,0.08,inf
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,"[-0.1, 0.08, 0.36]","[0.0, 0.0, 0.0]",0.22,0.18,inf
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,"[0.09, 0.37, -0.09]","[0.0, 0.0, 0.0]",0.23,0.18,inf
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,"[0.37, -0.1, -0.05]","[0.0, 0.0, 0.0]",0.22,0.17,inf
...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,"[94.74, 83.49, 127.14]","[69.2, 60.13, 93.1]",28.03,27.65,37.44
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,"[74.76, 114.06, 103.04]","[60.13, 93.1, 85.8]",17.80,17.61,22.31
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,"[109.41, 98.89, 105.34]","[93.1, 85.8, 96.61]",13.08,12.71,13.94
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,"[96.43, 102.75, 105.66]","[85.8, 96.61, 105.0]",7.10,5.81,6.46
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,"[101.01, 103.84, 43.52]","[96.61, 105.0, 44.1]",2.65,2.04,2.32

Средние метрики Holt–Winter's по регионам (rolling-3):

                            Регион   RMSE    MAE  MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ   0.13   0.11     NaN
1              АКТЮБИНСКАЯ ОБЛАСТЬ   5.03   4.04    2.23
2              АЛМАТИНСКАЯ ОБЛАСТЬ  15.92  13.73   86.55
3               АТЫРАУСКАЯ ОБЛАСТЬ 107.89  75.17   13.84
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   1.41   1.11     NaN
5                          ГАЛМАТЫ   0.00   0.00     NaN
6                          ГАСТАНА   0.04   0.03     NaN
7                         ГШЫМКЕНТ   0.00   0.00     NaN
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ   2.39   2.00    7.23
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   1.58   1.22    9.20
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ   3.14   2.04     NaN
11            КОСТАНАЙСКАЯ ОБЛАСТЬ   0.25   0.16     NaN
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ 198.88 126.70   44.56
13           МАНГИСТАУСКАЯ ОБЛАСТЬ 143.84 115.97   32.34
14                    ОБЛАСТЬ АБАЙ   2.90   2.33     NaN
15                  ОБЛАСТЬ ЖЕТІСУ   4.59   2.82     NaN
16                  ОБЛАСТЬ ҰЛЫТАУ   0.03   0.02     NaN
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ   0.18   0.15     NaN
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ   0.04   0.03     NaN
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ  85.46  58.47   20.88

In [6]:
res_hw[res_hw['Регион'] == 'ПАВЛОДАРСКАЯ ОБЛАСТЬ']

,Регион,Test start,Test end,Forecast,Actual,RMSE,MAE,MAPE_%
170,ПАВЛОДАРСКАЯ ОБЛАСТЬ,2024-08,2024-10,"[0.07, 0.13, -0.0]","[0.4, 0.0, 0.0]",0.21,0.15,inf
171,ПАВЛОДАРСКАЯ ОБЛАСТЬ,2024-09,2024-11,"[0.13, -0.0, 0.15]","[0.0, 0.0, 0.0]",0.11,0.09,inf
172,ПАВЛОДАРСКАЯ ОБЛАСТЬ,2024-10,2024-12,"[-0.0, 0.15, 0.38]","[0.0, 0.0, 0.0]",0.24,0.18,inf
173,ПАВЛОДАРСКАЯ ОБЛАСТЬ,2024-11,2025-01,"[0.15, 0.38, 0.15]","[0.0, 0.0, 0.0]",0.25,0.23,inf
174,ПАВЛОДАРСКАЯ ОБЛАСТЬ,2024-12,2025-02,"[0.38, 0.15, 0.1]","[0.0, 0.0, 0.0]",0.24,0.21,inf
175,ПАВЛОДАРСКАЯ ОБЛАСТЬ,2025-01,2025-03,"[0.15, 0.1, 0.07]","[0.0, 0.0, 0.0]",0.11,0.11,inf
176,ПАВЛОДАРСКАЯ ОБЛАСТЬ,2025-02,2025-04,"[0.1, 0.07, 0.35]","[0.0, 0.0, 0.0]",0.21,0.17,inf
177,ПАВЛОДАРСКАЯ ОБЛАСТЬ,2025-03,2025-05,"[0.07, 0.35, 0.07]","[0.0, 0.0, 0.0]",0.21,0.16,inf
178,ПАВЛОДАРСКАЯ ОБЛАСТЬ,2025-04,2025-06,"[0.35, 0.07, 0.08]","[0.0, 0.0, 0.0]",0.21,0.17,inf
179,ПАВЛОДАРСКАЯ ОБЛАСТЬ,2025-05,2025-07,"[0.02, 0.03, -0.04]","[0.0, 0.0, 0.0]",0.03,0.03,inf

## SARIMA

In [7]:
results_sarima = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    ts = ts + epsilon
    ts_log = np.log(ts)

    if len(ts_log) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. для авто-ARIMA, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train_log = ts_log[ts_log.index < test_start]
        test_log  = ts_log[(ts_log.index >= test_start) & (ts_log.index <= test_end)]
        if len(train_log) < 12 + horizon or len(test_log) < horizon:
            continue

        # автоподбор на лог-данных
        use_seasonal = len(train_log) >= 2 * 12

        sarima_log = auto_arima(
            train_log,
            seasonal=use_seasonal,
            m=12 if use_seasonal else 1,
            D=1 if use_seasonal else 0,      # фиксируем порядок сезонной разности
            seasonal_test=None,               # пропустить nsdiffs
            boxcox=True,
            stepwise=True,
            suppress_warnings=True,
            error_action="ignore"
        )
      
        # прогноз в лог-шкале
        fc_log = sarima_log.predict(n_periods=horizon, return_conf_int=False)

        # возвращаем прогноз в исходные единицы
        fc = np.exp(fc_log) - epsilon
        actual = np.exp(test_log.values) - epsilon  # но exp(log(x)) == x

        # метрики на исходном уровне
        rmse = np.sqrt(mean_squared_error(actual, fc))
        mae  = mean_absolute_error(actual, fc)
        mape = (np.abs((actual - fc) / actual).mean()) * 100

        results_sarima.append({
            "Регион":         region,
            "Test start":     test_start.strftime("%Y-%m"),
            "Test end":       test_end.strftime("%Y-%m"),
            "order":          sarima_log.order,
            "seasonal_order": sarima_log.seasonal_order,
            "RMSE":           round(rmse,2),
            "MAE":            round(mae,2),
            "MAPE_%":         round(mape,2),
            "Forecast":       [round(x,2) for x in fc],
            "Actual":         [round(y,2) for y in actual]
        })
# формируем DataFrame с результатами
res_sarima = pd.DataFrame(results_sarima)
res_sarima.to_excel("results/Верблюды - Результаты прогнозов SARIMA.xlsx", index=False)
print("Результаты прогнозов SARIMA на 3 месяца:")

display(res_sarima)

final_sarima = (
    res_sarima
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_sarima.to_excel("results/Верблюды - Результаты прогнозов SARIMA средние.xlsx", index=False)
print("Средние метрики SARIMA по регионам (rolling-3):")
display(final_sarima)

Результаты прогнозов SARIMA на 3 месяца:

,Регион,Test start,Test end,order,seasonal_order,RMSE,MAE,MAPE_%,Forecast,Actual
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,"(0, 0, 1)","(0, 1, 1, 12)",0.00,0.00,156767816281293536.00,"[0.0, -0.0, -0.0]","[0.0, 0.0, 0.0]"
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,"(0, 0, 1)","(0, 1, 1, 12)",0.00,0.00,164102929071652832.00,"[-0.0, -0.0, -0.0]","[0.0, 0.0, 0.0]"
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,"(0, 0, 1)","(0, 1, 1, 12)",0.00,0.00,301383896929273728.00,"[-0.0, -0.0, 0.0]","[0.0, 0.0, 0.0]"
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,"(0, 0, 1)","(0, 1, 1, 12)",0.00,0.00,311009655718454144.00,"[-0.0, 0.0, -0.0]","[0.0, 0.0, 0.0]"
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,"(0, 0, 1)","(0, 1, 1, 12)",0.00,0.00,288628032405297024.00,"[0.0, -0.0, 0.0]","[0.0, 0.0, 0.0]"
...,...,...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,"(3, 0, 0)","(0, 1, 0, 12)",20.83,19.61,25.83,"[82.9, 75.78, 122.57]","[69.2, 60.13, 93.1]"
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,"(3, 0, 0)","(0, 1, 0, 12)",24.32,23.09,28.62,"[74.49, 115.01, 118.79]","[60.13, 93.1, 85.8]"
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,"(2, 0, 2)","(0, 1, 0, 12)",37.03,34.84,38.63,"[116.25, 138.04, 125.73]","[93.1, 85.8, 96.61]"
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,"(3, 0, 0)","(0, 1, 0, 12)",13.17,8.87,10.14,"[108.35, 100.02, 105.64]","[85.8, 96.61, 105.0]"
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,"(3, 0, 0)","(0, 1, 0, 12)",5.24,4.41,7.28,"[97.08, 99.25, 37.09]","[96.61, 105.0, 44.1]"

Средние метрики SARIMA по регионам (rolling-3):

,Регион,RMSE,MAE,MAPE_%
0,АКМОЛИНСКАЯ ОБЛАСТЬ,0.00,0.00,234298811075384160.00
1,АКТЮБИНСКАЯ ОБЛАСТЬ,4.62,3.77,2.34
2,АЛМАТИНСКАЯ ОБЛАСТЬ,15.75,13.72,88.69
3,АТЫРАУСКАЯ ОБЛАСТЬ,122.91,88.97,16.87
4,ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,0.74,0.53,4481981798858405445632.00
5,ГАЛМАТЫ,1.00,1.00,236118088025158109364224.00
6,ГАСТАНА,0.00,0.00,0.00
7,ГШЫМКЕНТ,1.00,1.00,236118088025158109364224.00
8,ЖАМБЫЛСКАЯ ОБЛАСТЬ,2.31,1.89,7.06
9,ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,2.97,2.43,22.82
10,КАРАГАНДИНСКАЯ ОБЛАСТЬ,4.26,3.04,326876682879239821721600.00
11,КОСТАНАЙСКАЯ ОБЛАСТЬ,0.21,0.12,35872498088695361536.00
12,КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ,200.76,132.30,46.28
13,МАНГИСТАУСКАЯ ОБЛАСТЬ,172.36,129.42,43.24
14,ОБЛАСТЬ АБАЙ,958.42,553.86,3075002658089149136896.00
15,ОБЛАСТЬ ЖЕТІСУ,21668.28,12511.37,303175941370688064.00
16,ОБЛАСТЬ ҰЛЫТАУ,0.00,0.00,15.00
17,ПАВЛОДАРСКАЯ ОБЛАСТЬ,0.02,0.01,4878482432353040384.00
18,СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,0.00,0.00,3116639736815846912.00
19,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,90.66,62.72,23.49

## Facebook Prophet

In [8]:
results_prophet = []

for region in regions:
    ts = (
        df[df["Регион"] == region]
        .set_index("Период")[target]
        .dropna()
        .sort_index()
    )
    if len(ts) < 12 + horizon:
        print(f"{region}: менее {12+horizon} мес. данных, пропускаем.")
        continue

    for test_start in test_starts:
        test_end = test_start + pd.DateOffset(months=horizon) - pd.DateOffset(days=1)

        train = ts[ts.index < test_start]
        test  = ts[(ts.index >= test_start) & (ts.index <= test_end)]
        if len(train) < 12 + horizon or len(test) < horizon:
            continue

        # Подготовка данных для Prophet
#         df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
# # подготовка для одного региона
        df_prophet = train.reset_index().rename(columns={"Период":"ds", target:"y"})
        df_prophet["y"] = np.log(df_prophet["y"] + epsilon)

        m = Prophet()
        m.fit(df_prophet)

        future = m.make_future_dataframe(periods=horizon, freq="MS")
        forecast = m.predict(future)

        # берем только прогнозные точки
        yhat_log = forecast["yhat"].values[-horizon:]
        fc = np.exp(yhat_log) - epsilon

        # m = Prophet()
        # m.fit(df_prophet)

        # # Создаем DataFrame будущих дат и делаем прогноз
        # # future = m.make_future_dataframe(periods=horizon, freq="MS")
        # # forecast = m.predict(future)

        # # Отбираем только наши горизонты
        # fc = forecast.set_index("ds")["yhat"].loc[test.index].values
        actual = test.values

        # Расчет метрик
        rmse  = np.sqrt(mean_squared_error(actual, fc))
        mae   = mean_absolute_error(actual, fc)
        mape  = (np.abs((actual - fc) / actual).mean()) * 100

        results_prophet.append({
            "Регион":     region,
            "Test start": test_start.strftime("%Y-%m"),
            "Test end":   test_end.strftime("%Y-%m"),
            "RMSE":       round(rmse, 2),
            "MAE":        round(mae, 2),
            "MAPE_%":     round(mape, 2),
            "Forecast":   [round(x, 2) for x in fc],
            "Actual":     [round(x, 2) for x in actual]
        })

# Собираем результаты в DataFrame
res_prophet = pd.DataFrame(results_prophet)
res_prophet.to_excel("results/Верблюды - Результаты прогнозов Prophet.xlsx", index=False)
print("Результаты прогнозов Prophet на 3 месяца:")
display(res_prophet)

final_prophet = (
    res_prophet
    .groupby("Регион")[["RMSE","MAE","MAPE_%"]]
    .mean()
    .round(2)
    .reset_index()
)
final_prophet.to_excel("results/Верблюды - Результаты прогнозов Prophet средние.xlsx", index=False)
print("Средние метрики Prophet по регионам (rolling-3):")
display(final_prophet)

12:29:06 - cmdstanpy - INFO - Chain [1] start processing
12:29:08 - cmdstanpy - INFO - Chain [1] done processing
12:29:08 - cmdstanpy - INFO - Chain [1] start processing
12:29:08 - cmdstanpy - INFO - Chain [1] done processing
12:29:08 - cmdstanpy - INFO - Chain [1] start processing
12:29:08 - cmdstanpy - INFO - Chain [1] done processing
12:29:09 - cmdstanpy - INFO - Chain [1] start processing
12:29:09 - cmdstanpy - INFO - Chain [1] done processing
12:29:09 - cmdstanpy - INFO - Chain [1] start processing
12:29:09 - cmdstanpy - INFO - Chain [1] done processing
12:29:10 - cmdstanpy - INFO - Chain [1] start processing
12:29:10 - cmdstanpy - INFO - Chain [1] done processing
12:29:10 - cmdstanpy - INFO - Chain [1] start processing
12:29:10 - cmdstanpy - INFO - Chain [1] done processing
12:29:11 - cmdstanpy - INFO - Chain [1] start processing
12:29:11 - cmdstanpy - INFO - Chain [1] done processing
12:29:11 - cmdstanpy - INFO - Chain [1] start processing
12:29:11 - cmdstanpy - INFO - Chain [1] done processing
12:29:12 - cmdstanpy - INFO - Chain [1] start processing
12:29:12 - cmdstanpy - INFO - Chain [1] done processing
12:29:12 - cmdstanpy - INFO - Chain [1] start processing
12:29:12 - cmdstanpy - INFO - Chain [1] done processing
12:29:12 - cmdstanpy - INFO - Chain [1] start processing
12:29:12 - cmdstanpy - INFO - Chain [1] done processing
12:29:13 - cmdstanpy - INFO - Chain [1] start processing
12:29:13 - cmdstanpy - INFO - Chain [1] done processing
12:29:13 - cmdstanpy - INFO - Chain [1] start processing
12:29:13 - cmdstanpy - INFO - Chain [1] done processing
12:29:14 - cmdstanpy - INFO - Chain [1] start processing
12:29:14 - cmdstanpy - INFO - Chain [1] done processing
12:29:14 - cmdstanpy - INFO - Chain [1] start processing
12:29:14 - cmdstanpy - INFO - Chain [1] done processing
12:29:14 - cmdstanpy - INFO - Chain [1] start processing
12:29:14 - cmdstanpy - INFO - Chain [1] done processing
12:29:15 - cmdstanpy - INFO - Chain [1] start processing
12:29:15 - cmdstanpy - INFO - Chain [1] done processing
12:29:15 - cmdstanpy - INFO - Chain [1] start processing
12:29:15 - cmdstanpy - INFO - Chain [1] done processing
12:29:15 - cmdstanpy - INFO - Chain [1] start processing
12:29:15 - cmdstanpy - INFO - Chain [1] done processing
12:29:15 - cmdstanpy - INFO - Chain [1] start processing
12:29:16 - cmdstanpy - INFO - Chain [1] done processing
12:29:16 - cmdstanpy - INFO - Chain [1] start processing
12:29:16 - cmdstanpy - INFO - Chain [1] done processing
12:29:16 - cmdstanpy - INFO - Chain [1] start processing
12:29:16 - cmdstanpy - INFO - Chain [1] done processing
12:29:16 - cmdstanpy - INFO - Chain [1] start processing
12:29:16 - cmdstanpy - INFO - Chain [1] done processing
12:29:17 - cmdstanpy - INFO - Chain [1] start processing
12:29:17 - cmdstanpy - INFO - Chain [1] done processing
12:29:17 - cmdstanpy - INFO - Chain [1] start processing
12:29:17 - cmdstanpy - INFO - Chain [1] done processing
12:29:17 - cmdstanpy - INFO - Chain [1] start processing
12:29:17 - cmdstanpy - INFO - Chain [1] done processing
12:29:17 - cmdstanpy - INFO - Chain [1] start processing
12:29:18 - cmdstanpy - INFO - Chain [1] done processing
12:29:18 - cmdstanpy - INFO - Chain [1] start processing
12:29:18 - cmdstanpy - INFO - Chain [1] done processing
12:29:18 - cmdstanpy - INFO - Chain [1] start processing
12:29:18 - cmdstanpy - INFO - Chain [1] done processing
12:29:18 - cmdstanpy - INFO - Chain [1] start processing
12:29:18 - cmdstanpy - INFO - Chain [1] done processing
12:29:19 - cmdstanpy - INFO - Chain [1] start processing
12:29:19 - cmdstanpy - INFO - Chain [1] done processing
12:29:19 - cmdstanpy - INFO - Chain [1] start processing
12:29:19 - cmdstanpy - INFO - Chain [1] done processing
12:29:20 - cmdstanpy - INFO - Chain [1] start processing
12:29:20 - cmdstanpy - INFO - Chain [1] done processing
12:29:20 - cmdstanpy - INFO - Chain [1] start processing
12:29:20 - cmdstanpy - INFO - Chain [1] done processing
12:29:21 - cmdstanpy - INFO - Chain [1] start processing
12:29:21 - cmdstanpy - INFO - Chain [1] done processing
12:29:21 - cmdstanpy - INFO - Chain [1] start processing
12:29:21 - cmdstanpy - INFO - Chain [1] done processing
12:29:22 - cmdstanpy - INFO - Chain [1] start processing
12:29:22 - cmdstanpy - INFO - Chain [1] done processing
12:29:22 - cmdstanpy - INFO - Chain [1] start processing
12:29:22 - cmdstanpy - INFO - Chain [1] done processing
12:29:23 - cmdstanpy - INFO - Chain [1] start processing
12:29:23 - cmdstanpy - INFO - Chain [1] done processing
12:29:23 - cmdstanpy - INFO - Chain [1] start processing
12:29:24 - cmdstanpy - INFO - Chain [1] done processing
12:29:24 - cmdstanpy - INFO - Chain [1] start processing
12:29:24 - cmdstanpy - INFO - Chain [1] done processing
12:29:24 - cmdstanpy - INFO - Chain [1] start processing
12:29:25 - cmdstanpy - INFO - Chain [1] done processing
12:29:25 - cmdstanpy - INFO - Chain [1] start processing
12:29:25 - cmdstanpy - INFO - Chain [1] done processing
12:29:25 - cmdstanpy - INFO - Chain [1] start processing
12:29:26 - cmdstanpy - INFO - Chain [1] done processing
12:29:26 - cmdstanpy - INFO - Chain [1] start processing
12:29:26 - cmdstanpy - INFO - Chain [1] done processing
12:29:27 - cmdstanpy - INFO - Chain [1] start processing
12:29:27 - cmdstanpy - INFO - Chain [1] done processing
12:29:27 - cmdstanpy - INFO - Chain [1] start processing
12:29:28 - cmdstanpy - INFO - Chain [1] done processing
12:29:28 - cmdstanpy - INFO - Chain [1] start processing
12:29:28 - cmdstanpy - INFO - Chain [1] done processing
12:29:29 - cmdstanpy - INFO - Chain [1] start processing
12:29:29 - cmdstanpy - INFO - Chain [1] done processing
12:29:32 - cmdstanpy - INFO - Chain [1] start processing
12:29:32 - cmdstanpy - INFO - Chain [1] done processing
12:29:32 - cmdstanpy - INFO - Chain [1] start processing
12:29:32 - cmdstanpy - INFO - Chain [1] done processing
12:29:33 - cmdstanpy - INFO - Chain [1] start processing
12:29:33 - cmdstanpy - INFO - Chain [1] done processing
12:29:33 - cmdstanpy - INFO - Chain [1] start processing
12:29:33 - cmdstanpy - INFO - Chain [1] done processing
12:29:34 - cmdstanpy - INFO - Chain [1] start processing
12:29:34 - cmdstanpy - INFO - Chain [1] done processing
12:29:34 - cmdstanpy - INFO - Chain [1] start processing
12:29:34 - cmdstanpy - INFO - Chain [1] done processing
12:29:35 - cmdstanpy - INFO - Chain [1] start processing
12:29:35 - cmdstanpy - INFO - Chain [1] done processing
12:29:35 - cmdstanpy - INFO - Chain [1] start processing
12:29:35 - cmdstanpy - INFO - Chain [1] done processing
12:29:36 - cmdstanpy - INFO - Chain [1] start processing
12:29:36 - cmdstanpy - INFO - Chain [1] done processing
12:29:37 - cmdstanpy - INFO - Chain [1] start processing
12:29:37 - cmdstanpy - INFO - Chain [1] done processing
12:29:41 - cmdstanpy - INFO - Chain [1] start processing
12:29:41 - cmdstanpy - INFO - Chain [1] done processing
12:29:42 - cmdstanpy - INFO - Chain [1] start processing
12:29:42 - cmdstanpy - INFO - Chain [1] done processing
12:29:42 - cmdstanpy - INFO - Chain [1] start processing
12:29:42 - cmdstanpy - INFO - Chain [1] done processing
12:29:43 - cmdstanpy - INFO - Chain [1] start processing
12:29:43 - cmdstanpy - INFO - Chain [1] done processing
12:29:43 - cmdstanpy - INFO - Chain [1] start processing
12:29:43 - cmdstanpy - INFO - Chain [1] done processing
12:29:44 - cmdstanpy - INFO - Chain [1] start processing
12:29:44 - cmdstanpy - INFO - Chain [1] done processing
12:29:44 - cmdstanpy - INFO - Chain [1] start processing
12:29:44 - cmdstanpy - INFO - Chain [1] done processing
12:29:45 - cmdstanpy - INFO - Chain [1] start processing
12:29:45 - cmdstanpy - INFO - Chain [1] done processing
12:29:45 - cmdstanpy - INFO - Chain [1] start processing
12:29:45 - cmdstanpy - INFO - Chain [1] done processing
12:29:46 - cmdstanpy - INFO - Chain [1] start processing
12:29:46 - cmdstanpy - INFO - Chain [1] done processing
12:29:46 - cmdstanpy - INFO - Chain [1] start processing
12:29:47 - cmdstanpy - INFO - Chain [1] done processing
12:29:47 - cmdstanpy - INFO - Chain [1] start processing
12:29:47 - cmdstanpy - INFO - Chain [1] done processing
12:29:48 - cmdstanpy - INFO - Chain [1] start processing
12:29:48 - cmdstanpy - INFO - Chain [1] done processing
12:29:48 - cmdstanpy - INFO - Chain [1] start processing
12:29:48 - cmdstanpy - INFO - Chain [1] done processing
12:29:48 - cmdstanpy - INFO - Chain [1] start processing
12:29:49 - cmdstanpy - INFO - Chain [1] done processing
12:29:49 - cmdstanpy - INFO - Chain [1] start processing
12:29:49 - cmdstanpy - INFO - Chain [1] done processing
12:29:49 - cmdstanpy - INFO - Chain [1] start processing
12:29:49 - cmdstanpy - INFO - Chain [1] done processing
12:29:50 - cmdstanpy - INFO - Chain [1] start processing
12:29:50 - cmdstanpy - INFO - Chain [1] done processing
12:29:50 - cmdstanpy - INFO - Chain [1] start processing
12:29:50 - cmdstanpy - INFO - Chain [1] done processing
12:29:51 - cmdstanpy - INFO - Chain [1] start processing
12:29:51 - cmdstanpy - INFO - Chain [1] done processing
12:29:51 - cmdstanpy - INFO - Chain [1] start processing
12:29:51 - cmdstanpy - INFO - Chain [1] done processing
12:29:52 - cmdstanpy - INFO - Chain [1] start processing
12:29:52 - cmdstanpy - INFO - Chain [1] done processing
12:29:52 - cmdstanpy - INFO - Chain [1] start processing
12:29:53 - cmdstanpy - INFO - Chain [1] done processing
12:29:53 - cmdstanpy - INFO - Chain [1] start processing
12:29:53 - cmdstanpy - INFO - Chain [1] done processing
12:29:54 - cmdstanpy - INFO - Chain [1] start processing
12:29:54 - cmdstanpy - INFO - Chain [1] done processing
12:29:54 - cmdstanpy - INFO - Chain [1] start processing
12:29:54 - cmdstanpy - INFO - Chain [1] done processing
12:29:55 - cmdstanpy - INFO - Chain [1] start processing
12:29:55 - cmdstanpy - INFO - Chain [1] done processing
12:29:55 - cmdstanpy - INFO - Chain [1] start processing
12:29:55 - cmdstanpy - INFO - Chain [1] done processing
12:29:56 - cmdstanpy - INFO - Chain [1] start processing
12:29:56 - cmdstanpy - INFO - Chain [1] done processing
12:29:57 - cmdstanpy - INFO - Chain [1] start processing
12:29:57 - cmdstanpy - INFO - Chain [1] done processing
12:29:57 - cmdstanpy - INFO - Chain [1] start processing
12:29:57 - cmdstanpy - INFO - Chain [1] done processing
12:29:58 - cmdstanpy - INFO - Chain [1] start processing
12:29:58 - cmdstanpy - INFO - Chain [1] done processing
12:29:59 - cmdstanpy - INFO - Chain [1] start processing
12:29:59 - cmdstanpy - INFO - Chain [1] done processing
12:29:59 - cmdstanpy - INFO - Chain [1] start processing
12:29:59 - cmdstanpy - INFO - Chain [1] done processing
12:30:00 - cmdstanpy - INFO - Chain [1] start processing
12:30:00 - cmdstanpy - INFO - Chain [1] done processing
12:30:01 - cmdstanpy - INFO - Chain [1] start processing
12:30:01 - cmdstanpy - INFO - Chain [1] done processing
12:30:01 - cmdstanpy - INFO - Chain [1] start processing
12:30:01 - cmdstanpy - INFO - Chain [1] done processing
12:30:02 - cmdstanpy - INFO - Chain [1] start processing
12:30:02 - cmdstanpy - INFO - Chain [1] done processing
12:30:02 - cmdstanpy - INFO - Chain [1] start processing
12:30:03 - cmdstanpy - INFO - Chain [1] done processing
12:30:03 - cmdstanpy - INFO - Chain [1] start processing
12:30:03 - cmdstanpy - INFO - Chain [1] done processing
12:30:04 - cmdstanpy - INFO - Chain [1] start processing
12:30:04 - cmdstanpy - INFO - Chain [1] done processing
12:30:04 - cmdstanpy - INFO - Chain [1] start processing
12:30:05 - cmdstanpy - INFO - Chain [1] done processing
12:30:05 - cmdstanpy - INFO - Chain [1] start processing
12:30:05 - cmdstanpy - INFO - Chain [1] done processing
12:30:06 - cmdstanpy - INFO - Chain [1] start processing
12:30:06 - cmdstanpy - INFO - Chain [1] done processing
12:30:06 - cmdstanpy - INFO - Chain [1] start processing
12:30:07 - cmdstanpy - INFO - Chain [1] done processing
12:30:07 - cmdstanpy - INFO - Chain [1] start processing
12:30:07 - cmdstanpy - INFO - Chain [1] done processing
12:30:08 - cmdstanpy - INFO - Chain [1] start processing
12:30:08 - cmdstanpy - INFO - Chain [1] done processing
12:30:08 - cmdstanpy - INFO - Chain [1] start processing
12:30:08 - cmdstanpy - INFO - Chain [1] done processing
12:30:09 - cmdstanpy - INFO - Chain [1] start processing
12:30:09 - cmdstanpy - INFO - Chain [1] done processing
12:30:09 - cmdstanpy - INFO - Chain [1] start processing
12:30:09 - cmdstanpy - INFO - Chain [1] done processing
12:30:10 - cmdstanpy - INFO - Chain [1] start processing
12:30:10 - cmdstanpy - INFO - Chain [1] done processing
12:30:10 - cmdstanpy - INFO - Chain [1] start processing
12:30:11 - cmdstanpy - INFO - Chain [1] done processing
12:30:11 - cmdstanpy - INFO - Chain [1] start processing
12:30:11 - cmdstanpy - INFO - Chain [1] done processing
12:30:11 - cmdstanpy - INFO - Chain [1] start processing
12:30:12 - cmdstanpy - INFO - Chain [1] done processing
12:30:12 - cmdstanpy - INFO - Chain [1] start processing
12:30:12 - cmdstanpy - INFO - Chain [1] done processing
12:30:13 - cmdstanpy - INFO - Chain [1] start processing
12:30:13 - cmdstanpy - INFO - Chain [1] done processing
12:30:13 - cmdstanpy - INFO - Chain [1] start processing
12:30:13 - cmdstanpy - INFO - Chain [1] done processing
12:30:14 - cmdstanpy - INFO - Chain [1] start processing
12:30:14 - cmdstanpy - INFO - Chain [1] done processing
12:30:14 - cmdstanpy - INFO - Chain [1] start processing
12:30:14 - cmdstanpy - INFO - Chain [1] done processing
12:30:15 - cmdstanpy - INFO - Chain [1] start processing
12:30:15 - cmdstanpy - INFO - Chain [1] done processing
12:30:15 - cmdstanpy - INFO - Chain [1] start processing
12:30:15 - cmdstanpy - INFO - Chain [1] done processing
12:30:16 - cmdstanpy - INFO - Chain [1] start processing
12:30:16 - cmdstanpy - INFO - Chain [1] done processing
12:30:17 - cmdstanpy - INFO - Chain [1] start processing
12:30:17 - cmdstanpy - INFO - Chain [1] done processing
12:30:17 - cmdstanpy - INFO - Chain [1] start processing
12:30:18 - cmdstanpy - INFO - Chain [1] done processing
12:30:18 - cmdstanpy - INFO - Chain [1] start processing
12:30:18 - cmdstanpy - INFO - Chain [1] done processing
12:30:19 - cmdstanpy - INFO - Chain [1] start processing
12:30:19 - cmdstanpy - INFO - Chain [1] done processing
12:30:20 - cmdstanpy - INFO - Chain [1] start processing
12:30:20 - cmdstanpy - INFO - Chain [1] done processing
12:30:21 - cmdstanpy - INFO - Chain [1] start processing
12:30:21 - cmdstanpy - INFO - Chain [1] done processing
12:30:21 - cmdstanpy - INFO - Chain [1] start processing
12:30:22 - cmdstanpy - INFO - Chain [1] done processing
12:30:22 - cmdstanpy - INFO - Chain [1] start processing
12:30:23 - cmdstanpy - INFO - Chain [1] done processing
12:30:23 - cmdstanpy - INFO - Chain [1] start processing
12:30:24 - cmdstanpy - INFO - Chain [1] done processing
12:30:24 - cmdstanpy - INFO - Chain [1] start processing
12:30:24 - cmdstanpy - INFO - Chain [1] done processing
12:30:25 - cmdstanpy - INFO - Chain [1] start processing
12:30:25 - cmdstanpy - INFO - Chain [1] done processing
12:30:26 - cmdstanpy - INFO - Chain [1] start processing
12:30:26 - cmdstanpy - INFO - Chain [1] done processing
12:30:27 - cmdstanpy - INFO - Chain [1] start processing
12:30:27 - cmdstanpy - INFO - Chain [1] done processing
12:30:27 - cmdstanpy - INFO - Chain [1] start processing
12:30:28 - cmdstanpy - INFO - Chain [1] done processing
12:30:28 - cmdstanpy - INFO - Chain [1] start processing
12:30:28 - cmdstanpy - INFO - Chain [1] done processing
12:30:29 - cmdstanpy - INFO - Chain [1] start processing
12:30:29 - cmdstanpy - INFO - Chain [1] done processing
12:30:30 - cmdstanpy - INFO - Chain [1] start processing
12:30:30 - cmdstanpy - INFO - Chain [1] done processing
12:30:31 - cmdstanpy - INFO - Chain [1] start processing
12:30:31 - cmdstanpy - INFO - Chain [1] done processing
12:30:32 - cmdstanpy - INFO - Chain [1] start processing
12:30:32 - cmdstanpy - INFO - Chain [1] done processing
12:30:32 - cmdstanpy - INFO - Chain [1] start processing
12:30:33 - cmdstanpy - INFO - Chain [1] done processing
12:30:33 - cmdstanpy - INFO - Chain [1] start processing
12:30:34 - cmdstanpy - INFO - Chain [1] done processing
12:30:34 - cmdstanpy - INFO - Chain [1] start processing
12:30:34 - cmdstanpy - INFO - Chain [1] done processing
12:30:35 - cmdstanpy - INFO - Chain [1] start processing
12:30:35 - cmdstanpy - INFO - Chain [1] done processing
12:30:35 - cmdstanpy - INFO - Chain [1] start processing
12:30:35 - cmdstanpy - INFO - Chain [1] done processing
12:30:36 - cmdstanpy - INFO - Chain [1] start processing
12:30:36 - cmdstanpy - INFO - Chain [1] done processing
12:30:37 - cmdstanpy - INFO - Chain [1] start processing
12:30:37 - cmdstanpy - INFO - Chain [1] done processing
12:30:37 - cmdstanpy - INFO - Chain [1] start processing
12:30:37 - cmdstanpy - INFO - Chain [1] done processing
12:30:38 - cmdstanpy - INFO - Chain [1] start processing
12:30:38 - cmdstanpy - INFO - Chain [1] done processing
12:30:38 - cmdstanpy - INFO - Chain [1] start processing
12:30:38 - cmdstanpy - INFO - Chain [1] done processing
12:30:39 - cmdstanpy - INFO - Chain [1] start processing
12:30:39 - cmdstanpy - INFO - Chain [1] done processing
12:30:39 - cmdstanpy - INFO - Chain [1] start processing
12:30:39 - cmdstanpy - INFO - Chain [1] done processing
12:30:40 - cmdstanpy - INFO - Chain [1] start processing
12:30:40 - cmdstanpy - INFO - Chain [1] done processing
12:30:40 - cmdstanpy - INFO - Chain [1] start processing
12:30:41 - cmdstanpy - INFO - Chain [1] done processing
12:30:41 - cmdstanpy - INFO - Chain [1] start processing
12:30:41 - cmdstanpy - INFO - Chain [1] done processing
12:30:41 - cmdstanpy - INFO - Chain [1] start processing
12:30:42 - cmdstanpy - INFO - Chain [1] done processing
12:30:42 - cmdstanpy - INFO - Chain [1] start processing
12:30:42 - cmdstanpy - INFO - Chain [1] done processing
12:30:42 - cmdstanpy - INFO - Chain [1] start processing
12:30:42 - cmdstanpy - INFO - Chain [1] done processing
12:30:43 - cmdstanpy - INFO - Chain [1] start processing
12:30:43 - cmdstanpy - INFO - Chain [1] done processing
12:30:43 - cmdstanpy - INFO - Chain [1] start processing
12:30:43 - cmdstanpy - INFO - Chain [1] done processing
12:30:44 - cmdstanpy - INFO - Chain [1] start processing
12:30:44 - cmdstanpy - INFO - Chain [1] done processing
12:30:44 - cmdstanpy - INFO - Chain [1] start processing
12:30:44 - cmdstanpy - INFO - Chain [1] done processing
12:30:45 - cmdstanpy - INFO - Chain [1] start processing
12:30:45 - cmdstanpy - INFO - Chain [1] done processing
12:30:45 - cmdstanpy - INFO - Chain [1] start processing
12:30:45 - cmdstanpy - INFO - Chain [1] done processing
12:30:46 - cmdstanpy - INFO - Chain [1] start processing
12:30:46 - cmdstanpy - INFO - Chain [1] done processing
12:30:46 - cmdstanpy - INFO - Chain [1] start processing
12:30:46 - cmdstanpy - INFO - Chain [1] done processing
12:30:47 - cmdstanpy - INFO - Chain [1] start processing
12:30:47 - cmdstanpy - INFO - Chain [1] done processing
12:30:47 - cmdstanpy - INFO - Chain [1] start processing
12:30:47 - cmdstanpy - INFO - Chain [1] done processing
12:30:48 - cmdstanpy - INFO - Chain [1] start processing
12:30:48 - cmdstanpy - INFO - Chain [1] done processing
12:30:48 - cmdstanpy - INFO - Chain [1] start processing
12:30:49 - cmdstanpy - INFO - Chain [1] done processing
12:30:49 - cmdstanpy - INFO - Chain [1] start processing
12:30:49 - cmdstanpy - INFO - Chain [1] done processing
12:30:50 - cmdstanpy - INFO - Chain [1] start processing
12:30:50 - cmdstanpy - INFO - Chain [1] done processing
12:30:51 - cmdstanpy - INFO - Chain [1] start processing
12:30:51 - cmdstanpy - INFO - Chain [1] done processing
12:30:51 - cmdstanpy - INFO - Chain [1] start processing
12:30:52 - cmdstanpy - INFO - Chain [1] done processing
12:30:52 - cmdstanpy - INFO - Chain [1] start processing
12:30:52 - cmdstanpy - INFO - Chain [1] done processing
12:30:53 - cmdstanpy - INFO - Chain [1] start processing

Результаты прогнозов Prophet на 3 месяца:

,Регион,Test start,Test end,RMSE,MAE,MAPE_%,Forecast,Actual
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-08,2024-10,0.00,0.00,inf,"[0.0, -0.0, -0.0]","[0.0, 0.0, 0.0]"
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-09,2024-11,0.00,0.00,inf,"[-0.0, -0.0, 0.0]","[0.0, 0.0, 0.0]"
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-10,2024-12,0.00,0.00,inf,"[-0.0, 0.0, 0.0]","[0.0, 0.0, 0.0]"
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-11,2025-01,0.00,0.00,inf,"[0.0, 0.0, -0.0]","[0.0, 0.0, 0.0]"
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2024-12,2025-02,0.00,0.00,inf,"[0.0, -0.0, -0.0]","[0.0, 0.0, 0.0]"
...,...,...,...,...,...,...,...,...
195,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-01,2025-03,6.86,6.41,8.88,"[72.15, 68.41, 101.11]","[69.2, 60.13, 93.1]"
196,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-02,2025-04,7.85,7.84,10.28,"[68.48, 100.99, 93.07]","[60.13, 93.1, 85.8]"
197,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-03,2025-05,5.32,4.39,4.90,"[99.94, 91.97, 96.78]","[93.1, 85.8, 96.61]"
198,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-04,2025-06,5.73,4.80,4.97,"[91.14, 95.9, 96.65]","[85.8, 96.61, 105.0]"
199,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,2025-05,2025-07,5.04,3.70,4.31,"[95.76, 96.49, 42.36]","[96.61, 105.0, 44.1]"

Средние метрики Prophet по регионам (rolling-3):

                            Регион        RMSE         MAE  MAPE_%
0              АКМОЛИНСКАЯ ОБЛАСТЬ        0.00        0.00     NaN
1              АКТЮБИНСКАЯ ОБЛАСТЬ       22.66       19.19   11.96
2              АЛМАТИНСКАЯ ОБЛАСТЬ       50.19       36.96  326.40
3               АТЫРАУСКАЯ ОБЛАСТЬ      227.59      171.11   28.43
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ        0.74        0.52     NaN
5                          ГАЛМАТЫ        0.00        0.00     NaN
6                          ГАСТАНА        0.00        0.00     NaN
7                         ГШЫМКЕНТ        0.00        0.00     NaN
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ       17.19       13.13   39.58
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ        4.19        3.58   47.04
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ        4.16        3.01     NaN
11            КОСТАНАЙСКАЯ ОБЛАСТЬ        0.21        0.12     NaN
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ     1122.56      986.02  306.88
13           МАНГИСТАУСКАЯ ОБЛАСТЬ      146.75      116.67   33.17
14                    ОБЛАСТЬ АБАЙ  8803222.95  5082544.60     NaN
15                  ОБЛАСТЬ ЖЕТІСУ 74061576.87 42759488.72     NaN
16                  ОБЛАСТЬ ҰЛЫТАУ   244699.29   141277.20     NaN
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ        0.02        0.01     NaN
18    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ        0.00        0.00     NaN
19           ТУРКЕСТАНСКАЯ ОБЛАСТЬ       93.73       63.03   17.35

In [9]:
# Переименуем колонки с MAPE, чтобы было понятно, к какому методу относятся
hw = final_hw.rename(columns={"MAPE_%": "MAPE_HW"})
sar = final_sarima.rename(columns={"MAPE_%": "MAPE_SARIMA"})
pr  = final_prophet.rename(columns={"MAPE_%": "MAPE_Prophet"})

# Мёрджим по региону
summary = (
    hw[["Регион", "MAPE_HW"]]
    .merge(sar[["Регион", "MAPE_SARIMA"]], on="Регион")
    .merge(pr[["Регион", "MAPE_Prophet"]], on="Регион")
)

# Определяем для каждой строки, какой столбец MAPE минимален
# idxmin вернёт название столбца с минимальным значением
summary["Best_method"] = summary[["MAPE_HW","MAPE_SARIMA","MAPE_Prophet"]] \
                           .idxmin(axis=1) \
                           .str.replace("MAPE_","")  # убираем префикс для красоты

# Если нужно, можно сразу отсортировать
# summary = summary.sort_values("Best_method")

# допустим, у вас уже есть summary
summary = summary.round({
    "MAPE_HW": 2,
    "MAPE_SARIMA": 2,
    "MAPE_Prophet": 2
})

# Готово!
print(summary.to_string(index=False))
summary.to_excel("results/Верблюды - лучшие модели.xlsx", index=False)

                        Регион  MAPE_HW                 MAPE_SARIMA  MAPE_Prophet Best_method
           АКМОЛИНСКАЯ ОБЛАСТЬ      NaN       234298811075384160.00           NaN      SARIMA
           АКТЮБИНСКАЯ ОБЛАСТЬ     2.23                        2.34         11.96          HW
           АЛМАТИНСКАЯ ОБЛАСТЬ    86.55                       88.69        326.40          HW
            АТЫРАУСКАЯ ОБЛАСТЬ    13.84                       16.87         28.43          HW
ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ      NaN   4481981798858405445632.00           NaN      SARIMA
                       ГАЛМАТЫ      NaN 236118088025158109364224.00           NaN      SARIMA
                       ГАСТАНА      NaN                        0.00           NaN      SARIMA
                      ГШЫМКЕНТ      NaN 236118088025158109364224.00           NaN      SARIMA
            ЖАМБЫЛСКАЯ ОБЛАСТЬ     7.23                        7.06         39.58      SARIMA
 ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ     9.20                       22.82         47.04          HW
        КАРАГАНДИНСКАЯ ОБЛАСТЬ      NaN 326876682879239821721600.00           NaN      SARIMA
          КОСТАНАЙСКАЯ ОБЛАСТЬ      NaN     35872498088695361536.00           NaN      SARIMA
        КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ    44.56                       46.28        306.88          HW
         МАНГИСТАУСКАЯ ОБЛАСТЬ    32.34                       43.24         33.17          HW
                  ОБЛАСТЬ АБАЙ      NaN   3075002658089149136896.00           NaN      SARIMA
                ОБЛАСТЬ ЖЕТІСУ      NaN       303175941370688064.00           NaN      SARIMA
                ОБЛАСТЬ ҰЛЫТАУ      NaN                       15.00           NaN      SARIMA
          ПАВЛОДАРСКАЯ ОБЛАСТЬ      NaN      4878482432353040384.00           NaN      SARIMA
  СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ      NaN      3116639736815846912.00           NaN      SARIMA
         ТУРКЕСТАНСКАЯ ОБЛАСТЬ    20.88                       23.49         17.35     Prophet